### ISSUE TITLE
extra-gnome/gnome-calendar : Startup very slow in gnome-shell's launcher

### ISSUE THREAD

**Issue by bobcao3** [AOSC-Dev/aosc-os-abbs#100]
When I start the gnome-calendar by the gnome-shell's launcher, its window pops up with many seconds of lagging. When I start the program by terminal or SESDE's launcher, it started in a flash.

**Comment by MingcongBai** [comment]
I did notice the lag, not sure currently though.

**Comment by MingcongBai** [comment]
Fixed as of `gnome-shell` 3.18.1.
