### ISSUE TITLE
Please update to uriparser 0.8.5

### ISSUE THREAD

**Issue by hartwork** [AOSC-Dev/aosc-os-abbs#1000]
Hi!

uriparser 0.8.5 has been released:
https://github.com/uriparser/uriparser/releases

Thanks for updating!

**Comment by hartwork** [comment]
Any news or any obstacles I should know about? Thanks!

**Comment by MingcongBai** [comment]
Don't worry... We are currently a bit short on people, we should be able to get it within the coming days. Thanks for the report!

**Comment by LionNatsu** [comment]
Off topic: one thousand!

**Comment by hartwork** [comment]
Looks like fixed by 4d54d61fed899b4907241a30c9869467aa553824. Thanks @MingcongBai !
