### ISSUE TITLE
Package request: the whole lzip family

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#101]
And for zutils, add alternatives. I think it's a sound idea to use it instead of those `zcat` stuffs in gzip in our offical releases.

**Comment by MingcongBai** [comment]
I will first import them into the tree, and we can go from there.

**Comment by MingcongBai** [comment]
`zutils` now available to replace utilities from `gzip`.

**Comment by Arthur2e5** [comment]
wow, super fast

**Comment by MingcongBai** [comment]
> wow, super fast

I have nothing to compain except that `zutils` needs `gcc-runtime`...

**Comment by Arthur2e5** [comment]
If that annoys you, try libtcc (?!)… It's only some glue programs so performance won't matter a much.
