### ISSUE TITLE
gwenview: sofile is missing

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#1012]
gwenview: error while loading shared libraries: libexiv2.so.14: cannot open shared object file: No such file or directory

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/4f4d2e7a6c679415eede1fb72429346ce5b17dfa. Closing, sorry for the delay.

**Comment by MingcongBai** [comment]
@bobby285271 问题修复…… 实在抱歉之前没有看见这个 issue
