### ISSUE TITLE
kernel-tools: missing "perf" tool

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#1018]

**Comment by lmy441900** [comment]
Look at https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools and https://github.com/AOSC-Dev/aosc-os-abbs/blob/staging/extra-kernel/kernel-tools/autobuild/build and it's easy to find out that there are still many "kernel tools" not packed, and `perf` is one of them.

One possible reason is that some tools are packed into another package, so they are not in the `kernel-tools` package. Further investigation needed.

**Comment by LionNatsu** [comment]
@lmy441900 > so they are not in the kernel-tools package. Further investigation needed.

I know you mean: let's do our skillful system-wide grep. (No, abbs-wide actually.)

**Comment by LionNatsu** [comment]
Why don't we just simply run `make`? (/tools/Makefile)

**Comment by LionNatsu** [comment]
So, what's next? For using the perf, I don't think I should issue a packaging request because there's kernel-tools already.

**Comment by MingcongBai** [comment]
I'm currently buried in a large collection of updates - I will come back to this possibly in the following week...

**Comment by MingcongBai** [comment]
> Why don't we just simply run make? (/tools/Makefile)

All tools are built differently, there's no uniform way to make and install (package) them all. I'll at least make sure `perf` is built. Other than that, if you want anything else, please open a different issue.
