### ISSUE TITLE
Package Request: GNU hello

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#102]
GNU hello is indeed the best program, ever, that the GNU guys have written. It brings the joy of seeing a familiar and friendly greeting to ordinary users, and shows new GNU contributors how a neat GNU project should look like. It breaks the boundary between lusers and coders with the simplest greeting: hello, world! 

> [...] Truly, hello is familiar and the friendliest. (Gnur'an 0x27:0x35 "The indeed and truly book")

And we should make it a sample for new autobuild packers, too. And please include these text in the PKGDES.

**Comment by biergaizi** [comment]
+1

**Comment by Icenowy** [comment]
Xuanology

---- Mingye Wang编写 ----

GNU hello is indeed the best program, ever, that the GNU guys has made. It brings the joy of seeing a familiar and friendly greeting to ordinary users, and shows new GNU contributors how a neat GNU project should look like. It breaks the boundary between lusers and coders with the simplest greeting: hello, world!

And we should make it a sample for new autobuild packers, too. And please include these text in the PKGDES.

---
Reply to this email directly or view it on GitHub:
https://github.com/AOSC-Dev/aosc-os-abbs/issues/102
