### ISSUE TITLE
xkeyboard-config: apply changes for pinyin keyboard

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#1026]
* AOSC-Dev/aosc-os#9 contains a definiton for a pinyin layout. Append the segment to `/usr/share/X11/xkb/symbols/cn`.
* Mention the layout in `rules/base.xml.in`.
* Change `/usr/share/X11/locale/zh_CN.UTF-8` so that it starts with a line that says `include %S/en_US.UTF-8/Compose`. Perhaps try it without the change first so we know whether it's necessary?

If you can make this a cool little patch, please do it. It seems to match Xkb's [submission rules](https://www.freedesktop.org/wiki/Software/XKeyboardConfig/Rules/), but we might need to waste some time on convincing Xlib people that zh_CN needs dead keys.

**Comment by Artoria2e5** [comment]
tracking upstream https://bugs.freedesktop.org/show_bug.cgi?id=105168

**Comment by Artoria2e5** [comment]
The compose TODO is an error. There's already an `include` line there. I didn't see it because I wasn't pressing `f` in `less`.

**Comment by MingcongBai** [comment]
What is the current status on this proposal? Doesn't seem to have much going on, on the Bugzilla side.

**Comment by Artoria2e5** [comment]
Upstream merged to git.

**Comment by MingcongBai** [comment]
Sounds good!

**Comment by MingcongBai** [comment]
Introduced with e84abf44634b8f8a22d16e1c0d0f96af5c32e5c7 (v2.28). Closing.

@Artoria2e5 Thanks again for your work!
