### ISSUE TITLE
Package Request: tcc

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#103]
We need a smaller ANSI C compiler which acts interestingly with undefined behavior.

**Comment by Trickness** [comment]
TCC 的 ARM 版 弄到 Android 上会有什么神奇的化学反应？


>>End of mail





On Wed, Oct 21, 2015 at 6:47 PM -0700, "Mingye Wang" <notifications@github.com> wrote:
We need a smaller ANSI C compiler which acts interestingly with undefined behavior.

---
Reply to this email directly or view it on GitHub:
https://github.com/AOSC-Dev/aosc-os-abbs/issues/103

**Comment by Icenowy** [comment]
C4Droid默认编译器

**Comment by Icenowy** [comment]
C4Droid默认编译器
