### ISSUE TITLE
ruby: multiple vulnerabilities in RubyGems

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1043]
https://www.ruby-lang.org/en/news/2018/02/17/multiple-vulnerabilities-in-rubygems/

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/a89d65760fcdc8bc9ff3e0c8f0f71bad06dce075. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0106.
