### ISSUE TITLE
openjdk: go for icedtea 8?

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#1080]
Icedtea 3.8.0 seems to have dropped the very wrong infinality requirement and replaced it with `--enable-improved-font-rendering` in configure. (http://icedtea.classpath.org/hg/icedtea8/rev/cd09a97434bd) In other words they are probably reliable now…

**Comment by MingcongBai** [comment]
Wouldn't be a bad idea, but it will probably be smart to evaluate its JIT support - if it's any worse than what Orcale is able to dish out, I'll advise against it...

**Comment by liushuyu** [comment]
So, what's the decision on this?

**Comment by MingcongBai** [comment]
@liushuyu If you could investigate the JIT support issue as mentioned above it would be much appreciated.

**Comment by liushuyu** [comment]
>@liushuyu If you could investigate the JIT support issue as mentioned above it would be much appreciated.

Actually, IcedTea uses the same JIT as the OpenJDK with several patches from Red Hat. So the performance should be close or the same as the OpenJDK.

**Comment by MingcongBai** [comment]
@liushuyu In that case, since you are the de facto Java maintainer these days, you'll make the call here.

**Comment by liushuyu** [comment]
>@liushuyu In that case, since you are the de facto Java maintainer these days, you'll make the call here.

So I need to ask how long you can wait when a security issue is discovered? If your answer is within a week, then IcedTea is not suitable. Usually, IcedTea will release the corresponding version after approximately one month.

**Comment by MingcongBai** [comment]
@liushuyu Is font rendering the only “practical” (minus licensing or any other moral claims...) advantage that IcedTea hold over OpenJDK?

**Comment by liushuyu** [comment]
>@liushuyu Is font rendering the only “practical” (minus licensing or any other moral claims...) advantage that IcedTea hold over OpenJDK?

IcedTea also comes bundled with `aarch32/aarch64` JIT and various staging features that not yet included in upstream OpenJDK (like `wine-staging`)

**Comment by MingcongBai** [comment]
@liushuyu Well. If security update indeed takes a month, I’ll say no to this...

**Comment by liushuyu** [comment]
>@liushuyu Is font rendering the only “practical” (minus licensing or any other moral claims...) advantage that IcedTea hold over OpenJDK?

I can give you an example: `8u191` was released on [Oct 08, 2018](http://hg.openjdk.java.net/jdk8u/jdk8u/rev/b425c4315c20) and the corresponding IcedTea release 3.10.0 was released on [Dec 26, 2018](http://icedtea.classpath.org/hg/icedtea8/rev/e6a21c71b123)

Although IcedTea said it does "Inclusion of bug fixes ahead of inclusion in upstream OpenJDK" but it is difficult to tell which patch fixed which issue since all the patches were named after the `hg` commit hash.

**Comment by MingcongBai** [comment]
@liushuyu @l2dy What are your thoughts on this?

**Comment by l2dy** [comment]
> > @liushuyu Is font rendering the only “practical” (minus licensing or any other moral claims...) advantage that IcedTea hold over OpenJDK?
> 
> IcedTea also comes bundled with `aarch32/aarch64` JIT and various staging features that not yet included in upstream OpenJDK (like `wine-staging`)

Can we package IcedTea separately?

**Comment by liushuyu** [comment]
> Can we package IcedTea separately?

They provide substantially the same functionality. Packaging IcedTea flavored OpenJDK is acceptable but when OpenJDK has security issues, these two will both need to be fixed, or confirmation of the corresponding fix is already present.

**Comment by MingcongBai** [comment]
Seems like now with OpenJDK 11 as mainline, we have moved past this issue. Closing.
