### ISSUE TITLE
fontconfig: infer generic classes from font files

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#1090]
We don't need to write those boring files assigning families to sans/serif/monospace if fontconfig could read those from font files. This experimental functionality is provided at an upstream branch at https://cgit.freedesktop.org/~tagoh/fontconfig/commit/?h=panose-sfamilyclass-support; to adapt it for the srb patch, try adding a ", NULL" to the last fcobj entry.

Upstream bug: https://bugs.freedesktop.org/show_bug.cgi?id=29497

**Comment by MingcongBai** [comment]
This is pretty cool...

**Comment by Artoria2e5** [comment]
According to TAGOH it has been used in Fedora since Fedora 18, but I am not sure about the new versions. The branch has been continually rebased, so I guess it means that it's still fresh?

**Comment by MingcongBai** [comment]
Stalled (feature/design change) issue, closing. Please open a new issue if this thought arises again.
