### ISSUE TITLE
exempi: security update to 2.4.5

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1096]
https://github.com/hfiguiere/exempi/blob/2.4.5/NEWS

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/42dbb28af42b51d03383d8eb39429d70c65118f7. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0140.
