### ISSUE TITLE
audacious: coredump

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#1099]
Add dependency: audacious-plugins

Log:
```
ERROR plugin-init.cc:147 [start_required]: No output plugin found.
(Did you forget to install audacious-plugins?)
中止 (コアダンプ)
```

**Comment by cthbleachbit** [comment]
`audacious-plugins` need `audacious` as build dependency. Adding `audacious-plugin` to `audacious` makes a stage 2 situation...

**Comment by cthbleachbit** [comment]
Meanwhile audacious would `abort` itself if it finds no plugins upon start.

**Comment by MingcongBai** [comment]
@cthbleachbit Would it be a valid thought to just merge the packages since they won't function independently anyways?

**Comment by cthbleachbit** [comment]
~~You've shown me the way.~~ That works.

**Comment by cthbleachbit** [comment]
So actually audacious plugins are linked against audacious shared objects, so the plugins won't compile without audcious installed properly.

**Comment by MingcongBai** [comment]
Fixed. Closing.
