### ISSUE TITLE
tree: O2 override prevention

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#110]
# The issue

All around the tree, a considerable amount of packages are pre-configured to use `-O3` flag in their (generated or not) Makefiles. However, with autobuild3, `-O2` is configured as part of `$CFLAGS`, `$CXXFLAGS`, `$CPPFLAGS`. However, when building, `-O2` may be printed behind the pre-configured `-O3` flag.

... TL;DR: if upstream says `-O3`, why don't we stop being paranoid...
# To solve

Inspection of packages? On the go?... Up for discussion.

**Comment by Arthur2e5** [comment]
`gcc` needs a `--optimize-at-least=2` option. (Just kidding

**Comment by MingcongBai** [comment]
Hah... Very funny. No.

**Comment by MingcongBai** [comment]
This issue is warned by @felixonmars of possible breakage.

**Comment by Arthur2e5** [comment]
I think he was talking about forcing stack protection.

**Comment by MingcongBai** [comment]
> I think he was talking about forcing stack protection.

A universal rebuild for such was already done in May.

**Comment by LionNatsu** [comment]
Yes?

**Comment by LionNatsu** [comment]
`${CPPFLAGS/-O2/}` is useless now, isn't it?...

They need some reverts(to clean these replacement) now.

**Comment by LionNatsu** [comment]
@LionNatsu CC: @JeffBai

**Comment by MingcongBai** [comment]
Indeed. It was an issue where we explicitly specified `-O2` in `$CPPFLAGS` to work around some issues like...

"FORTIFY_SOURCE requires optimization (-O)"

... Something similar to the message above.

So we did an ugly hack to deal with it. I have already removed it with the new Core 4 update, which will require packagers to deal with the issue above themselves (through means of patching or environment variable tinkling...).

> They need some reverts(to clean these replacement) now.

Not reverts, deal with it like a code clean up that happened after the original event. But they shouldn't hurt as is right now.

**Comment by LionNatsu** [comment]
But now the title should be changed, right...?

**Comment by MingcongBai** [comment]
> But now the title should be changed, right...?

Still is relevant though. The issue is one regarding that some packages shipped with `-O3` with default, but were overriden with `autobuild`'s own set of flags, which contains `-O2`.

**Comment by LionNatsu** [comment]
Can ab remove the default `-O*` flag (with a wildcard)? Then it solve the problem that packages *Yindian'ed* any level of optimizing option.

**Comment by MingcongBai** [comment]
> Can ab remove the default -O* flag (with a wildcard)?

Instead I have implemented `AB_FLAGS_O3` with the newest updates, but that's actually a good idea.

> Then it solve the problem...

Not quite, we will still need to survey, or "chart" all the packages that does that. This will be a long-term effort.

> Yindian'ed any level of optimizing option.

While it's funny, please limit such language that may bring confusion to those who does not understand Chinese or the joke behind it.

**Comment by MingcongBai** [comment]
Stalled (feature/design change) issue, closing. Please open a new issue if this thought arises again.
