### ISSUE TITLE
palemoon: update to 27.8.3

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1103]
https://www.palemoon.org/releasenotes.shtml
>Backed out some responsive layout code that caused intermittent but not uncommon crashes in the browser depending on window sizes and page content.

https://forum.palemoon.org/viewtopic.php?t=18735
>Otherwise there are no changes in this release. It's recommended everyone update to this version ASAP to prevent potential data loss due to crashes.

**Comment by MingcongBai** [comment]
Updated package with https://github.com/AOSC-Dev/aosc-os-abbs/commit/a0ecf1b9b1bce32696c40c5264863e870424fcd2.

**Comment by l2dy** [comment]
Use AOSA-2018-0147.

**Comment by l2dy** [comment]
AOSA-2018-0147 revoked.
