### ISSUE TITLE
32subsystem: degrade to runtime libraries and headers only

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#111]
32subsystem is for compatibility purpose only, which does not require certain data files (icons, desktop entries, manpages, ...) to be installed with the packages. This issue is used for tracking the process of degrading 32subsystem into runtime libraries (with exceptions for toolchain packages).

**Comment by Icenowy** [comment]
no

**Comment by MingcongBai** [comment]
Process is almost over. Current exceptions: `gcc+32`, `nasm+32`, `binutils+32`, `llvm+32`, as they are all code generating programs that are installed in such place (`/opt/32/bin`).

A change to `32subsystem` directory structure is that `share` is now managed by `32subsystem` the package itself, not `glibc`, as `/opt/32/share` as whole is now a symlink to `/usr/share`.

More to report in about 2 hours as the rebuild will be over by the time.

**Comment by MingcongBai** [comment]
To this point, all rebuilds are complete, now it's time to implement the new structure from inside of `32subsystem`.

**Comment by MingcongBai** [comment]
`/opt/32` is now half in size as it was before.

**Comment by MingcongBai** [comment]
Concluding this case as `wine` 1.7.45 built and run successfully with the new subsys build.
