### ISSUE TITLE
nmap: security update to 7.70

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1114]
Low severity and our next wave is close, so `to-staging`.

http://seclists.org/nmap-announce/2018/0
* [NSE][SECURITY] Nmap developer nnposter found a security flaw (directory
traversal vulnerability) in the way the non-default http-fetch script
sanitized URLs. If a user manualy ran this NSE script against a malicious
web server, the server could potentially (depending on NSE arguments used)
cause files to be saved outside the intended destination directory.
Existing files couldn't be overwritten.  We fixed http-fetch, audited our
other scripts to ensure they didn't make this mistake, and updated the
httpspider library API to protect against this by default. [nnposter,
Daniel Miller]

**Comment by MingcongBai** [comment]
Addressed in `staging` with 423c622c0. AOSA pending.

**Comment by l2dy** [comment]
Use AOSA-2018-0173.
