### ISSUE TITLE
krb5: security regression

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1125]

**Comment by MingcongBai** [comment]
In reference to original issue https://github.com/AOSC-Dev/aosc-os-abbs/issues/

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/32b4f64d91d9c567830cb365be7868fce76828ba. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0182.
