### ISSUE TITLE
sqlite: security regression

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1126]

**Comment by MingcongBai** [comment]
In reference to original issue https://github.com/AOSC-Dev/aosc-os-abbs/issues/1079

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/6e93620ba117aaaa59a49052e0bceaf5f9f11a47. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0183.
