### ISSUE TITLE
libvirt: security regression

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1127]

**Comment by MingcongBai** [comment]
In reference to https://github.com/AOSC-Dev/aosc-os-abbs/issues/1107

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/a0085286c17d0999fdb6f30123aedfdc9e968b85. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0184.
