### ISSUE TITLE
packagekit: security update to 1.1.10

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1138]
http://www.openwall.com/lists/oss-security/2018/04/23/3

https://github.com/hughsie/PackageKit/blob/PACKAGEKIT_1_1_10/NEWS#L6

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/65c058dca054f443129f22e6e2de9e0a36a2f8be. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0193.
