### ISSUE TITLE
opencl-registry-api: Need a layout to fit in CL 1.2 headers

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#114]
@liushuyu's commet in b90eb0c mentioned that I missed CL 1.2 headers. However, this is basically impractical even in the original version, since `wget` will save some `cl.hpp.1` and the `install` step will still skip it because of its suffix.

**Comment by Arthur2e5** [comment]
Oops, false positive. It's cl2.hpp and cl.hpp.

**Comment by liushuyu** [comment]
We really need this 1.2 version cl.hpp

**Comment by Arthur2e5** [comment]
Fixed already.
