### ISSUE TITLE
quassel: security update to 0.12.5

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1146]
https://quassel-irc.org/node/130
>However, chaign_c has recently discovered two vulnerabilites in the 0.12.4 core, so a new maintenance release is warranted (and an immediate upgrade of 0.12.4 cores is highly recommended!). Since it has been so long since the last release, we've decided to backport over a hundred commits worth of bugfixes and quality-of-life improvements to make upgrading worth your while. Go grab Quassel 0.12.5 from the downloads page!

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/8e0cae174b2c2df318fbbd0ffeec8fbc44d16ab3. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0197.
