### ISSUE TITLE
imagemagick: security update to 6.9.9+44

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1172]
https://github.com/ImageMagick/ImageMagick6/blob/6.9.9-44/ChangeLog
```
2018-03-26  6.9.9-41 Cristy  <quetzlzacatenango@image...>
* Fixed numerous use of uninitialized values, integer overflow, memory
```
https://github.com/ImageMagick/ImageMagick6/compare/6.9.9-40...6.9.9-44

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/d1ef0ff67ff469947a47b07202369141939ce8dd. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0228.
