### ISSUE TITLE
tor: TROVE-2018-005

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1191]
https://blog.torproject.org/tor-0336-released-new-stable-series
* Major bugfixes (security, directory authority, denial-of-service):
  * Fix a bug that could have allowed an attacker to force a directory authority to use up all its RAM by passing it a maliciously crafted protocol versions string. Fixes bug 25517; bugfix on 0.2.9.4-alpha. This issue is also tracked as TROVE-2018-005.

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/a202a67e750101498693a8803e6533d1d123dd23. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0245.
