### ISSUE TITLE
telegram-desktop: unsupport fcitx Chinese IME

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/aosc-os-abbs#1207]
telegram-desktop can't type in Chinese

this is my apt show:
```
sakiiily@eat-x220i [ ~ ] $ apt show telegram-desktop
Package: telegram-desktop
Version: 1.2.24
Essential: no
Section: web
Maintainer: Mingcong Bai <jeffbai@aosc.io>
Installed-Size: 35.5 MB
Provides: telegram, tdesktop
Depends: ffmpeg (>= 3.4.2-4), hicolor-icon-theme (>= 0.15-4), libappindicator (>= 1:12.10.0-1), libnotify (>= 0.7.7-1), minizip (>= 1.2.11), openal-soft (>= 1.17.2-2), openssl (>= 1.0.2o-1), opus (>= 1.2.1), qt-5 (>= 1:5.11.0+wk5.212.0), x265 (>= 2.7-2), dee (>= 1:1.2.7-2), opus (>= 1.2.1)
Download-Size: 18.0 MB
APT-Manual-Installed: yes
APT-Sources: https://mirrors.tuna.tsinghua.edu.cn/anthon/os-amd64/testing/os-amd64/os3-dpkg  Packages
Description: The official Telegram desktop application

```
and my ```.xprofile```:
```
sakiiily@eat-x220i [ ~ ] $ cat .xprofile
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export QT5_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
xcalib -d :0 ~/Thinkpadx240.icc
```
and telegram-desktop 1.1 and fcitx Can input Chinese, but this not

**Comment by liushuyu** [comment]
>and telegram-desktop 1.1 and fcitx Can input Chinese, but this not

Cannot confirm.
Chinese input is possible using `telegram-desktop` 1.2.24 and `fcitx` 4.2.9.6

**Comment by liushuyu** [comment]
@eatradish Please run `fcitx-diagnose` and paste the report to https://pastebin.aosc.io
And comment the link to your report.

**Comment by eatradish** [comment]
@liushuyu @liushuyu 
这里的意思是 1.1 可以，但现在这个版本不行

**Comment by liushuyu** [comment]
> 这里的意思是 1.1 可以，但现在这个版本不行

I know. But I can use fcitx to input Chinese in current version (1.2.24) in Telegram Desktop.
我知道。但是我可以在 1.2.24 版本的 Telegram 客户端中使用 fcitx 输入中文。

**Comment by liushuyu** [comment]
>@eatradish Please run fcitx-diagnose and paste the report to https://pastebin.aosc.io
>And comment the link to your report.

Translation:
>请在终端运行 `fcitx-diagnose` 然后将生成的报告提交到 https://pastebin.aosc.io 并在此 issue 上贴上链接

**Comment by eatradish** [comment]
@liushuyu 尝试下在 mate 下使用

**Comment by liushuyu** [comment]
>@liushuyu 尝试下在 mate 下使用

I'm using mate-desktop rn
我现在使用的就是 mate

**Comment by eatradish** [comment]
@liushuyu this log:
https://pastebin.aosc.io/paste/eNgwIgkdc6dWi8yTUbvYYQ

**Comment by eatradish** [comment]
@liushuyu 已经查明原因，```apt install fcitx-qt5``` 后解决

**Comment by liushuyu** [comment]
@eatradish Okay, close as resolved
