### ISSUE TITLE
gpg, pcsclite: gpg --card-edit gets card error

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#121]
gpg-agent is running, pcscd.service is running.

gpg --card-edit --verbose output:

sijie [ ~ ] $ LC_ALL=C gpg --card-edit --verbose
gpg: NOTE: THIS IS A DEVELOPMENT VERSION!
gpg: It is only intended for test purposes and should NOT be
gpg: used in a production environment or with production keys!

gpg: selecting openpgp failed: Card error
gpg: OpenPGP card not available: Card error

gpg/card> 

systemctl status pcscd output:

root [ sijie ] ! systemctl status -l pcscd
● pcscd.service - PC/SC Smart Card Daemon
   Loaded: loaded (/usr/lib/systemd/system/pcscd.service; indirect; vendor preset: disabled)
   Active: active (running) since 五 2015-12-04 18:47:45 EST; 39s ago
 Main PID: 3414 (pcscd)
   CGroup: /system.slice/pcscd.service
           └─3414 /usr/bin/pcscd --foreground --auto-exit

12月 04 18:47:45 sijie-l450.aosc.xyz systemd[1]: Started PC/SC Smart Card Daemon

dmesg output:

root [ sijie ] # dmesg|tail
[  712.492648] hid-generic 0003:1050:0116.0004: hiddev0,hidraw1: USB HID v1.10 Device [Yubico Yubikey NEO OTP+U2F+CCID] on usb-0000:00:14.0-1/input1
[  940.194490] EXT4-fs (sda5): mounted filesystem with ordered data mode. Opts: discard
[  989.353930] usb 1-1: USB disconnect, device number 7
[  991.134325] usb 1-1: new full-speed USB device number 8 using xhci_hcd
[  991.309455] usb 1-1: ep 0x81 - rounding interval to 64 microframes, ep desc says 80 microframes
[  991.310765] input: Yubico Yubikey NEO OTP+U2F+CCID as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:1050:0116.0005/input/input20
[  991.361533] hid-generic 0003:1050:0116.0005: input,hidraw0: USB HID v1.10 Keyboard [Yubico Yubikey NEO OTP+U2F+CCID] on usb-0000:00:14.0-1/input0
[  991.362244] hid-generic 0003:1050:0116.0006: hiddev0,hidraw1: USB HID v1.10 Device [Yubico Yubikey NEO OTP+U2F+CCID] on usb-0000:00:14.0-1/input1
[  994.696945] input: Yubico Yubikey NEO OTP+U2F+CCID as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:1050:0116.0007/input/input21
[  994.748715] hid-generic 0003:1050:0116.0007: input,hidraw0: USB HID v1.10 Keyboard [Yubico Yubikey NEO OTP+U2F+CCID] on usb-0000:00:14.0-1/input0

**Comment by MingcongBai** [comment]
I will investigate in an hour or so.

**Comment by MingcongBai** [comment]
Multiple packages, that are PC/SC related are pushed (as update and new packages) to both `staging` and `master`. Commits are listed below.

f237a341f41609c57d66d2081d07e961da2b52d0
7a527668f1031b70f33fa2608cfe7fa882248073
437fccb7eeac7764aca2526a7f1a7c9c798cf9e3
7d8dd3588a9cc865af60e2fcd27dc3eea3fdaba8
fe3fd3ad29045126f17e4b0f687babe7e36e1037
d35c36aa8381802529fd1ed44ab378c43a446d38

Please reply with updates on usability on Monday (when I will push them to the repository). Thanks.

**Comment by butangmucat** [comment]
Solved.

**Comment by MingcongBai** [comment]
Can you tell me what else you've installed to solve the issue?

**Comment by butangmucat** [comment]
pcsc tools opensc

**Comment by MingcongBai** [comment]
Appreciate it.
