### ISSUE TITLE
rofi: can't open caja (MATE File Manager) in MATE Desktop

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/aosc-os-abbs#1219]
Hi, 
I try open caja in rofi, But nothing happens, and I don't know how to debug....
Thank you for your help.

**Comment by MingcongBai** [comment]
When invoked via `rofi -show run`, and typed in `caja`, it does launch.

**Comment by eatradish** [comment]
@MingcongBai thanks your reply, I know my I already know my problem

I use `rofi -show`, but this command feature is show window, no open app, try 'rofi -show run` successful.
