### ISSUE TITLE
lightdm: screen flash

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#122]
Whenever the login is present, the screen will flash once.

systemctl status lightdm output:

root [ sijie ] # systemctl status lightdm -l
● lightdm.service - LightDM Display Manager
   Loaded: loaded (/usr/lib/systemd/system/lightdm.service; enabled; vendor preset: disabled)
   Active: active (running) since 五 2015-12-04 18:29:24 EST; 24min ago
     Docs: man:lightdm(1)
 Main PID: 886 (lightdm)
   CGroup: /system.slice/lightdm.service
           ├─ 886 /usr/bin/lightdm
           └─3620 /usr/sbin/X :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch

12月 04 18:29:24 sijie-l450.aosc.xyz systemd[1]: Starting LightDM Display Manager...
12月 04 18:29:24 sijie-l450.aosc.xyz systemd[1]: Started LightDM Display Manager.
12月 04 18:29:24 sijie-l450.aosc.xyz lightdm[914]: pam_unix(lightdm-greeter:session): session opened for user lightdm by (uid=0)
12月 04 18:29:29 sijie-l450.aosc.xyz lightdm[950]: pam_unix(lightdm:session): session opened for user sijie by (uid=0)
12月 04 18:52:48 sijie-l450.aosc.xyz lightdm[3632]: pam_unix(lightdm-greeter:session): session opened for user lightdm by (uid=0)
12月 04 18:52:54 sijie-l450.aosc.xyz lightdm[3653]: pam_unix(lightdm:session): session opened for user sijie by (uid=0)

xorg-server:
Package: xorg-server
Status: install ok installed
Section: x11
Installed-Size: 15676
Maintainer: Jeff Bai jeffbai@aosc.xyz
Architecture: amd64
Version: 1.18.0-2

**Comment by butangmucat** [comment]
dmesg here
[dmesg.txt](https://github.com/AOSC-Dev/aosc-os-abbs/files/52669/dmesg.txt)

**Comment by MingcongBai** [comment]
No specific issue found in the `dmesg.txt` provided.

I am holding this as a long term issue as this is probably a `xf86-video-intel` related issue.

**Comment by MingcongBai** [comment]
Still exists...

**Comment by MingcongBai** [comment]
Please re-open if reproduced.
