### ISSUE TITLE
imagemagick: security update to ^6.9.9+51

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1223]
https://github.com/ImageMagick/ImageMagick6/blob/6.9.9-51/ChangeLog

https://github.com/ImageMagick/ImageMagick6/compare/6.9.9-46...6.9.9-51

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/1f6c5c3221161f60150b1c840ac0e27e8569fecd. Closing.

**Comment by MingcongBai** [comment]
Use AOSA-2018-0269.
