### ISSUE TITLE
xfce4-panel: certain autostart icons still don't show

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#123]
Every once a while when login, the nm-applet icon will not show (though it is started). Re-login workarounds the issue. Similar things happen to iBus (when show, a transparent icon).

sijie [ ~ ] $ dpkg -s xfce4-panel
Package: xfce4-panel
Status: install ok installed
Section: xfce
Installed-Size: 4640
Maintainer: Jeff Bai jeffbai@aosc.xyz
Architecture: amd64
Version: 1:4.12.0

sijie [ ~ ] $ dpkg -s ibus
Package: ibus
Status: install ok installed
Section: x11
Installed-Size: 11040
Maintainer: AOSC Buildbot aosc@members.fsf.org
Architecture: amd64
Version: 1.5.11-0

sijie [ ~ ] $ dpkg -s network-manager-applet
Package: network-manager-applet
Status: install ok installed
Section: gnome
Installed-Size: 7868
Maintainer: Jeff Bai jeffbai@aosc.xyz
Architecture: amd64
Version: 1.0.8

**Comment by butangmucat** [comment]
Or maybe it is the display that is messed up, see pic attached for more info.

![full-screen-shot](http://imgur.com/IwgwvGxl.png)

**Comment by MingcongBai** [comment]
I wouldn't believe that though. I can reproduce it on my laptop. 

By the way, interesting wallpaper you've got there.

**Comment by butangmucat** [comment]
What?

**Comment by MingcongBai** [comment]
Sometimes the tray icons will refuse to load, too.

**Comment by MingcongBai** [comment]
Can you try enabling the system tray plugin and ser what happens? We used custom widgets for the NetworkManager tray icon.

**Comment by butangmucat** [comment]
Re-enabling the tray plugin will fix for both nm applet and ibus

**Comment by butangmucat** [comment]
But only for current session

**Comment by MingcongBai** [comment]
It still disappears if you relogin?

**Comment by butangmucat** [comment]
Re-login and usually ibus will become problematic, sometimes nm too. Seafile seems to be fine.

**Comment by butangmucat** [comment]
All the time.

**Comment by MingcongBai** [comment]
Interesting... Please allow some time for investigation. Although your `xsession-error.txt` file contains largely trivial warnings, but I might look into that anyways.

**Comment by butangmucat** [comment]
This is also the case when using gnome-flashback.

**Comment by MingcongBai** [comment]
> This is also the case when using gnome-flashback.

As the `nm-applet` icon would not show up?

**Comment by MingcongBai** [comment]
http://askubuntu.com/questions/449658/networkmanager-tray-nm-applet-is-gone-after-upgrade-to-14-04-trusty

Might be a usable reference.

**Comment by MingcongBai** [comment]
If you can, try a manual edit on the `Exec=` line as mentioned in the link.

**Comment by butangmucat** [comment]
Didn't work.

**Comment by MingcongBai** [comment]
Hmm...

**Comment by MingcongBai** [comment]
Still seeing this issue currently.

**Comment by MingcongBai** [comment]
Please re-open if reproduced.
