### ISSUE TITLE
synaptics, apt: segfault when searching

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#124]
sijie [ ~ ] ! LC_ALL=C apt search pcsc
Sorting... Done
段错误 (核心已转储) 50%

sijie [ ~ ] ! synaptic
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
段错误 (核心已转储)

sijie [ ~ ] $ dpkg -s apt
Package: apt
Status: install ok installed
Section: admin
Installed-Size: 7740
Maintainer: Jeff Bai <jeffbai@aosc.xyz>
Architecture: amd64
Version: 1:1.1.3

sijie [ ~ ] ! dpkg -s synaptic
Package: synaptic
Status: install ok installed
Section: admin
Installed-Size: 8224
Maintainer: Jeff Bai <jeffbai@aosc.xyz>
Architecture: amd64
Version: 0.82

**Comment by butangmucat** [comment]
这是老问题了吧

**Comment by MingcongBai** [comment]
Old persisting issue... My current suspicion would be somewhere in the early `b*` package having ambiguous data. You can try scroll through the package list, it should crash when you reach `b*`.

**Comment by MingcongBai** [comment]
Solved. Two "rotten" packages in the basket. A new catalog is available for `apt update`.
