### ISSUE TITLE
xfce4-session-logout: direct logout without power menu

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#125]
Happened again.

No info from coredumpctl.

xsession-errors attached.

[xsession-errors.txt](https://github.com/AOSC-Dev/aosc-os-abbs/files/52659/xsession-errors.txt)

**Comment by MingcongBai** [comment]
Have you ever seen a logout dialog after downgrading?

**Comment by butangmucat** [comment]
yes

**Comment by MingcongBai** [comment]
Okay, please go ahead.

**Comment by butangmucat** [comment]
error log attached

**Comment by MingcongBai** [comment]
No particular related error here.

**Comment by butangmucat** [comment]
I am not sure if it is a function from upstream, but it seemed to be caused by unchecking the "Prompt on logout" option.

![xfce4-settings-manager](http://imgur.com/6ZDqBzll.png)

**Comment by MingcongBai** [comment]
That's good then, please close this.
