### ISSUE TITLE
pyyaml: security update to 5.1

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1252]
http://www.openwall.com/lists/oss-security/2018/06/27/1

- [x] Intel 64 / AMD64
- [x] Armv8-A 64-bit (AArch64)
- [x] Armv7-A
- [x] PowerPC 64-bit
- [x] PowerPC 32-bit

**Comment by MingcongBai** [comment]
Too much of a bump, marking `to-staging`.

**Comment by MingcongBai** [comment]
This version has actually been removed by upstream.

**Comment by MingcongBai** [comment]
No fix version has been released yet.

**Comment by MingcongBai** [comment]
Still no release.

**Comment by MingcongBai** [comment]
Still no fix.

**Comment by l2dy** [comment]
"Fixed" in 5.1. See https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation.

**Comment by KexyBiscuit** [comment]
~- [x] Intel 64 / AMD64~
~- [x] Armv8-A 64-bit (AArch64)~
~- [x] Armv7-A~
~- [x] PowerPC 64-bit~
~- [x] PowerPC 32-bit~
~- [ ] RISC-V~

Moved to the issue.

**Comment by MingcongBai** [comment]
Throwing `riscv64` back to experimental state, it stalled - thus we are done here for now. Closing.

**Comment by l2dy** [comment]
Use AOSA-2019-0157.
