### ISSUE TITLE
gdm: hang after logout

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#126]
Session: GNOME Flashback

GDM hangs after using the logout function. Blank screen, frozen mouse and keyboard.

Package: gdm
Status: install ok installed
Section: gnome
Installed-Size: 7452
Maintainer: Jeff Bai <jeffbai@aosc.xyz>
Architecture: amd64
Version: 3.18.2

**Comment by MingcongBai** [comment]
I can reproduce this with a `gnome-shell` session. Seems like GDM will lock the screen, resulting in a black screen by default, by design, when hitting the keyboard, GDM should show a lock screen with time and date on it. However, it seems like the screen fails to re-initialize.

I can work around this by closing the lid (put it into sleep), and open the lid again.

I will look into this.

**Comment by MingcongBai** [comment]
A bug report in Fedora bugzilla can be referred to.

https://bugzilla.redhat.com/show_bug.cgi?id=1272737

**Comment by MingcongBai** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1272737#c25

```
I think I figured this out.  cogl will stop doing page flipping and revert to manual drmSetCrtc calls if the drmModePageFlip call fails. Doing that, will cause tearing but provides a compatibility path for drivers that don't support page flipping (mga for instance).  drmModePageFlip can fail under normal conditions, though, if it's called when using a non-render-node (as is the case for us at the moment) and the VT is inactive.  In this case, it will return an error code of EACCES.  We try to detect this space case and leave page flipping enabled, so the user doesn't start seeing tearing after one of these "expected" failures.  The code isn't quite right though.  It not only ignores the error, but it proceeds as if the page flip request succeeded, and sits and waits for the flip event to come back. Since the page flip request didn't succeed the event never comes back.

Will build a fix.
```

And hence reported to be effective.

**Comment by MingcongBai** [comment]
http://pkgs.fedoraproject.org/cgit/cogl.git/tree/fix-black-login-screen.patch

Pending patch.

**Comment by MingcongBai** [comment]
With investigation above, this should be a `cogl` instead. I am building a fix now.

**Comment by MingcongBai** [comment]
The commit mentioned above is referring to the future `cogl` version `1.22.0-1` update that would be available in just hours. This, from my own testing, fixes the issue.

If you can confirm this, please close this issue when available.

**Comment by butangmucat** [comment]
Lid doesn't work for me.

**Comment by MingcongBai** [comment]
Please check for a `cogl` update.

**Comment by butangmucat** [comment]
Package?

**Comment by MingcongBai** [comment]
Yes, it is a package update.

**Comment by butangmucat** [comment]
now?

**Comment by MingcongBai** [comment]
It should be available as an update now.

**Comment by butangmucat** [comment]
Fixed.

**Comment by MingcongBai** [comment]
Good to hear.
