### ISSUE TITLE
netease-cloud-music: (virtually) all package files owned by 1000:1000

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#1265]
A rebuild is in order to fix the permission errors, and to prevent further damage.

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/0f64607348a3caa5e510038277abcda3c19943af. 

@l2dy Please assign an AOSA for this one.

**Comment by MingcongBai** [comment]
Note to self: Class 2 and 3.

**Comment by l2dy** [comment]
Use AOSA-2018-0302.
