### ISSUE TITLE
alsa: workaround needed for sound to work on ThinkPad L450

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#127]
By default, there is no output from the integrated ACL3232 HD Audio chip, and a workaround in /etc/modprobe.d is needed (alsactl init does not work). This does not happen on Arch Linux with both official and ck1 kernels.

The workaround is described in https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture#Set_the_default_sound_card

**Comment by MingcongBai** [comment]
Can you try removing the workaround, reboot, and `alsactl init` as root or `sudo` instead?

**Comment by butangmucat** [comment]
tried not working

**Comment by MingcongBai** [comment]
Sorry. Forgot to mention that 9791cd7a53dfa1dab3ef5b70096648dec52867e1 solves this issue. Closing.
