### ISSUE TITLE
apt-key: broken after gpg update

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#128]
root [ sijie ] ! apt-get update --allow-unauthenticated
忽略:1 https://repo.aosc.io/os3-next/os3-dpkg  InRelease
命中:2 https://repo.aosc.io/os3-next/os3-dpkg  Release
获取:3 https://repo.aosc.io/os3-next/os3-dpkg  Release.gpg [473 B]
忽略:3 https://repo.aosc.io/os3-next/os3-dpkg  Release.gpg
下载 473 B，耗时 7秒 (64 B/s) 
正在读取软件包列表... 完成
W: GPG 错误：https://repo.aosc.io/os3-next/os3-dpkg  Release: 运行 apt-key 时发生未知错误
W: The repository 'https://repo.aosc.io/os3-next/os3-dpkg  Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root [ sijie ] # apt-key list
Error: gnupg or gnupg2 do not seem to be installed,
Error: but apt-key requires gnupg or gnupg2 for this operation.

root [ sijie ] ! dpkg -s gnupg
Package: gnupg
Status: install ok installed
Section: libs
Installed-Size: 9960
Maintainer: Jeff Bai <jeffbaichina@members.fsf.org>
Architecture: amd64
Version: 2.1.9
Replaces: gnupg+1, dirmngr
Provides: gnupg+1, dirmngr

root [ sijie ] # dpkg -s apt
Package: apt
Status: install ok installed
Section: admin
Installed-Size: 7740
Maintainer: Jeff Bai <jeffbai@aosc.xyz>
Architecture: amd64
Version: 1:1.1.3

**Comment by MingcongBai** [comment]
Try install `which` and it should solve the issue.

**Comment by Arthur2e5** [comment]
我该看看 apt-key 的源码吗

**Comment by MingcongBai** [comment]
> 我该看看 apt-key 的源码吗

Please do, using `which` to see if `gnupg` is installed is nothing more than silly.

**Comment by Arthur2e5** [comment]
```
    if [ -n "$GPG_EXE" ] && which "$GPG_EXE" >/dev/null 2>&1; then
	true
    elif which gpg >/dev/null 2>&1; then
	GPG_EXE="gpg"
    elif which gpg2 >/dev/null 2>&1; then
	GPG_EXE="gpg2"
    else
	echo >&2 "Error: gnupg or gnupg2 do not seem to be installed,"
	echo >&2 "Error: but apt-key requires gnupg or gnupg2 for this operation."
	echo >&2
	exit 255
    fi
```
They should use `type`.

**Comment by Arthur2e5** [comment]
This is a debian bug. On my Ubuntu system, `apt` doesn't claim to depend on `debianutils` -- running `apt remove debianutils` doesn't remove apt.
