### ISSUE TITLE
telegram-desktop: missing dependency

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#129]
root [ sijie ] # ldd /usr/bin/telegram-desktop | grep "not found"
	libnuma.so.1 => not found

Package: telegram-desktop
Status: install ok installed
Section: net
Installed-Size: 30316
Maintainer: Jeff Bai <jeffbai@aosc.xyz>
Architecture: amd64
Version: 0.9.13-1
Provides: telegram, tdesktop
Depends: desktop-file-utils (>= 0.22-2), ffmpeg (>= 2.8.2-1), icu (>= 53.1-3), jasper (>= 1.900.1-5), libexif (>= 0.6.21-2), libinput (>= 1.1.1), libmng (>= 2.0.3-0), libproxy (>= 0.4.11-1), libwebp (>= 0.4.3-0), libxkbcommon (>= 0.5.0-1), mtdev (>= 1.1.5-1), openal-soft (>= 1.16.0-3)

**Comment by MingcongBai** [comment]
`ffmpeg` is missing `numactl` as its dependency. Building a fix now.
