### ISSUE TITLE
gnupg: please enable GUI pinentry programs (gtk2, qt4)

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#130]
As of gnugp 2.1.9, only CLI pinentry programs are enabled, please add GUI versions for the sake of convenience in an X session.

**Comment by MingcongBai** [comment]
https://github.com/AOSC-Dev/aosc-os-abbs/commit/252a3f8eeb059b513b2a64ccf37003b03ed6160e

I am closing this my friend.

**Comment by butangmucat** [comment]
？

**Comment by MingcongBai** [comment]
I have enabled such support in the commit provided, and it is in repo as an update now.

**Comment by butangmucat** [comment]
didnt receive such update

**Comment by MingcongBai** [comment]
Then please wait for an hour or two for it to refresh.

**Comment by butangmucat** [comment]
repo.aosc.io

**Comment by MingcongBai** [comment]
http://repo.anthonos.org/os3-next/os3-dpkg/p/pinentry_0.9.6-0_amd64.deb
