### ISSUE TITLE
gnome-control-center: core dump after hitting the top left back button in input sources panel

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#131]
How to reproduce:

gnome-control-center -> languages -> back

output: [1]    2358 segmentation fault (core dumped)  gnome-control-center

Package: gnome-control-center
Status: install ok installed
Section: gnome
Installed-Size: 16580
Maintainer: Jeff Bai <jeffbai@aosc.xyz>
Architecture: amd64
Version: 3.18.2

**Comment by Arthur2e5** [comment]
I believe we should turn off ABSTRIP for our beta…

**Comment by MingcongBai** [comment]
I can always produce debug builds when needed.

**Comment by MingcongBai** [comment]
This issue, however, is most like the past Xfce issue that xfce4-session would crash due to a gtk_widget call. This is the same way.

**Comment by Arthur2e5** [comment]
Crashes somewhere near https://github.com/GNOME/gtk/blob/gtk-3-18/gtk/gtkwidget.c#L4630-L4657.

**Comment by MingcongBai** [comment]
Quite a good location... bad for debugging.

**Comment by Arthur2e5** [comment]
Not that bad, at least we know it crashed before calling g_object_run_dispose……

**Comment by MingcongBai** [comment]
Very true...

**Comment by MingcongBai** [comment]
As described in the commit msg, this bug is actually introduced by the `--disable-debug` configuration flag, which ended up inhibiting GTK+ applications from returning "Critical" outputs, which leads to segmentation fault (as there is no fallback for a warning).

I am really happy to have finally get this one taken care of.

**Comment by MingcongBai** [comment]
And yes, as proven many times before, not a linkage, nor a compiler/linker flag related issue!
