### ISSUE TITLE
brave-browser: security update to ^0.23.77

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1317]
https://github.com/brave/browser-laptop/releases/tag/v0.23.77dev

> Upgraded to Chromium 68.0.3440.84.

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/8bb296f12acb31b9889a0bd011be8a040aafecdb. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0357.
