### ISSUE TITLE
thunderbird: security update to 60.0

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1323]
https://www.thunderbird.net/en-US/thunderbird/60.0/releasenotes/
https://www.mozilla.org/en-US/security/advisories/mfsa2018-19/

**Comment by MingcongBai** [comment]
Fixing in stable, even if updating to a new major version - in accordance to the [Exception List](https://wiki.aosc.io/developers/aosc-os/cycle-exceptions).

**Comment by MingcongBai** [comment]
Keeping this issue open.

- The new package has been built for AMD64 and was uploaded two days ago.
- All other architectures failed to build Thunderbird 60. Will investigate further in the coming week.

Marking `investigating`.

**Comment by l2dy** [comment]
@MingcongBai AOSA now or later?

**Comment by MingcongBai** [comment]
Later. I'm yet to be able to produce a build on ARM* and PPC*BE.

**Comment by l2dy** [comment]
> Later. I'm yet to be able to produce a build on ARM* and PPC*BE.

Any progress?
