### ISSUE TITLE
build-essential: a new meta should be introduced

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#133]
It is more clear at this point that most new AOSC OS users would not realize of a proper way to set up a usable development environment.

A classic example is the absence of `linux+api` with a installed `gcc`, and the user will still not be able to build anything with it (practically).

Therefore, a `build-essential` package (or of a similar name) should be provided, containing all runtime, and development packages provided in the Core.

**Comment by liushuyu** [comment]
Is this issue still alive? 
I think it will be better if `make` is also included...

**Comment by MingcongBai** [comment]
Bad memory.
