### ISSUE TITLE
Please update to uriparser 0.8.6

### ISSUE THREAD

**Issue by hartwork** [AOSC-Dev/aosc-os-abbs#1340]
Hi!

Just a quick heads up that [uriparser 0.8.6](https://github.com/uriparser/uriparser/releases/tag/uriparser-0.8.6) with bugfixes has been released.

Thanks for updating!

**Comment by MingcongBai** [comment]
Updated with https://github.com/AOSC-Dev/aosc-os-abbs/commit/99ce1b82933397794f51dd24c1f1d14c35999260. Thanks for the heads-up.

**Comment by hartwork** [comment]
Thank you!
