### ISSUE TITLE
packagekit: "'" (&quot;) in filename can result in failure of query

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#135]
As a reference, the original bug report can be found here.

https://bugzilla.gnome.org/show_bug.cgi?id=759513

And the proposed patch by the upstream can be found here.

https://github.com/hughsie/PackageKit/commit/09584a45684810ea15c4127be70da277ad8afeb5.patch

Known subjects that are affected by this issue: Civilization V for Linux.

**Comment by MingcongBai** [comment]
@Icenowy Calling again for confirmation on the fix.

**Comment by MingcongBai** [comment]
Last call on confirmation, I will close this in three days on notice.

**Comment by liushuyu** [comment]
>Last call on confirmation, I will close this in three days on notice.

Okay, and three days pasted...
