### ISSUE TITLE
graphicsmagick, imagemagick: Disable PS, EPS, PDF, and XPS coders

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1352]
Cross-References: openSUSE-SU-2018:2516-1, USN-3785-1

https://www.kb.cert.org/vuls/id/332928

Architectural progress
--------------------------------

- [x] AMD64 (`amd64`)
- [x] AArch64 (`arm64`)
- [x] ARMv7 (`armel`)
- [x] PowerPC 64-bit BE (`ppc64`)
- [x] PowerPC 32-bit BE (`powerpc`)

**Comment by MingcongBai** [comment]
Seems like a series of patches are made available for GhostScript and GhostPDL.

**Comment by l2dy** [comment]
> Seems like a series of patches are made available for GhostScript and GhostPDL.

That would be a different issue. This issue is about hardening GraphicsMagick and ImageMagick.

**Comment by MingcongBai** [comment]
Action plan:

- Disabling insecure coders from GraphicsMagick and ImageMagick.
- Patching GhostScript and GhostPDL with the patches supplied in the original documentation.

AOSA:

- Please assign one for each package affected.

**Comment by MingcongBai** [comment]
Second point above applies to #1354

**Comment by MingcongBai** [comment]
Fixed with:

- ImageMagick: https://github.com/AOSC-Dev/aosc-os-abbs/commit/f9c7759277b38ca485b666c9c0caa87ab1ffbb1b
- GraphicsMagick: https://github.com/AOSC-Dev/aosc-os-abbs/commit/e1bb07d3401d7e560dee6adcd1f06d4a3e88b135

**Comment by l2dy** [comment]
Use AOSA-2018-0385 for ImageMagick.
Use AOSA-2018-0386 for GraphicsMagick.

**Comment by l2dy** [comment]
Ubuntu Security Notice USN-3785-1
October 04, 2018

```
Due to a large number of issues discovered in GhostScript that prevent
it from being used by ImageMagick safely, this update includes a
default policy change that disables support for the Postscript and
PDF formats in ImageMagick. This policy can be overridden if necessary
by using an alternate ImageMagick policy configuration.
```
