### ISSUE TITLE
RPM package rebuild needed for packages w/ RPMEXTRAPROVIDE / PKGPROV_RPM

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#136]
See AOSC-Dev/autobuild3#78. We need someone to run `grep -r`.

**Comment by Icenowy** [comment]
./extra-python/python-3/autobuild/defines:RPMEXTRAPROVIDE="/sbin/python3 /usr/sbin/python3 /bin/python3"
./extra-ocaml/ocaml/autobuild/defines:RPMEXTRAPROVIDE="ocaml(runtime) = 4.02.3"
./base-utils/gawk/autobuild/defines:RPMEXTRAPROVIDE="/usr/bin/awk /usr/sbin/awk /bin/awk /sbin/awk /usr/bin/gawk /usr/sbin/gawk /bin/gawk /sbin/gawk"
./base-utils/coreutils/autobuild/defines:RPMEXTRAPROVIDE="/bin/env /sbin/env"
./extra-gnome/gjs/autobuild/defines:RPMEXTRAPROVIDE="/bin/gjs /sbin/gjs /usr/sbin/gjs"
./extra-admin/upower/autobuild/defines:RPMEXTRAPROVIDE="libupower-glib.so.2()(64bit)"
./base-python/python-2/autobuild/defines:RPMEXTRAPROVIDE="/sbin/python /bin/python /usr/bin/python /usr/sbin/python /sbin/python2 /bin/python2 /usr/bin/python2 /usr/sbin/python2"
./extra-libs/boost/autobuild/defines:RPMEXTRAPROVIDE="$(cat autobuild/extra)"
./extra-libs/libical/autobuild/defines:RPMEXTRAPROVIDE="libical.so.0()(64bit) libicalss.so.0()(64bit) libicalvcal.so.0()(64bit)"

and aosc-os-core

./core-libs/glibc/autobuild/defines:RPMEXTRAPROVIDE="rtld(GNU_HASH)"
./core-shells/bash/autobuild/defines:RPMEXTRAPROVIDE="/bin/sh /bin/bash /sbin/bash"
./core-perl/perl/autobuild/defines:RPMEXTRAPROVIDE="perl(abbrev.pl) /sbin/perl /usr/sbin/perl /bin/perl"
./core-perl/perl/autobuild/defines:	RPMEXTRAPROVIDE+=",$1"

**Comment by MingcongBai** [comment]
Okay, thanks a lot.

**Comment by Arthur2e5** [comment]
Hold on. I believe this thing is still broken.

A brain run on `RPMEXTRAPROVIDE="ocaml(runtime) = 4.02.3"` gives the following result:

1. `rpmopttag Provides $RPMEXTRAPROVIDE $PKGPROV $PKGPROV_RPM`
2. `VER_NONE=${VER_NONE-1} pm_depcom 'ocaml(runtime)' '=' '4.02.3'`

BOOM.

**Comment by Icenowy** [comment]
OK, you'd fix it.

To be honest, I cannotnread your code yet.

- 发送自我的Sony Xperia™智能手机

---- Mingye Wang编写 ----

Hold on. I believe this thing is still broken.

A brain run on `RPMEXTRAPROVIDE="ocaml(runtime) = 4.02.3"` gives the following result:

1. `rpmopttag Provides $RPMEXTRAPROVIDE $PKGPROV $PKGPROV_RPM`
2. `VER_NONE=${VER_NONE-1} pm_depcom 'ocaml(runtime)' '=' '4.02.3'`

BOOM.

---

**Comment by Arthur2e5** [comment]
This is YOUR fault since you mixed up data structures.

I can write a fix, but it is too hacky. And I don't want to wipe YOUR butt.

**Comment by Icenowy** [comment]
It's your own butt. I just wiped it, although not cleanly

- 发送自我的Sony Xperia™智能手机

---- Mingye Wang编写 ----

This is YOUR fault since you mixed up data structures.

I can write a fix, but it is too hacky. And I don't want to wipe YOUR butt.

---
