### ISSUE TITLE
dbeaver This installation kit. It's damaged

### ISSUE THREAD

**Issue by zhenruyan** [AOSC-Dev/aosc-os-abbs#1365]
Bug description
-----------------------

*Bug description here...*

Reproducing steps
---------------------------

*List steps to reproduce the issue.*

Update channel(s)
--------------------------

*Stable, Testing, or Explosive? Any enabled Overlay(s)?*

Package and version
------------------------------

*Execute `dpkg -s $PKG` and paste output below, where `$PKG` is the affected package. If uncertain, leave this section blank.*

**Comment by MingcongBai** [comment]
First of all, the package is just fine; secondly... what you are posting is a bug template, wonder why.

Closing as invalid.
