### ISSUE TITLE
OpenJDK postinst will fail on non-amd64 systems.

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#137]
I don't know why you are making some neutral things amd64. Well, I am not going to say fsck again, but..

Here is the story.

The cross-arch `extra-java/openjdk/autobuild/postinst` specifies a `mkcacerts`, but it won't work since there is only a `extra-java/openjdk/autobuild/amd64/overrides/usr/bin/mkcacerts`. **amd64**.

**Comment by Arthur2e5** [comment]
And apparently the bloody BLFS guy cannot tell bashism from `/bin/sh`. Does anyone know how to write patches to BLFS people?

**Comment by MingcongBai** [comment]
They have a mailing list for the purpose, I am sorry about the amd64
separation, that was plainly a careless mistake.
2015年12月17日 下午9:53，"Mingye Wang" <notifications@github.com>写道：

**Comment by MingcongBai** [comment]
This will be fixed in the next commit. However... An idea about `$AVAILABLEARCH` just came across my mind...

**Comment by Arthur2e5** [comment]
In the current ab way, just direct it onto a build that says `false`.
