### ISSUE TITLE
latrace: libltaudit.so has undefined symbol

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#1389]
Bug description & Reproducing steps
-----------------------
```
lion@Lion-Laptop [ Debug ] $ latrace /bin/true
ERROR: ld.so: object '/usr/lib/libltaudit.so.0.5.11' cannot be loaded as audit interface: undefined symbol: lt_args_wrap; ignored.

/bin/true finished - exited, status=0
```
Package and version
------------------------------
latrace 0.5.11 amd64

**Comment by MingcongBai** [comment]
Note, this is a package introduced with current `Explosive`.

**Comment by LionNatsu** [comment]
Amazing, we didn't even have latrace!

**Comment by LionNatsu** [comment]
And it's in `stable` bruh

**Comment by MingcongBai** [comment]
Dropped in an upcoming PR. Closing.

If anyone cares to revive the project, it could be introduced again.
