### ISSUE TITLE
gnome-shell, gnome-tweak-tool: change in icon theme doesn't reflect

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#139]
How to reproduce:
Install an icon theme i.e. numix-circle;
Try to change it in gnome-tweak-tool;
gnome-tweak-tool doesn't complain but the icon theme in gnome-shell is still the default 'gnome' theme (fails silently).

**Comment by MingcongBai** [comment]
Try running `gtk-update-icon-cache -t -f /usr/share/icons/${ICONTHEME}` as root, where `${ICONTHEME}` is the directory containing the icon theme.

This can be a packaging issue.

**Comment by MingcongBai** [comment]
Mysteriously fixed by d84d40047f3365c2a2c8723fc16049cc7a759f81, closing this (as I have tested it in multiple cases).
