### ISSUE TITLE
vlc: GUI failed to start

### ISSUE THREAD

**Issue by lmy441900** [AOSC-Dev/aosc-os-abbs#14]
![2015-07-15 15-46-44](https://cloud.githubusercontent.com/assets/4285573/8693392/5fd0b9be-2b09-11e5-8d2f-54ce7eda32da.png)

**Comment by MingcongBai** [comment]
`vlc -v` suggests that `libQt5Widgets.so.5`, `libgnomevfs-2.so.0`, `libvncclient.so.0` are missing.

Corresponding, `qt-5`, `libvnserver`, and `gnome-vfs`. Need rebuild.

**Comment by MingcongBai** [comment]
Fixed as of 9577c34.
