### ISSUE TITLE
pakreq: lld (git)

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#142]
lld is LLVM's NIH linker: http://lld.llvm.org/.

Yes, they seem to enjoy their assembler and here comes their WIP linker.

**Comment by MingcongBai** [comment]
Why don't we just wait for a tag... It will happen some time in the future, won't it?

**Comment by liushuyu** [comment]
> Why don't we just wait for a tag... It will happen some time in the future, won't it?
But I am afraid this wouldn't happen in the near future... They haven't had a tag for around 2 years(?) ...

**Comment by MingcongBai** [comment]
> But I am afraid this wouldn't happen in the near future... They haven't had a tag for around 2 years(?) ...

What really makes it difficult is that this has to be built in a LLVM source tree, making it possible to be un-build-able across LLVM version bumps...

**Comment by liushuyu** [comment]
Looking at http://lld.llvm.org/open_projects.html
I am afraid that lld is just yet another experiment... As there are so many un-implement features... 🌚
It's just a playground for now.

**Comment by Arthur2e5** [comment]
Perhaps you should go and ask Bai what clang-as means to us.

**Comment by liushuyu** [comment]
>What really makes it difficult is that this has to be built in a LLVM source tree, making it possible to be un-build-able across LLVM version bumps...

Maybe we can re-build this each time LLVM bumps its version... As @Arthur2e5 said it is important to introduce this thing

**Comment by Arthur2e5** [comment]
YOU GOT ME WRONG.

LOOK AT AOSC-Dev/autobuild3 : arch/*

**Comment by liushuyu** [comment]
All right my dear A2...😃

**Comment by MingcongBai** [comment]
Time to get this built.
