### ISSUE TITLE
Please update uriparser to 0.9.0, includes security fixes

### ISSUE THREAD

**Issue by hartwork** [AOSC-Dev/aosc-os-abbs#1428]
Hi!

Just a quick heads up that [uriparser 0.9.0](https://github.com/uriparser/uriparser/releases/tag/uriparser-0.9.0) with security fixes has been released.

Thanks for updating!

**Comment by MingcongBai** [comment]
@l2dy Could you please open up an issue later with proper security update information?

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/453594375f84c9e366766e2129d85f7e44e47b4c. Thanks for the heads up! @hartwork

**Comment by hartwork** [comment]
Thank you!
