### ISSUE TITLE
sqlmap: requset new package

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#143]
Home Page: http://sqlmap.org/
GitHub Repo: https://github.com/sqlmapproject/sqlmap

**Comment by liushuyu** [comment]
Yes, I will do that **if I have time**
😃

**Comment by LionNatsu** [comment]
sqlmap 1.0 has been released.

**Comment by MingcongBai** [comment]
I will package this ASAP.
