### ISSUE TITLE
openssl: any plans for 1.1.1?

### ISSUE THREAD

**Issue by GreaterFire** [AOSC-Dev/aosc-os-abbs#1431]
OpenSSL 1.1.1 is a LTS version and it starts to support TLS 1.3 with no or little ABI compatibility issue. A very nice feature to have in AOSC OS.

**Comment by MingcongBai** [comment]
We do plan on upgrading to OpenSSL 1.1 in the coming cycle, along with GCC ABI updates. Thanks for the suggestion.

**Comment by l2dy** [comment]
Related #1444.

**Comment by MingcongBai** [comment]
We are currently working on it. Rebuilds pending since https://github.com/AOSC-Dev/aosc-os-abbs/commit/b5d715e7fcfb1a958b2597ca3eecd440bd640cb7.

**Comment by MingcongBai** [comment]
However I do want to point out...

```
... little ABI compatibility issue.
```

Let's see...

```
root@explosive-40001 [ ~ ] # wget
wget: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

That would be ~280 packages pending for rebuild.

**Comment by MingcongBai** [comment]
This is actually ready on Testing now. I will close this once we merge.

**Comment by MingcongBai** [comment]
As we have released the Winter cycle updates [yesterday](https://aosc.io/news/621-weekly-community-report-issue-28,-2019) with OpenSSL 1.1, this issue can now be closed.

For the record, OpenSSL 1.1 was introduced by 4c228bbf04e3b9141dfd8b94d3b82e0e8cd12c7c.
