### ISSUE TITLE
freeimage: spec syntax error

### ISSUE THREAD

**Issue by gumblex** [AOSC-Dev/aosc-os-abbs#1434]
https://github.com/AOSC-Dev/aosc-os-abbs/blob/explosive/extra-libs/freeimage/spec#L2

**Comment by MingcongBai** [comment]
Also found in `Stable`, will fix it there and backport.

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/5dc8aee8174a6c28a2d188f5a623b8a0a7a959da. Closing.

**Comment by gumblex** [comment]
Please merge it back to explosive.
