### ISSUE TITLE
lighttpd: security update to 1.4.51

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1453]
**CVE IDs:** N/A

**Other security advisory IDs:** MGASA-2018-0430

**Descriptions:**
https://www.lighttpd.net/2018/10/14/1.4.51/
> [core,security] process headers after combining folded headers

**Architectural progress:**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] ARMv7 `armel`
- [x] PowerPC 64-bit BE `ppc64`

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/6741026925bc7ab02df0bf2d2aaf7ce3dd78a0a5. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0472.
