### ISSUE TITLE
gdal: security update to 2.3.2

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1479]
**CVE IDs:** N/A

**Other security advisory IDs:** MGASA-2018-0451

**Descriptions:**
A flaw was found in gdal up to version 2.3.0. A Heap-buffer-overflow in
GTiffOddBitsBand::IReadBlock.

A flaw was found in gdal. A Heap-buffer-overflow in
NITFRasterBand::Unpack.

A flaw was found in gdal up to version 2.3.0. An Index-out-of-bounds in
CPLErrorSetState.

**Architectural progress:**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] ARMv7 `armel`

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/b79e1efabec330978fb7a96f1e71d5ed7beda3f1. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0488.
