### ISSUE TITLE
Package Request : Playonlinux

### ISSUE THREAD

**Issue by RedL0tus** [AOSC-Dev/aosc-os-abbs#151]
Playonlinux:
It's a manager of Wine (Maybe).
Home page:https://www.playonlinux.com/
GitHub: https://github.com/PlayOnLinux

**Comment by liushuyu** [comment]
For Playonlinux : Most likely this can be achieved
For Debootstrap: I'm afraid that this one will be in far future...

**Comment by liushuyu** [comment]
But if we simplify the problem and if I am not mistaken, you will find Debootstrap is a kind of downloader and chroot ...

I suggest you spilt this issue into two separate issues. One package request for Playonlinux
Another one call for discussion that wether a Debootstrap like tool should be built... (As Always Overuse Shell Community, I can guarantee that this is not difficult to invent (?) one in Bash)

**Comment by RedL0tus** [comment]
OK

**Comment by MingcongBai** [comment]
Well, `playonlinux` is in the repo. But needs an update.

**Comment by MingcongBai** [comment]
Closing this as a new issue is opened for a *bootstrap tool.

**Comment by RedL0tus** [comment]
Already opened a "*bootstrap" issue.

**Comment by liushuyu** [comment]
Yes, and Playonlinux is exist in our repo and it will be easy to just bump the version

**Comment by MingcongBai** [comment]
> Yes, and Playonlinux is exist in our repo and it will be easy to just bump the version

Needed to keep an eye on their release channel, too...
