### ISSUE TITLE
Future Package Refactors on AOSC OS

### ISSUE THREAD

**Issue by jyhi** [AOSC-Dev/aosc-os-abbs#1510]
This is a tracking issue for a list of operations that we want to do in the (near or distant) future and will **break existing packages** of AOSC OS:

- [x] GCC C++ ABI Upgrade, from `gcc4-compatible` to `cxx11`
  - May also need a lint on GCC configuration options
- [x] OpenSSL Upgrade, from ~1.0.1 to ~1.1
- [x] Golang packages re-bootstrap to enable PIE

There are also changes that _may not_ break ABI, but we would like to do it along with the above changes:

- [X] ~~Rust packages re-bootstrap to enable PIC~~ (PIE enabled by default, though depending on target)

If you have more idea, update the list.

**Comment by MingcongBai** [comment]
Just Golang left to do!

**Comment by MingcongBai** [comment]
All done as of Spring 2020.
