### ISSUE TITLE
rpm: security update to 4.14.2.1

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1512]
**CVE IDs:** N/A

**Other security advisory IDs:** N/A

**Descriptions:**
http://rpm.org/wiki/Releases/4.14.2.1
> #### Security fixes
>
> - Fix regression in –setperms, –setugids and –restore (RhBug:1640470) in 4.14.2:
>
>    In case of –setperms, all encountered symlinks would have their target file/directory permissions set to the 0777 of the link itself (so world writable etc but suid/sgid stripped), temporarily or permanently, depending on whether the symlink occurs before or after it’s target in the package file list. When the link occurs before its target, there’s a short window where the target is world writable before having it’s permissions reset to original, making it particularly bad for suid/sgid binaries.
>
>    –setugids was similarly affected with link targets owner/group changing to that of the symlink.
>
>    –restore was affected as it utilizes –setperms and –setugids to do it’s task.
>
>    **Note that this update can not automatically fix possible damage done by using –setperms, –setugids or –restore with rpm 4.14.2, it merely fixes the functionlity itself. Any damage needs to be investigated and fixed manually, such as using –verify and –restore or reinstalling packages.**

**Architectural progress:**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] ARMv7 `armel`
- [x] PowerPC 64-bit BE `ppc64`
- [x] PowerPC 32-bit BE `powerpc`
- [x] RISC-V 64-bit `riscv64`

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/8613c9981dad46434730176a203ed28e029821c2. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0501.
