### ISSUE TITLE
Whether a Debootstrap like tool should be built

### ISSUE THREAD

**Issue by RedL0tus** [AOSC-Dev/aosc-os-abbs#152]
> "debootstrap is a tool which will install a Debian base system into a subdirectory of another, already installed system".  --From the official wiki of Debian

A tool which can install the base system in a easy way.(But I'm **not sure** whether it works with AOSC OS)

Debian Wiki : https://wiki.debian.org/Debootstrap/
Source code:  https://anonscm.debian.org/git/d-i/debootstrap.git

It can be another way to install AOSC OS.

(Maybe you guys can build a tool called "AOSCbootstrap")

**Comment by liushuyu** [comment]
Fixed. Using https://github.com/AOSC-Dev/aoscbootstrap.
