### ISSUE TITLE
kdeconnect: security update to ^1.3.2

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1521]
**CVE IDs:** N/A

**Other security advisory IDs:** MGASA-2018-0473

**Descriptions:**
https://mail.kde.org/pipermail/kde-announce-apps/2018-November/005484.html
> KDE Connect 1.3.2 includes a security fix plus some minor fixes, while
> 1.3.3 just addresses an issue when KDE Connect was linked with the latest
> version of KIO.
> 
> No new features nor new strings, so hopefully the security fix can get into
> every distro.
> 
> Changes since 1.3.1:
> - [Security fix] Don't disable all modern SSH encryption algorithms.
> 
> [...]

**Architectural progress:**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] ARMv7 `armel`
- [x] PowerPC 64-bit BE `ppc64`
- [x] PowerPC 32-bit BE `powerpc`

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/cc6880a94a5fe7a5edb7f8314940f954ca68847d. Closing.

**Comment by l2dy** [comment]
Use AOSA-2019-0051.
