### ISSUE TITLE
PakReq: Azul Zulu Embedded (OpenJDK-Based)

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#154]
This (certified Java SE compliant) JDK gives JIT ability on 32-bit ARM. Perhaps we should figure out the changeset and pack it like all these icedtea JIT VMs.

**Comment by MingcongBai** [comment]
They are usually quite a pain to deal with (packaging), but I am happy to do it per requested. Just a quick question if you may, is this beneficial in anyway to architectures other than ARM?

**Comment by Arthur2e5** [comment]
If you want to binpack them, well, you can get some good commercial-grade certification for free…

**Comment by MingcongBai** [comment]
> If you want to binpack them, well, you can get some good commercial-grade certification for free…

I would not want to do it.

**Comment by Arthur2e5** [comment]
(By saying this I mean the offical binary builds are certified JVM compatible.)

**Comment by MingcongBai** [comment]
> (By saying this I mean the offical binary builds are certified JVM compatible.)

Well our `openjdk` is already not (considering classpath, etc). I am currently having trouble finding its source code.

**Comment by Arthur2e5** [comment]
I guess I gave you a false pakreq. The ARM32 builds are still in Early Access stage.

They are simply calling their builds '100% Open Source OpenJDK builds' (https://www.azul.com/products/open-source-tools/other-azul-open-source-initiatives/), so I guess they are constantly sending patches upstream so they don't need to worry about where to put the source?

**Comment by MingcongBai** [comment]
> so I guess they are constantly sending patches upstream so they don't need to worry about where to put the source?

Very smart of them then.

Would you mind if I close the issue for now? You may open this anytime you wish, when it is actually a valid request for packaging (source provided + confirmed feature).

**Comment by Arthur2e5** [comment]
Sure. Binpacks might be interesting though.
(Yeah, and on Windows I use their builds instead of Oracle JVM)

**Comment by MingcongBai** [comment]
> Sure. Binpacks might be interesting though.

Will be listed into my TODO (probably due by this weekend). Closing this as invalid request.

**Comment by Arthur2e5** [comment]
Just one more thing. Will you do some investigation on OpenJDK's default crypto key length policy?
http://www.azul.com/products/zulu/zulu-cryptography-extension-kit/
