### ISSUE TITLE
nodejs: package nodejs returns to the current branch and add package nodejs-lts to use the LTS branch

### ISSUE THREAD

**Issue by Garfield550** [AOSC-Dev/aosc-os-abbs#1552]
// Sorry, press ENTER too fast.

I know why we drop back nodejs to LTS branch, but my advice is to create a new package using the LTS branch, and the current nodejs package uses the latest release version.

**Comment by MingcongBai** [comment]
I'm sorry but I would have to reject this request. This was a voted resolution during AOSCC 2018 to ensure that Node.js could receive security updates without requiring major version updates (this will be useful for our Stable branch, and Testing branch during the freezing month).

Original bulletin:

```
关于分支定义

— 不稳定分支名称为 Explosive
— Explosive 不接受不稳定和测试版本/分支，不接受季度时间限制（但是无明显分支界定的不能打任何 beta/rc，不接受 GNOME 3.29 这类明显的不稳定分支，Node 这类明显需要保障分支内安全更新的在 LTS 分支之间跳）
— Testing 在季度周期（假设两个月更新，一个月测试）内引入新的 LTS 和稳定分支，无明显分支的也引入，但是要在第二个月结尾截止，然后一个月测试
— Stable 只在三个月内提供当前 LTS 分支和稳定分支内的 patch release 更新（比如 GNOME 3.28.1 到 3.28.3）；Stable 更新时，除非可以确定是 patch release（需要利用文档记录已知规则和例子），否则不允许更新
```

**Comment by Garfield550** [comment]
Okey it's fine.
