### ISSUE TITLE
openmpi: update to 4.0.0 + fix summary typo

### ISSUE THREAD

**Issue by luzpaz** [AOSC-Dev/aosc-os-abbs#1556]
Bug description
-----------------------

Please update to latest [stable](https://www.mail-archive.com/announce@lists.open-mpi.org/msg00119.html) 4.0.0

**Also:**  
https://github.com/AOSC-Dev/aosc-os-abbs/blob/explosive/extra-scientific/openmpi/autobuild/defines#L5 should be 
`PKGDES="High performance message passing library"` 
instead of  
`PKGDES="High performance massage passing library"`

**Comment by MingcongBai** [comment]
Addressed with #2882. Closing.
