### ISSUE TITLE
sqlite: feature request

### ISSUE THREAD

**Issue by gumblex** [AOSC-Dev/aosc-os-abbs#1561]
Bug description
-----------------------

* --enable-update-limit --enable-geopoly --enable-session

* add `dbhash` and `lemon` binaries

Reproducing steps
---------------------------

N/A

Update channel(s)
--------------------------

explosive

Package and version
------------------------------

enable them in 3.26.0

**Comment by eatradish** [comment]
Now sqlite 3.27.1 in testing, close this issue
