### ISSUE TITLE
palemoon, fossamail: package

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#159]
@MingcongBai Just to remind you to package them and send them to upstream for authorization.

**Comment by MingcongBai** [comment]
http://forum.palemoon.org/viewtopic.php?f=40&t=11393
PaleMoon submitted for 3rd party build audition.

**Comment by MingcongBai** [comment]
Pale Moon is now approved as endorsed contributed build.

https://www.palemoon.org/contributed-builds.shtml
