### ISSUE TITLE
Firefox: bugs

### ISSUE THREAD

**Issue by bobcao3** [AOSC-Dev/aosc-os-abbs#16]
When starting firefox, input w or press Ctrl+A causing core dump of firefox.
When resuming from suspend, it could be disappeared

**Comment by MingcongBai** [comment]
Could be fixed with the latest `gtk-2` update, can you check on how it works now?

**Comment by bobcao3** [comment]
It's still have problems, switching windows could cause it terminated now.

**Comment by MingcongBai** [comment]
@Icenowy reports that this issue shows on his machine, too.

**Comment by MingcongBai** [comment]
Cannot reproduce anyways. Closing. Please re-open if found again, attach with stack trace.
