### ISSUE TITLE
gstreamer-1-0 update to 1.15.1

### ISSUE THREAD

**Issue by luzpaz** [AOSC-Dev/aosc-os-abbs#1605]
New version released: 
https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.15.1.tar.xz  
https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.15.1.tar.xz.asc  
https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.15.1.tar.xz.sha256sum

**Comment by MingcongBai** [comment]
We do not accept unstable versions in *any* of our branches. GStreamer 1.15 represents the development progress of 1.16.
