### ISSUE TITLE
Update ccache to 3.6

### ISSUE THREAD

**Issue by luzpaz** [AOSC-Dev/aosc-os-abbs#1608]
https://www.samba.org/ftp/ccache/ccache-3.6.tar.xz

https://github.com/AOSC-Dev/aosc-os-abbs/tree/testing/extra-devel/ccache
https://packages.aosc.io/packages/ccache

**Comment by eatradish** [comment]
Done. ccache 3.6 in explosive

**Comment by liushuyu** [comment]
Marking as resolved
