### ISSUE TITLE
pakreq: tre, the 'approximate match' regex engine and its agrep impl

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#162]
https://github.com/laurikari/tre

rename agrep &rarr; tre-agrep
alternative tre-agrep &rarr; agrep

**Comment by MingcongBai** [comment]
https://github.com/laurikari/tre/issues/37

@Arthur2e5 Recommended this pending patch.

**Comment by Arthur2e5** [comment]
Regarding the `alloca` part… `alloca` should still be much faster than `malloc`. So on our side, you might want something like..

```C
#ifdef TRE_USE_ALLOCA
      if (sizeof(*tags) * tnfa->num_tags < 16384)
        tags = alloca(sizeof(*tags) * tnfa->num_tags);
      else
#else /* !TRE_USE_ALLOCA */
      tags = xmalloc(sizeof(*tags) * tnfa->num_tags);
#endif /* !TRE_USE_ALLOCA */
```

```C
  if (tags
#ifdef TRE_USE_ALLOCA
      && sizeof(*tags) * tnfa->num_tags < 16384
#endif /* TRE_USE_ALLOCA */
        )
    xfree(tags);
```

**Comment by Arthur2e5** [comment]
Also tre-match-approx.c, tre_tnfa_run_approx().

**Comment by Arthur2e5** [comment]
tre-match-*.c actually.
