### ISSUE TITLE
extra-cmake-modules: Update to 5.54

### ISSUE THREAD

**Issue by luzpaz** [AOSC-Dev/aosc-os-abbs#1622]
https://packages.aosc.io/packages/extra-cmake-modules (notice that the script is erroneously showing that 5.50 is the latest version) 

https://download.kde.org/stable/frameworks/
https://download.kde.org/stable/frameworks/5.54/

**Comment by MingcongBai** [comment]
@gumblex For the note that upstream version does not indicate the right version.

**Comment by MingcongBai** [comment]
Addressed since long ago. Closing.
