### ISSUE TITLE
Many packages export their internal libraries via /etc/ld.so.conf.d/*

### ISSUE THREAD

**Issue by Icenowy** [AOSC-Dev/aosc-os-abbs#1631]
Bug description
-----------------------
A bunch of libraries export their internal-used libraries via paths in /etc/ld.so.conf.

A severe example is julia, which exports some libraries with the same name of packaged library provided by AOSC OS.

Packages
------------------------------

Known packages with unnecessary ld.so.conf:
```
glibc+32
discover
fakeroot # It comes with a bad ld.so.conf which doesn't have any effect at all.
lmms
wine # but it comes with libwine.so which is really intended to be exported
```

Known packages which really export libraries via ld.so.conf:
```
openjdk
openmpi
samba
```

**Comment by MingcongBai** [comment]
Addressed with #2882. Closing.
