### ISSUE TITLE
boost: version bump

### ISSUE THREAD

**Issue by luzpaz** [AOSC-Dev/aosc-os-abbs#1633]
https://www.boost.org/users/history/version_1_69_0.html

https://github.com/AOSC-Dev/aosc-os-abbs/tree/explosive/extra-libs/boost

**Comment by eatradish** [comment]
Done. now boost 1.69.0 in testing

**Comment by luzpaz** [comment]
JFYI, Boost 1.70 has been released: https://www.boost.org/users/history/version_1_70_0.html

**Comment by liushuyu** [comment]
AOSC OS has updated `boost` to 1.75. This can be closed now.
