### ISSUE TITLE
yarn: broken package (Stable)

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/aosc-os-abbs#1654]
Bug description
-----------------------

```
root@saki-stable-11007b [ ~ ] ? dpkg -L yarn
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/yarn
/usr/share/doc/yarn/LICENSE
```

Reproducing steps
---------------------------

apt update
apt install yarn

Update channel(s)
--------------------------

Stable

Package and version
------------------------------
```
root@saki-stable-11007b [ ~ ] # dpkg -s yarn
Package: yarn
Status: install ok installed
Section: devel
Installed-Size: 48
Maintainer: Mingcong Bai <jeffbai@aosc.io>
Architecture: all
Version: 1.9.4-1
Depends: nodejs (>= 2:10.11.0-1)
Description: Fast reliable and secure dependency management
```

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/cdd1cf366f22187ba149bcdbcb1826829961434f. Closing.
