### ISSUE TITLE
mdm: setup utility segfault

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#166]
sijie@sijie-w541 ~ % sudo mdmsetup                                       :(
[1]    3568 segmentation fault  sudo mdmsetup

STFG did not find anything relevant.

**Comment by liushuyu** [comment]
Is it possible to debug mdmsetup?

**Comment by MingcongBai** [comment]
A segfault at `gtk_label_get_label () at /usr/lib/libgtk-x11-2.0.so.0`.

**Comment by MingcongBai** [comment]
https://github.com/linuxmint/mdm/blob/0288d5db43f5b8f2d7c69149bedb629d01d77992/gui/mdmsetup.c#L1146 Call reference.

**Comment by Icenowy** [comment]
seems that our gtk2 is not stable

**Comment by MingcongBai** [comment]
> seems that our gtk2 is not stable

Yes it was... it wasn't able to speak out (no fallback for a warning, therefore error and segmentation fault).
