### ISSUE TITLE
Review needed for 66-google-noto-sans-cjk

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#169]
It appears that we are considering normal Noto CJK fonts as:

* monospace
  * Only true for `Noto Mono CJK`
* serif
  * Wow, sans `sans-`.

:/

**Comment by MingcongBai** [comment]
Check on the newest commit.

**Comment by Arthur2e5** [comment]
Bai said he removed this.
