### ISSUE TITLE
blueman: package error

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#170]
sijie@sijie-w541 ~ % blueman-applet 
Traceback (most recent call last):
  File "/bin/blueman-applet", line 14, in <module>
    from blueman.Constants import *
ImportError: No module named blueman.Constants

see https://github.com/blueman-project/blueman/issues/71

**Comment by MingcongBai** [comment]
Blueman built with Python 3 but shebang shows `env python`. Interesting upstream.

**Comment by Arthur2e5** [comment]
They must be using arch.

**Comment by MingcongBai** [comment]
> They must be using arch.

That would be my guess as well, filing an issue now.

**Comment by MingcongBai** [comment]
Reported as upstream issue. https://github.com/blueman-project/blueman/issues/482

**Comment by misaka4e21** [comment]
This problem appears again with blueman/os-amd64 1:2.0.5.

**Comment by MingcongBai** [comment]
Fixed in `staging`. Closing.
