### ISSUE TITLE
SDDM: failed to start

### ISSUE THREAD

**Issue by RedL0tus** [AOSC-Dev/aosc-os-abbs#1704]
Bug description
-----------------------

SDDM failed to start.
No output on TTY, no log to systemd-journald and `/var/log/sddm.log`

Result of strace: https://pastebin.aosc.io/paste/Zflz-N9TQ76e0v2xIX4Kqw

Reproducing steps
---------------------------

Upgrade to the latest SDDM.

Update channel(s)
--------------------------

testing, no overlay.

Package and version
------------------------------
```
Package: sddm
Status: install ok installed
Section: x11
Installed-Size: 5472
Maintainer: Mingcong Bai <jeffbai@aosc.io>
Architecture: amd64
Version: 1:0.18.0-1
Depends: qt-5 (>= 1:5.11.3+wk5.212.0)
Conffiles:
 /usr/share/sddm/scripts/Xsetup ac3edd2a1c7369bf911a56e12bf38360
 /etc/sddm.conf 7cd19641f3c0491c092fd124b15da977
Description: QML based X11 display manager
```

**Comment by RedL0tus** [comment]
Confirmed that it does work on Shintel graphics.

**Comment by MingcongBai** [comment]
So far I haven't been able to reproduce this issue. Input needed.

**Comment by LionNatsu** [comment]
```
...
openat(AT_FDCWD, "/var/log/sddm.log", O_WRONLY|O_CREAT|O_APPEND|O_CLOEXEC, 0666) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=748, ...}) = 0
fstat(4, {st_mode=S_IFREG|0644, st_size=748, ...}) = 0
lseek(4, 748, SEEK_SET)                 = 748
write(4, "[19:51:46.598] (II) DAEMON: Init"..., 44) = 44
...
clone(child_stack=0x7fdda8ba5ef0, flags=..., ...) = 7140
...
```
There *is* `/var/log/sddm.log`. More important, you should use "strace -f" to trace those new tasks forked by `clone`. Sadly those infomation was lost. Anyways, can you still reproduce it now?

**Comment by RedL0tus** [comment]
My P50 died, closing.
