### ISSUE TITLE
KDE: failed to start on testing

### ISSUE THREAD

**Issue by RedL0tus** [AOSC-Dev/aosc-os-abbs#1705]
Bug description
-----------------------

KDE 5.15.2 failed to start with xinit (SDDM failed to start, see #1704).

Output of `startkde`: https://pastebin.aosc.io/paste/g8VGLpXIMt4IvXCB1b-ttg 

OpenGL seems working fine on other DE (tested on MATE).

glxinfo: https://pastebin.aosc.io/paste/O9OhvLUdUpVenVWa4Oh64A

Reproducing steps
---------------------------

Upgrade KDE packages to the versions listed below.

Update channel(s)
--------------------------

testings, no overlay.

Package and version
------------------------------

KDE Plasma 5.15.2
KDE Frameworks 5.55.0
KDE Application 18.08.2

**Comment by RedL0tus** [comment]
Confirmed that it does work on Shintel graphics.

**Comment by MingcongBai** [comment]
So far I haven't been able to reproduce this issue. Input needed.

**Comment by RedL0tus** [comment]
My P50 died, closing.
