### ISSUE TITLE
mdm: crash on login (correct password)

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#171]
and shows the tty for a second, and immediately reloads itself back to the login interface

3月 13 01:22:25 sijie-w541.site ag[1260]: mdm-superpost Starting...
3月 13 01:22:25 sijie-w541.site ag[1261]: mdm-superpost Finished
3月 13 01:22:26 sijie-w541.site ag[1272]: mdm-superinit Starting...
3月 13 01:22:26 sijie-w541.site ag[1273]: mdm-superinit Finished
3月 13 01:22:36 sijie-w541.site mdm-binary[1262]: pam_tally(mdm:auth): pam_get_user; user?
3月 13 01:22:36 sijie-w541.site mdm-binary[1262]: pam_nologin(mdm:auth): cannot determine username
3月 13 01:22:36 sijie-w541.site ag[1306]: mdm-superinit Starting...
3月 13 01:22:36 sijie-w541.site ag[1307]: mdm-superinit Finished
3月 13 01:22:50 sijie-w541.site mdm-binary[1262]: pam_unix(mdm:session): session opened for user sijie by (uid=0)
3月 13 01:22:50 sijie-w541.site mdm[1063]: mdm-binary[1063]: WARNING: mdm_cleanup_children: child 1262 crashed of signal 11
3月 13 01:22:50 sijie-w541.site mdm[1063]: mdm-binary[1063]: WARNING: mdm_cleanup_children: Slave crashed, killing its children
3月 13 01:22:50 sijie-w541.site mdm-binary[1063]: WARNING: mdm_cleanup_children: child 1262 crashed of signal 11
3月 13 01:22:50 sijie-w541.site mdm-binary[1063]: WARNING: mdm_cleanup_children: Slave crashed, killing its children
3月 13 01:22:50 sijie-w541.site kernel: mdm-binary[1262]: segfault at 8 ip 00007f5c3501b4ea sp 00007ffd0c4661a0 error 4 in libglib-2.0.so.0.4600.2[7f5c34fe1000+ea000]

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/e256b80004e5703f98e22228120d9bb16ea3ac95, wait for an update.
