### ISSUE TITLE
fontconfig: patch for C.UTF-8

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#172]
https://sources.debian.net/src/fontconfig/2.11.0-6.3/debian/patches/03_locale_c.utf8.patch/

**Comment by Arthur2e5** [comment]
Just an aside -- personally I prefer something like:
```C
strncmp(lang, 1, "C") && (lang[1] == '.' || lang[1] == '@' || lang[1] == '\0')
```
for locale matching.

**Comment by MingcongBai** [comment]
That should be able to be merged...
