### ISSUE TITLE
nvidia, nvidia+390: security update to 410.104, 390.116

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1723]
**CVE IDs:** CVE‑2018‑6260

**Other security advisory IDs:** USN-3904-1

**Descriptions:**
It was discovered that the NVIDIA graphics drivers incorrectly handled the
GPU performance counters. A local attacker could possibly use this issue to
access the application data processed on the GPU.

https://nvidia.custhelp.com/app/answers/detail/a_id/4772

**Architectural progress (410 mainline):**

- [x] AMD64 `amd64`

**Architectural progress (390 legacy):**

- [x] AMD64 `amd64`

**Comment by MingcongBai** [comment]
@l2dy Please assign two distinct AOSAs.

- NVIDIA 410.x mainline: https://github.com/AOSC-Dev/aosc-os-abbs/commit/dbc1cb2541195b7639650143e69bd57d43c9d681 .
- NVIDIA 390.x legacy: https://github.com/AOSC-Dev/aosc-os-abbs/commit/a3d8e2a9384d56469893dfe73ac7afc8581fb573 .

Closing.

**Comment by l2dy** [comment]
Use AOSA-2019-0083 for NVIDIA 410.x mainline driver.
Use AOSA-2019-0084 for NVIDIA 390.x legacy driver.
