### ISSUE TITLE
darling: FTBFS

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/aosc-os-abbs#1724]
log: http://fars.ee/wKc8

**Comment by eatradish** [comment]
drop it!!!!!!!!!1

**Comment by MingcongBai** [comment]
Less of the shouting please. I have already dropped this package from `Stable`, as it will require introduction of new packages to fix its build (and probably functionalities).

**Comment by MingcongBai** [comment]
I will rename this issue to serve the purpose of tracking build-ability of this package.

**Comment by MingcongBai** [comment]
Orphaned in an upcoming PR. Closing.

This package could of course be re-introduced if their development picks up again.
