### ISSUE TITLE
scribus: please offer development version (v1.5.5) which is qt5 compliant 

### ISSUE THREAD

**Issue by luzpaz** [AOSC-Dev/aosc-os-abbs#1743]
Scribus stable is inferior to development version 
Would it be possible to offer a side-by-side option of stable and development?

Update channel(s)
--------------------------
*Stable, Testing, or Explosive? Any enabled Overlay(s)?*

Package and version
------------------------------
https://www.scribus.net/downloads/unstable-branch/ (1.5.4)

**Comment by MingcongBai** [comment]
Personally I'm hesitant to consider that option, but I'm open to opinions. If anyone would second @luzpaz , I am happy to switch to 1.5.x as an exception.

**Comment by luzpaz** [comment]
1.5.5 is current development version

**Comment by MingcongBai** [comment]
Stalled (feature/design change) issue, closing. Please open a new issue if this thought arises again. 

@luzpaz I will still hold off on this, let's wait for 1.6.
