### ISSUE TITLE
[DRAFT] .NET Lifecycle Policy

### ISSUE THREAD

**Issue by KexyBiscuit** [AOSC-Dev/aosc-os-abbs#1747]
# .NET Lifecycle Policy

AOSC OS includes several .NET packages, like `dotnet-{sdk,runtime}` and `mono`, which are maintained by Microsoft and the .NET community<sup>[1][1],[2][2]</sup>. This issue exists to clarify our lifecycle policy on them.

## .NET Core `dotnet-{sdk,runtime}`

.NET Core has 2 [release types](https://dotnet.microsoft.com/platform/support/policy/dotnet-core). Currently, we have LTS (2.1 at time of the writing) in `stable` branch, and Current (2.2 at time of the writing) in `testing` branch.

### Policy

`stable`: Latest LTS release
`testing`: Latest Current release

## Mono `mono`

Mono has 2 [release channels](https://www.mono-project.com/download/). Currently, we have Stable (5.18 at time of the writing) in `stable` and `testing` branch. Mono also has a [Visual Studio channel](https://www.mono-project.com/download/vs/) (5.16 at time of the writing), which is "the most tested but also the least frequently updated".

### Policy

`stable`: Latest Visual Studio release
`testing`: Latest Stable release

### Policy

`stable`: Latest release

## MSBuild + Mono `msbuild`

TODO

## NuGet + Mono `nuget`

NuGet has many [distribution versions available](https://www.nuget.org/downloads). Currently, we have v4.7 in `stable` branch, and v4.9 (recommended latest at time of the writing) in `testing` branch.

### Policy

`stable`: Latest recommended release

## See also

[2018 冬季周期工作指南](https://gist.github.com/MingcongBai/78f6923828bccc51f81019fd99462e6a)

[1]: https://docs.microsoft.com/en-us/dotnet/core/
[2]: https://www.mono-project.com/

**Comment by MingcongBai** [comment]
I would ensure that both branches could receive timely security updates, otherwise no objection from me.

**Comment by KexyBiscuit** [comment]
With no more comments, this will be moved to [Wiki](https://wiki.aosc.io/lifecycle/dotnet) in one day.

**Comment by KexyBiscuit** [comment]
Moved.
