### ISSUE TITLE
nodejs: docs related build script doesn't work

### ISSUE THREAD

**Issue by KexyBiscuit** [AOSC-Dev/aosc-os-abbs#1759]
Bug description
-----------------------

```shell
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man5/' is not a directory: No such file or directory
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man5/' is not a directory: No such file or directory
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man5/' is not a directory: No such file or directory
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man5/' is not a directory: No such file or directory
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man5/' is not a directory: No such file or directory
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man5/' is not a directory: No such file or directory
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man5/' is not a directory: No such file or directory
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man5/' is not a directory: No such file or directory
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man7/' is not a directory: No such file or directory
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man7/' is not a directory: No such file or directory
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man7/' is not a directory: No such file or directory
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man7/' is not a directory: No such file or directory
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man7/' is not a directory: No such file or directory
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man7/' is not a directory: No such file or directory
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man7/' is not a directory: No such file or directory
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man7/' is not a directory: No such file or directory
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man7/' is not a directory: No such file or directory
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man7/' is not a directory: No such file or directory
ln: target '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man7/' is not a directory: No such file or directory
rm: cannot remove '/var/cache/acbs/build/acbs.bjslzdce/node-10.15.3/abdist/usr/share/man/man1/doc': No such file or directory
```

Reproducing steps
---------------------------

Build `nodejs`.

Update channel(s)
--------------------------

`stable`

Package and version
------------------------------

`nodejs` 10.15.3

**Comment by KexyBiscuit** [comment]
Related code: https://github.com/AOSC-Dev/aosc-os-abbs/blob/7aa4bd50b1772c0b229f95a756f7d108f107839e/extra-js/nodejs/autobuild/build#L10

**Comment by Garfield550** [comment]
Maybe node.js doc doesn't have man5 and man7 section

```
➜  ~ man -w node
/usr/local/share/man/man1/node.1
```

https://github.com/nodejs/node/blob/master/BUILDING.md#building-the-documentation

**Comment by eatradish** [comment]
``` 
~  dpkg -L nodejs | grep "/usr/share"                                                                                                           Wed Apr  3 14:27:04 2019
/usr/share
/usr/share/doc
/usr/share/doc/node
/usr/share/doc/node/gdbinit
/usr/share/doc/node/lldb_commands.py
/usr/share/doc/node/lldbinit
/usr/share/doc/nodejs
/usr/share/doc/nodejs/LICENSE
/usr/share/man
/usr/share/man/man1
/usr/share/systemtap
/usr/share/systemtap/tapset
/usr/share/systemtap/tapset/node.stp
/usr/share/man/man1/npm-README.1
/usr/share/man/man1/npm-access.1
/usr/share/man/man1/npm-adduser.1
/usr/share/man/man1/npm-audit.1
/usr/share/man/man1/npm-bin.1
/usr/share/man/man1/npm-bugs.1
/usr/share/man/man1/npm-build.1
/usr/share/man/man1/npm-bundle.1
/usr/share/man/man1/npm-cache.1
/usr/share/man/man1/npm-ci.1
/usr/share/man/man1/npm-completion.1
/usr/share/man/man1/npm-config.1
/usr/share/man/man1/npm-dedupe.1
/usr/share/man/man1/npm-deprecate.1
/usr/share/man/man1/npm-dist-tag.1
/usr/share/man/man1/npm-docs.1
/usr/share/man/man1/npm-doctor.1
/usr/share/man/man1/npm-edit.1
/usr/share/man/man1/npm-explore.1
/usr/share/man/man1/npm-help-search.1
/usr/share/man/man1/npm-help.1
/usr/share/man/man1/npm-hook.1
/usr/share/man/man1/npm-init.1
/usr/share/man/man1/npm-install-ci-test.1
/usr/share/man/man1/npm-install-test.1
/usr/share/man/man1/npm-install.1
/usr/share/man/man1/npm-link.1
/usr/share/man/man1/npm-logout.1
/usr/share/man/man1/npm-ls.1
/usr/share/man/man1/npm-outdated.1
/usr/share/man/man1/npm-owner.1
/usr/share/man/man1/npm-pack.1
/usr/share/man/man1/npm-ping.1
/usr/share/man/man1/npm-prefix.1
/usr/share/man/man1/npm-profile.1
/usr/share/man/man1/npm-prune.1
/usr/share/man/man1/npm-publish.1
/usr/share/man/man1/npm-rebuild.1
/usr/share/man/man1/npm-repo.1
/usr/share/man/man1/npm-restart.1
/usr/share/man/man1/npm-root.1
/usr/share/man/man1/npm-run-script.1
/usr/share/man/man1/npm-search.1
/usr/share/man/man1/npm-shrinkwrap.1
/usr/share/man/man1/npm-star.1
/usr/share/man/man1/npm-stars.1
/usr/share/man/man1/npm-start.1
/usr/share/man/man1/npm-stop.1
/usr/share/man/man1/npm-team.1
/usr/share/man/man1/npm-test.1
/usr/share/man/man1/npm-token.1
/usr/share/man/man1/npm-uninstall.1
/usr/share/man/man1/npm-unpublish.1
/usr/share/man/man1/npm-update.1
/usr/share/man/man1/npm-version.1
/usr/share/man/man1/npm-view.1
/usr/share/man/man1/npm-whoami.1
/usr/share/man/man1/npm.1
/usr/share/man/man1/npx.1
```
maybe should remove `man5 man7`

**Comment by eatradish** [comment]
but why remove man?

**Comment by Garfield550** [comment]
> ```
> ~  dpkg -L nodejs | grep "/usr/share"                                                                                                           Wed Apr  3 14:27:04 2019
> /usr/share
> /usr/share/doc
> /usr/share/doc/node
> /usr/share/doc/node/gdbinit
> /usr/share/doc/node/lldb_commands.py
> /usr/share/doc/node/lldbinit
> /usr/share/doc/nodejs
> /usr/share/doc/nodejs/LICENSE
> /usr/share/man
> /usr/share/man/man1
> /usr/share/systemtap
> /usr/share/systemtap/tapset
> /usr/share/systemtap/tapset/node.stp
> /usr/share/man/man1/npm-README.1
> /usr/share/man/man1/npm-access.1
> /usr/share/man/man1/npm-adduser.1
> /usr/share/man/man1/npm-audit.1
> /usr/share/man/man1/npm-bin.1
> /usr/share/man/man1/npm-bugs.1
> /usr/share/man/man1/npm-build.1
> /usr/share/man/man1/npm-bundle.1
> /usr/share/man/man1/npm-cache.1
> /usr/share/man/man1/npm-ci.1
> /usr/share/man/man1/npm-completion.1
> /usr/share/man/man1/npm-config.1
> /usr/share/man/man1/npm-dedupe.1
> /usr/share/man/man1/npm-deprecate.1
> /usr/share/man/man1/npm-dist-tag.1
> /usr/share/man/man1/npm-docs.1
> /usr/share/man/man1/npm-doctor.1
> /usr/share/man/man1/npm-edit.1
> /usr/share/man/man1/npm-explore.1
> /usr/share/man/man1/npm-help-search.1
> /usr/share/man/man1/npm-help.1
> /usr/share/man/man1/npm-hook.1
> /usr/share/man/man1/npm-init.1
> /usr/share/man/man1/npm-install-ci-test.1
> /usr/share/man/man1/npm-install-test.1
> /usr/share/man/man1/npm-install.1
> /usr/share/man/man1/npm-link.1
> /usr/share/man/man1/npm-logout.1
> /usr/share/man/man1/npm-ls.1
> /usr/share/man/man1/npm-outdated.1
> /usr/share/man/man1/npm-owner.1
> /usr/share/man/man1/npm-pack.1
> /usr/share/man/man1/npm-ping.1
> /usr/share/man/man1/npm-prefix.1
> /usr/share/man/man1/npm-profile.1
> /usr/share/man/man1/npm-prune.1
> /usr/share/man/man1/npm-publish.1
> /usr/share/man/man1/npm-rebuild.1
> /usr/share/man/man1/npm-repo.1
> /usr/share/man/man1/npm-restart.1
> /usr/share/man/man1/npm-root.1
> /usr/share/man/man1/npm-run-script.1
> /usr/share/man/man1/npm-search.1
> /usr/share/man/man1/npm-shrinkwrap.1
> /usr/share/man/man1/npm-star.1
> /usr/share/man/man1/npm-stars.1
> /usr/share/man/man1/npm-start.1
> /usr/share/man/man1/npm-stop.1
> /usr/share/man/man1/npm-team.1
> /usr/share/man/man1/npm-test.1
> /usr/share/man/man1/npm-token.1
> /usr/share/man/man1/npm-uninstall.1
> /usr/share/man/man1/npm-unpublish.1
> /usr/share/man/man1/npm-update.1
> /usr/share/man/man1/npm-version.1
> /usr/share/man/man1/npm-view.1
> /usr/share/man/man1/npm-whoami.1
> /usr/share/man/man1/npm.1
> /usr/share/man/man1/npx.1
> ```
> maybe should remove `man5 man7`

And build node.js doc before removing man5/man7, because this package doesn't contain node.1 file.

```
➜  ~ ls /usr/local/share/man/man1 | grep node
node.1
```

**Comment by eatradish** [comment]
Fixed, closing.
