### ISSUE TITLE
pakreq-py: stackless

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#176]
https://bitbucket.org/stackless-dev/stackless/wiki/Home

**Comment by MingcongBai** [comment]
`stackless-2` at 057c186c29f7e641a1ff1e1445b1c17a9acd68f1;
`stackless-3` at e884df310bf2e02c8b4d45ab1646fb3387d77fd3;
`stackless-env` providing the `profile.d` file, at e38e71d013f91bb6b8ec09b841615e97ac9dec99;

Might look into exec prefix later, the `/opt` placement is just a pain.
