### ISSUE TITLE
intel-ucode: update to 20190312

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1764]
**CVE IDs:** N/A

**Other security advisory IDs:** openSUSE-SU-2019:1084-1

**Architectural progress:**

- [x] AMD64 `amd64`

**Comment by l2dy** [comment]
https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20190312

**Comment by KexyBiscuit** [comment]
:shipit: with d6d546b.

**Comment by l2dy** [comment]
Use AOSA-2019-0162.
