### ISSUE TITLE
fc: freefont

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#178]
The current 69-freefont.conf prefers freefont unconditionally, which is terrible.

And actually we need some extra entries for 30-metric-aliases.conf:

* FreeSerif = URW++ Nimbus Roman No9 = Times
* FreeSans = URW++ Nimbus Sans L = Helvetica
* FreeMono = URW++ Nimbus Mono L = Courier

You can actually consider all the FreeFont's some extended charset version of their URW++ sources.

**Comment by MingcongBai** [comment]
What are some suggested actions then?

**Comment by Arthur2e5** [comment]
Nuke 69-freesans.conf from freesans, patch 30-metrics-aliases.conf.

**Comment by MingcongBai** [comment]
Got it.

**Comment by Arthur2e5** [comment]
Or we can avoid changing fc by writing some `accept` in 31-freefont.conf.

**Comment by Arthur2e5** [comment]
Updated comment.

**Comment by Arthur2e5** [comment]
Testing needed.

**Comment by Arthur2e5** [comment]
Uh, 45-freefonts should be moved to fc and merged into 45-latin.

**Comment by Arthur2e5** [comment]
Uh, I still think these should be fc.. crap.

**Comment by Arthur2e5** [comment]
Sorry Bai you have to wipe all the () again..

**Comment by MingcongBai** [comment]
> Sorry Bai you have to wipe all the () again..

I feel sorry for the commit msgs... Just kidding go ahead.

**Comment by Arthur2e5** [comment]
Just rebase them before anyone else can see(

I need to eat.
