### ISSUE TITLE
audacity: v2.3.1 FTBFS on ppc32

### ISSUE THREAD

**Issue by KexyBiscuit** [AOSC-Dev/aosc-os-abbs#1790]
Bug description
-----------------------

```shell
/usr/lib/gcc/powerpc-aosc-linux-gnu/7.3.1/../../../libsratom-0.so: undefined reference to `serd_free'
```

Update channel(s)
--------------------------

`stable`

Package and version
------------------------------

`audacity` v2.3.1

**Comment by MingcongBai** [comment]
`ppc32be`, or `powerpc` in DPKG speech is now a Retro port. Closing.
