### ISSUE TITLE
OpenRA: Bump to 20190314, maybe open up some other mods

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#1818]
OpenRA needs a version bump for, uh... multiplayer and "bugfixes and stability improvements" I guess. They also have some promising out-of-tree mods like [RA2](https://github.com/OpenRA/ra2), which relies on the main binary to build. I don't know whether we should split them or just keep them together yet.

Arch AUR has a pretty simple [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openra-git) for putting everything in one package.

To let the user actually *see* the extra mods we will need to do some extra work. We will need to go down to the desktop-making section and copy some lines so the icons for TS and RA2 are visible. I might make that easier if I get around to finishing a PR for OpenRA/OpenRA#16439, but being the useless flesh pile I am idk

**Comment by Icenowy** [comment]
I remember RA2 usually ties to a specific core engine version.

So I suggest a splitted package with bundled OpenRA core for RA2.

**Comment by Artoria2e5** [comment]
How is it split if it's bundled?

**Comment by Icenowy** [comment]
Maybe I should use the word "dedicated" here.

**Comment by Artoria2e5** [comment]
The version tie is determined at build-time with the ENGINE_VERSION makefile variable. We can always build an RA2 against any current and future versions of OpenRA. What's the point of making a dedicated build then?

**Comment by Icenowy** [comment]
OpenRA promises no API stability.

If you change ENGINE_VERSION, there's a high probability you will get a build failurw.

**Comment by Artoria2e5** [comment]
Fair enough, but the AUR thing seems to build against 201903 while RA2 is asking for 201809. They aren't changing that much you see.

**Comment by MingcongBai** [comment]
Addressed with 570979d6690a37fe008f01f22bc9ae712d04e998. Closing.
