### ISSUE TITLE
pakreq-misc: cp-l

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#182]
https://github.com/AOSC-Dev/scriptlets/blob/master/cp-l

dep:
- bash
- cp-min
- getopt-min

recom:
- coreutils (cp)

**Comment by MingcongBai** [comment]
That would need Core 3.6.0 with its busybox integration in place wouldn't it...

**Comment by Arthur2e5** [comment]
按照现在这个依赖列表说是的……

**Comment by MingcongBai** [comment]
I will tag this "investigating" until Core 3.6.0 is ready.

**Comment by MingcongBai** [comment]
Stalled (feature/design change) issue, closing. Please open a new issue if this thought arises again.
