### ISSUE TITLE
vscode 1.33.1: make process crash

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/aosc-os-abbs#1837]
look this:
```
[[90m15:20:00[39m] Finished '[36mvscode-linux-x64-min[39m' after [35m5.67 min[39m
[2K[1GDone in 343.88s.
'/var/cache/acbs/build/acbs.nioxz0mq/vscode/abdist/usr/bin/vscode' -> '/usr/share/code/bin/code-oss'

!!Build exited with 127
```
log: http://fars.ee/ZIWn

this like a autobuild3 bug

**Comment by Artoria2e5** [comment]
do you have both dpkg and rpm installed? this looks like acbs reporting a command not found (127) from abbs.

**Comment by eatradish** [comment]
> do you have both dpkg and rpm installed? this looks like acbs reporting a command not found (127) from abbs.

yes.....I installed

**Comment by eatradish** [comment]
The problem has been resolved(14c442f9810702ee2340da524bf48e71e4f5a480), but it still needs investigation.

I use nvm, and add `echo $PATH` on last line in `build` file, but i see `/usr/bin` and `/bin` in `$PATH`

**Comment by Artoria2e5** [comment]
nvm pkgdep = "bash wget curl"

obviously it's gonna...
now that i think about it the 127 could be a #! not found

**Comment by MingcongBai** [comment]
We are way past this issue. Closing.
