### ISSUE TITLE
pakreq: urw-base-12 (otf)

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#185]
This looks like a source of "Newer" URW++ fonts, still using the GPL README.

http://git.ghostscript.com/?p=user/tor/urw-base-12.git;a=blob;f=README;h=a9562ff

**Comment by MingcongBai** [comment]
Currently the Nimbus font family is provided as a part of `urw-fonts`, in `.pfb` format. Whether or not this is a necesity is open for a discussion.
