### ISSUE TITLE
sqlmap: bump up version

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#188]
1.0.3 tagged. (the 'micro' version represent the month [[1]](https://github.com/sqlmapproject/sqlmap/issues/1765))

**Comment by MingcongBai** [comment]
Got it.

**Comment by liushuyu** [comment]
Quick action (*cough*)😃
2016年3月21日 11:09，"Mingcong Bai" <notifications@github.com>写道：

**Comment by MingcongBai** [comment]
Sorry... Some "nowhere" motel in New Mexico. Fun place though.
