### ISSUE TITLE
zathura-pdf-poppler: SRC download timeout

### ISSUE THREAD

**Issue by bobcao3** [AOSC-Dev/aosc-os-abbs#1901]
Bug description
-----------------------

zathura-pdf-poppler's SRC link timeout when trying to download src. (North america)

Reproducing steps
---------------------------

acbs build zathura-pdf-poppler

Update channel(s)
--------------------------

Stable

Package and version
------------------------------

zathura-pdf-poppler : 0.2.9-1

**Comment by MingcongBai** [comment]
Transitive issue. Closing. (Surprise, it builds now)
