### ISSUE TITLE
rdesktop: security update to 1.8.6

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#1907]
**CVE IDs:** N/A

**Other security advisory IDs:** DSA-4473-1, MGASA-2019-0247

**Descriptions:**
Multiple security issues were found in the rdesktop RDP client, which
could result in denial of service and the execution of arbitrary code.

**Architectural progress:**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] ARMv7 `armel`
- [x] PowerPC 64-bit BE `ppc64`

**Comment by MingcongBai** [comment]
All done. @l2dy Please assign an AOSA.

**Comment by l2dy** [comment]
Use AOSA-2020-0035.
