### ISSUE TITLE
pakreq: ssh-hpn

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#191]
https://www.psc.edu/index.php/hpn-ssh
"High performance" OpenSSH 6.3 patches with crazy or sane tweaks like:

* network RWIN size
* network buffer size
* Multi-threaded cipher
* "None" cipher
* switch to "None" cipher after encrypted auth

Since this is for OpenSSH 6.3, get ready for manual porting.

**Comment by Arthur2e5** [comment]
Oh, newer version available at https://github.com/rapier1/openssh-portable.

**Comment by MingcongBai** [comment]
So we will need alternatives here huh...
