### ISSUE TITLE
Update to ICU 64.2

### ISSUE THREAD

**Issue by KexyBiscuit** [AOSC-Dev/aosc-os-abbs#1922]
## Rebuild

- [x] brltty
- [x] xfsprogs
- [x] couchdb
- [x] mongo-c-driver
- [x] cutter
- [x] hhvm
- [x] php7
- [x] emacs
- [x] open-vm-tools
- [x] 0ad
- [x] epiphany
- [x] evolution-data-server
- [x] gnome-calendar
- [x] tracker-miners
- [x] tracker
- [x] gnustep-base
- [x] gnustep-corebase
- [x] gnustep-gui
- [x] renaissance
- [x] fcitx
- [x] ibus-qt
- [x] poedit
- [x] nodejs
- [x] boost
- [x] dee #1951
- [x] harfbuzz
- [x] js-38
- [x] js-45
- [x] js-52
- [x] libcdr
- [x] libe-book
- [x] libical
- [x] libmspub
- [x] libphonenumber
- [x] libqalculate
- [x] libqxp
- [x] libvisio
- [x] libzmf
- [x] poppler
- [x] qt-4
- [x] qt-5
- [x] raptor2
- [x] webkit2gtk
- [x] webkitgtk
- [x] xerces-c
- [x] aegisub
- [x] freshplayerplugin
- [x] mpd
- [x] ncmpcpp
- [x] dovecot
- [x] postfix
- [x] rspamd
- [x] boost+32
- [x] harfbuzz+32
- [x] calibre
- [x] libreoffice
- [x] pyicu
- [x] r
- [x] dff
- [x] powershell
- [x] texlive
- [x] darling-dmg
- [x] maim
- [x] slop
- [x] tesseract
- [x] unar
- [x] firefox
- [x] google-chrome
- [x] palemoon
- [x] seamonkey
- [x] thunderbird
- [x] znc

**Comment by KexyBiscuit** [comment]
All completed except `dee`, which has a dedicated issue, closing. :shipit:

**Comment by MingcongBai** [comment]
@KexyBiscuit Congratulations!
