### ISSUE TITLE
Weekly Testing Queue for Stable-Proposed (20190802)

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#1935]
Effective August 2, 2019 @ 15:56, UTC Time.

- [ ] bsp-sunxi(arm64): linux-kernel-sunxi64-5.3.0-rc2 `v5.3.0~rc2`
- [ ] bsp-sunxi(arm64): linux-kernel-sunxi64-5.3.0-rc2 `v5.3.0~rc2-1`
- [ ] bsp-sunxi(arm64): linux+kernel+sunxi64 `v22~1`
- [ ] bsp-sunxi(armel): linux-kernel-sunxi-kvm-5.3.0-rc2 `v5.3.0~rc2`
- [ ] bsp-sunxi(armel): linux+kernel+sunxi+kvm `v11~1`
- [ ] bsp-sunxi(armel): linux-kernel-sunxi-nokvm-5.3.0-rc2 `v5.3.0~rc2`
- [ ] bsp-sunxi(armel): linux+kernel+sunxi+nokvm `v11~1`
- [x] main(amd64): aisleriot `v3.22.8`
- [x] main(amd64): alsa-lib `v1.1.9`
- [x] main(amd64): alsa-plugins `v1.1.9`
- [x] main(amd64): alsa-utils `v1.1.9`
- [x] main(amd64): appstream-glib `v0.7.15`
- [x] main(amd64): aravis `v0.6.3`
- [x] main(amd64): at-spi2-atk `v2.30.1`
- [x] main(amd64): at-spi2-core `v2.30.1`
- [x] main(amd64): autogen `v5.18.12-2`
- [x] main(amd64): avidemux `v2.7.3`
- [x] main(amd64): babeltrace `v1.5.7`
- [x] main(amd64): babl `v0.1.68`
- [x] main(amd64): balsa `v2.5.7`
- [x] main(amd64): brave-browser `v0.66.101-1`
- [x] main(amd64): brial `v1.2.5`
- [x] main(amd64): bubblewrap `v0.3.3`
- [x] main(amd64): bzip2 `v1.0.8`
- [x] main(amd64): ccache `v3.7.2`
- [x] main(amd64): cdemu-client `v3.2.1`
- [x] main(amd64): chromium `v76.0.3809.87`
- [x] main(amd64): cmake `v3.13.5`
- [x] main(amd64): cmocka `v1.1.5`
- [x] main(amd64): cogl `v1.22.4`
- [x] main(amd64): colm `v0.13.0.7`
- [x] main(amd64): colord `v1.4.4`
- [x] main(amd64): cpprestsdk `v2.10.14`
- [x] main(amd64): crash `v7.2.6`
- [x] main(amd64): cups `v2.2.11`
- [x] main(amd64): dep `v0.5.4`
- [x] main(amd64): docker `v18.09.8`
- [x] main(amd64): enchant-2 `v2.2.5`
- [x] main(amd64): epiphany `v3.30.4`
- [x] main(amd64): exim `v4.92.1`
- [x] main(amd64): fox `v1.7.65`
- [x] main(amd64): freetds `v1.00.112`
- [x] main(amd64): fwupd `v1.2.10`
- [x] main(amd64): gawk `v5.0.1`
- [x] main(amd64): gdk-pixbuf `v2.38.1`
- [x] main(amd64): gdm `v3.30.3`
- [x] main(amd64): geocode-glib `v3.26.1`
- [x] main(amd64): geos `v3.7.2`
- [x] main(amd64): ghex `v3.18.4`
- [x] main(amd64): glide `v0.13.3`
- [x] main(amd64): glslang `v7.11.3214`
- [x] main(amd64): glu `v9.0.1`
- [x] main(amd64): gnome-chess `v3.30.1`
- [x] main(amd64): gnome-control-center `v3.30.3`
- [x] main(amd64): gnome-online-accounts `v3.30.2`
- [x] main(amd64): gnome-terminal `v3.30.3`
- [x] main(amd64): gnupg `v2.2.17`
- [x] main(amd64): gnutls `v3.6.9`
- [x] main(amd64): goffice `v0.10.45`
- [x] main(amd64): go-md2man `v1.0.10`
- [x] main(amd64): google-chrome `v76.0.3809.87-1`
- [x] main(amd64): go `v1.12.7`
- [x] main(amd64): granite `v5.2.4`
- [x] main(amd64): grilo-plugins `v0.3.9`
- [x] main(amd64): grilo `v0.3.9`
- [x] main(amd64): groovy `v2.5.7`
- [x] main(amd64): gsoap `v2.8.88`
- [x] main(amd64): gtk-3 `v3.24.10`
- [x] main(amd64): guile `v2.2.6`
- [x] main(amd64): gupnp `v1.0.4`
- [x] main(amd64): gvfs `v1.38.3`
- [x] main(amd64): gvim `v8.1.1735`
- [x] main(amd64): hdf5 `v1.10.5`
- [x] main(amd64): help2man `v1.47.10`
- [x] main(amd64): hplip `v3.19.6`
- [x] main(amd64): http-parser `v2.9.2`
- [x] main(amd64): ibus-libpinyin `v1.11.1`
- [x] main(amd64): ibus `v1.5.20`
- ~main(amd64): imake `v1.0.8`~ *Failed: version hard-coded in build scripts.*
- [x] main(amd64): kaffeine `v2.0.18`
- [x] main(amd64): kcptun `v20190725`
- [x] main(amd64): kdeconnect `v1.3.4`
- [x] main(amd64): kicad `v5.1.2`
- [x] main(amd64): lasem `v0.5.1`
- [x] main(amd64): latte-dock `v0.8.9`
- [x] main(amd64): libassuan `v2.5.3`
- [x] main(amd64): libatomic-ops `v7.6.10`
- [x] main(amd64): libchamplain `v0.12.19`
- [x] main(amd64): libcroco `v0.6.13`
- [x] main(amd64): libebml `v1.3.9`
- [x] main(amd64): libevent `v2.1.10`
- [x] main(amd64): libfm-qt `v0.14.1`
- [x] main(amd64): libgda `v5.2.9`
- [x] main(amd64): libgit2 `v0.28.2`
- [x] main(amd64): libglvnd `v1.1.1`
- [x] main(amd64): libgnomekbd `v3.26.1`
- ~main(amd64): libgovirt `v0.3.6`~ *Failed: GNOME Boxes failed at libosinfo, could not test oVirt support.*
- [x] main(amd64): libgsf `v1.14.46`
- [x] main(amd64): libgweather `v3.28.3`
- [x] main(amd64): libhubbub `v0.3.6`
- [x] main(amd64): libibus `v1.5.20`
- [x] main(amd64): libical `v3.0.5`
- [x] main(amd64): libindi `v1.7.9`
- [x] main(amd64): libiodbc `v3.52.13`
- [x] main(amd64): libltc `v1.3.1`
- [x] main(amd64): liblxqt `v0.14.1`
- [x] main(amd64): libmbim `v1.18.2`
- [x] main(amd64): libmicrohttpd `v0.9.65`
- [x] main(amd64): libmirage `v3.2.2`
- [x] main(amd64): libnftnl `v1.1.3`
- [x] main(amd64): libnice `v0.1.16`
- [x] main(amd64): libnotify `v0.7.8`
- [x] main(amd64): libp11 `v0.4.10`
- [x] main(amd64): libphonenumber `v8.10.15`
- [x] main(amd64): libpng `v1.6.37`
- [x] main(amd64): libqaccessibilityclient `v0.4.1`
- [x] main(amd64): libqmi `v1.22.4`
- [x] main(amd64): libqtxdg `v3.3.1`
- [x] main(amd64): libratbag `v0.9.906`
- [x] main(amd64): libraw `v0.19.3`
- [x] main(amd64): libseccomp `v2.4.1`
- [x] main(amd64): libsecret `v0.18.8`
- [x] main(amd64): libsigc++ `v2.10.2`
- [x] main(amd64): libsodium `v1.0.18`
- [x] main(amd64): libsolv `v0.7.5`
- [x] main(amd64): libsysstat `v0.4.2`
- [x] main(amd64): libtorrent-rasterbar `v1.2.1`
- [x] main(amd64): libu2f-host `v1.1.10`
- [x] main(amd64): libwapcaplet `v0.4.2`
- [x] main(amd64): libwebp `v1.0.3`
- [x] main(amd64): libxkbcommon `v0.8.4`
- [x] main(amd64): libxmlb `v0.1.11`
- [x] main(amd64): libzip `v1.5.2`
- [x] main(amd64): libzypp `v17.11.4`
- ~main(amd64): link-grammar `v5.6.2`~ *Failed: link-grammar: Fatal error: Unable to open default dictionary.*
- [x] main(amd64): linux-kernel-5.2.5 `v5.2.5`
- [x] main(amd64): linux-kernel-lts-4.19.63 `v4.19.63`
- ~main(amd64): llfuse `v1.3.6`~ *Failed: ImportError: No module named contextlib2.*
- [x] main(amd64): lmdb `v0.9.24`
- [x] main(amd64): lttng-ust `v2.10.4`
- [x] main(amd64): lua-mpack `v1.0.8`
- ~main(amd64): lvm2 `v2.02.185`~ *Failed: fixed in 2.02.185-1.*
- [x] main(amd64): lxqt-about `v0.14.1`
- [x] main(amd64): lxqt-admin `v0.14.1`
- [x] main(amd64): lxqt-config `v0.14.1`
- [x] main(amd64): lxqt-globalkeys `v0.14.1`
- [x] main(amd64): lxqt-notificationd `v0.14.1`
- [x] main(amd64): lxqt-panel `v0.14.1`
- [x] main(amd64): lxqt-policykit `v0.14.1`
- [x] main(amd64): lxqt-powermanagement `v0.14.1`
- [x] main(amd64): lxqt-runner `v0.14.1`
- [x] main(amd64): lxqt-session `v0.14.1`
- [x] main(amd64): lxqt-sudo `v0.14.1`
- [x] main(amd64): lxrandr `v0.3.2`
- [x] main(amd64): lxsession `v0.5.4`
- [x] main(amd64): lxtask `v0.1.9`
- [x] main(amd64): mbedtls `v2.16.2`
- [x] main(amd64): mbpfan `v2.1.1`
- [x] main(amd64): memcached `v1.5.16`
- [x] main(amd64): mesa `v19.1.3`
- [x] main(amd64): minetest `v5.0.1`
- ~main(amd64): multimc5 `v0.6.6`~ *Failed: MulitiMC couldn't create a log file - the MultiMC data folder is not writable... MultiMC cannot continue until you fix this problem.*
- [x] main(amd64): nautilus-python `v1.2.3`
- [x] main(amd64): neovim `v0.3.8`
- [x] main(amd64): newt `v0.52.21`
- [x] main(amd64): ngs `v2.9.6`
- [x] main(amd64): nodejs `v10.16.1`
- [x] main(amd64): obconf-qt `v0.14.1`
- [x] main(amd64): onig `v6.9.2`
- [x] main(amd64): openblas `v0.3.6`
- [x] main(amd64): opencolorio `v1.1.1`
- [x] main(amd64): openjpeg `v2.3.1`
- ~main(amd64): openldap `v2.4.48`~ *Failed: slapd.service failed to start.*
- [x] main(amd64): openssl+1.0 `v1.0.2s`
- [x] main(amd64): opera `v62.0.3331.99-1`
- [x] main(amd64): pacman `v5.1.3`
- [x] main(amd64): palemoon `v28.6.1`
- [x] main(amd64): pari `v2.11.2`
- [x] main(amd64): pavucontrol-qt `v0.14.1`
- [x] main(amd64): pcmanfm-qt `v0.14.1`
- [x] main(amd64): pdf2djvu `v0.9.13`
- [x] main(amd64): phonon-backend-gstreamer `v4.9.1`
- [x] main(amd64): phonon-backend-vlc `v0.10.3`
- [x] main(amd64): phonon `v4.10.3`
- ~main(amd64): php7 `v7.3.7`~ *Failed: [05-Aug-2019 10:03:24] ERROR: No pool defined. at least one pool section must be specified in config file.*
- [x] main(amd64): physfs `v3.0.2`
- [x] main(amd64): pixman `v0.38.4`
- [x] main(amd64): png++ `v0.2.10`
- [x] main(amd64): poedit `v2.2.3`
- [x] main(amd64): postgis `v2.5.2`
- [x] main(amd64): powerpc-utils `v1.3.7`
- [x] main(amd64): protobuf-c `v1.3.1-3`
- [x] main(amd64): protobuf-c `v1.3.2`
- [x] main(amd64): pstate-frequency `v3.10.3`
- [x] main(amd64): ptex `v2.3.2`
- ~main(amd64): qtcreator `v4.7.2`~ *Failed: /usr/libexec/qtcreator/clangbackend: error while loading shared libraries: libclang.so.7: cannot open shared object file: No such file or directory. Move `libclang.so.*` to `llvm-runtime`.*
- ~main(amd64): qterminal `v0.14.1`~ *Failed: Gdk-Message: 09:49:13.453: qterminal: Fatal IO error 2 (No such file or directory) on X server :0.0.*
- ~main(amd64): qtermwidget `v0.14.1`~ *See above.*
- [x] main(amd64): redis `v5.0.5`
- [x] main(amd64): rrdtool `v1.7.2`
- [x] main(amd64): sass `v3.7.4`
- [x] main(amd64): sddm `v0.18.1`
- [x] main(amd64): sdl2-image `v2.0.5`
- [x] main(amd64): sdl `v1.2.15-7`
- [x] main(amd64): sigil `v0.9.16`
- [x] main(amd64): slick-greeter `v1.2.6`
- [x] main(amd64): sqlitebrowser `v3.11.2`
- [x] main(amd64): suil `v0.10.4`
- [x] main(amd64): synaptic `v0.84.6`
- [x] main(amd64): systemd `v242-2`
- [x] main(amd64): totem-pl-parser `v3.26.3`
- [x] main(amd64): tracker-miners `v2.1.6`
- [x] main(amd64): tracker `v2.1.8`
- [x] main(amd64): ttfautohint `v1.8.3`
- [x] main(amd64): udisks-2 `v2.8.4`
- [x] main(amd64): util-linux `v2.33.1-3`
- [x] main(amd64): vala `v0.42.7`
- [x] main(amd64): vim-nox `v8.1.1735`
- [x] main(amd64): vim-runtime `v8.1.1735`
- [x] main(amd64): vim `v8.1.1735`
- ~main(amd64): virtualbox-guest `v6.0.10`~ *Failed: DKMS modules failed to build, but *make.log* seems fine.*
- ~main(amd64): virtualbox `v6.0.10` (have issue)~ *See above.*
- [x] main(amd64): virtualgl `v2.6.2`
- [x] main(amd64): vte-gtk3 `v0.54.4`
- ~main(amd64): vulkan `v1.1.114`~ *Retracted.*
- [x] main(amd64): xapian-bindings `v1.4.12`
- [x] main(amd64): xapian-core `v1.4.12`
- [x] main(amd64): xmlsec `v1.2.28`
- [x] main(amd64): z3 `v4.8.5`
- [x] main(amd64): zypper `v1.14.28`
- [x] main(noarch): alsa-lib+32 `v1.1.9`
- [x] main(noarch): alsa-plugins+32 `v1.1.9`
- [x] main(noarch): autobuild3 `v20190723`
- [x] main(noarch): autobuild3 `v20190726`
- ~main(noarch): beets `v1.4.9`~ *Failed: requires `jellyfish` v0.6.0, while Arch Linux (built with Python 3) doesn't seem to have this issue. Switch to Python 3 next week.*
- [x] main(noarch): commons-pool2 `v2.6.2`
- [x] main(noarch): firmware-free `v20190726`
- [x] main(noarch): firmware-nonfree `v20190726`
- ~main(noarch): glances `v3.1.1`~ *Failed: missing dependency `future`~, large amount of backtrace output - while the interface fails to display. Pending for next week~.*
- [x] main(noarch): glm `v0.9.9.5`
- [x] main(noarch): libpng-1.6+32 `v1.6.37`
- [x] main(noarch): lightdm-settings `v1.2.7`
- [x] main(noarch): linux+kernel+lts `v4.19.63`
- [x] main(noarch): linux+kernel `v5.2.5`
- [x] main(noarch): lutris `v0.5.2.2`
- [x] main(noarch): mate-themes `v3.22.20`
- [x] main(noarch): pushpkg `v20190728`
- [x] main(noarch): sphinxcontrib-websupport `v1.1.2`
- [x] main(noarch): sphinx-rtd-theme `v0.4.3`
- [x] main(noarch): yard `v0.9.20`
- [x] main(noarch): yarn `v1.16.0-1`
- [x] main(noarch): youtube-dl `v2019.07.30`
- [x] main(powerpc): linux-kernel-4.9.186 `v4.9.186`
- [x] main(powerpc): linux+kernel `v1`

**Comment by liushuyu** [comment]
>- [ ] ~~main(noarch): glances v3.1.1~~ Failed: missing dependency future, large amount of backtrace output - while the interface fails to display. Pending for next week.

Update:
Missing dependency `future` and plugin `ip` malfunctioned.

**Comment by MingcongBai** [comment]
Glances is fixed in `3.1.1-1`, delayed to the next queue.

**Comment by MingcongBai** [comment]
All tested packages are merged with `stable`.

**Comment by MingcongBai** [comment]
Superseded by https://github.com/AOSC-Dev/aosc-os-abbs/issues/1963. Closing.
