### ISSUE TITLE
Build .NET Core from source

### ISSUE THREAD

**Issue by KexyBiscuit** [AOSC-Dev/aosc-os-abbs#1943]
## See Also

- ~~[Build .NET Core from source](https://docs.microsoft.com/en-us/dotnet/core/build/)~~
- [.NET distribution packaging](https://docs.microsoft.com/en-us/dotnet/core/distribution-packaging)
- [.NET Core Build Scripts](https://github.com/dotnet/source-build)

**Comment by MingcongBai** [comment]
@liushuyu Noted a reason for not moving there, yet. Would you mind elaborating here just for the record?

**Comment by KexyBiscuit** [comment]
Closing this for now, will revisit once I have more time...
