### ISSUE TITLE
umbrello 19.04.3, 19.08.0: FTBFS (explosive)

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/aosc-os-abbs#1949]
log: http://fars.ee/Cc1_

**Comment by LionNatsu** [comment]
Anything wrong in the CMake log? It looks pretty normal.

**Comment by eatradish** [comment]
Looks like AOSC OS has dropped this package

**Comment by KexyBiscuit** [comment]
Really?
https://github.com/AOSC-Dev/aosc-os-abbs/tree/explosive/extra-kde/umbrello still exists.

**Comment by eatradish** [comment]
Ok i confused this package with https://github.com/AOSC-Dev/aosc-os-abbs/issues/2050

**Comment by MingcongBai** [comment]
No longer reproducible. Closing.
