### ISSUE TITLE
Wishlist: Use some dynamic linking for Golang

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#195]
AFAIK gccgo can do some dynamic linking, and it works fine. Not sure about how offical Go works though.

This actually comes from a part of my chat on TUNA:

> My worst experience with Golang is that..
> When I searched for ways to reduce the static binary size, I was expecting something like Dead Code Elimination...
> But the only sound solution I found was to use `goupx`, which is actually a tool to patch the ELF headers to make UPX happy.
> 
> And I figured out the ELF part only after spending 20 minutes compiling the damn thing only to get an error with my Win64-PE/COFF binary.

**Comment by MingcongBai** [comment]
We will include `gccgo` as a part of Core 4.1, might be a good start.

**Comment by MingcongBai** [comment]
It should be doable now with CGO...
