### ISSUE TITLE
[RFC] Allow newly introduced package to enter stable-proposed and then stable if possible

### ISSUE THREAD

**Issue by Icenowy** [AOSC-Dev/aosc-os-abbs#1952]
As new packages usually do not affect the dependency tree that already exists (except if it needs changes of configurations of some dependencies, which is a rare condition), we should be able to put them into stable as soon as possible to satisfy the need of users.

Considered roadmaps of new packages to enter stable:
- Directly enter stable-proposed, then stable after tested.
- Enter explosive-testing first, then backport to stable.

**Comment by MingcongBai** [comment]
We are now using [topic-based maintenance "cycles"](https://wiki.aosc.io/developer/packaging/topic-based-maintenance-guideline/). Closing.
