### ISSUE TITLE
pakreq: nnn

### ISSUE THREAD

**Issue by jarun** [AOSC-Dev/aosc-os-abbs#1955]
This is a request to package `nnn` - a full-featured file manager for low-end devices and the regular desktop.

Homepage: https://github.com/jarun/nnn

Would highly appreciate if `nnn` can be added to AOSC OS.

**Comment by eatradish** [comment]
Now, `nnn 2.6`  has entered the testing branch, request your test.

**Comment by jarun** [comment]
Thank you!

Can you please let me know the steps to test it if I download the Base flavour of AOSC?

How do I add the testing branch and install the package from there?

**Comment by MingcongBai** [comment]
@jarun 

The "Base" variant can be obtained [here](https://releases.aosc.io/os-amd64/base/aosc-os_base_20190722_amd64.tar.xz), assuming that you are using an AMD64 PC. Then, deploy the system according to our [Wiki](https://wiki.aosc.io/users/installation/amd64).

From there, execute the following command to enable Testing:

```
# apt-gen-list b testing
# apt update
```

**Comment by jarun** [comment]
Thank you!

**Comment by MingcongBai** [comment]
Introduced with 40f66f07475d446d61368c854868b4d92d9dc335. Closing.
