### ISSUE TITLE
fontconfig: {firefox,chromium} open quora font problem

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/aosc-os-abbs#1956]
I tried to open quora and found that the font rendering was terrible.

Their font-family looks like this:
```
Georgia,Times,"Times New Roman","Hiragino Kaku Gothic Pro","Meiryo",serif
```
I found that I didn't change the Georgia font from CSS. I noticed a change when I deleted Times.

After that, I turned on the chromium and did the same thing. I found the behavior even more strange. I deleted the `q_serif` loaded by chromium and it fallback to serif.

I have two Problem:

- Why are some fonts that don't match? For example, `Georgia` in Firefox, fonts other than serif in chromium
- Why is the rendering of `Times` fonts so bad?

**Comment by MingcongBai** [comment]
> Why are some fonts that don't match? For example, in Georgia, in Firefox, fonts other than serif in chromium

Chromium has always had the problem with inconsistent font rendering when compared with Firefox, and really, the whole system.

> Why is the rendering of Times fonts so bad?

The "Times" fonts that came with `x11-font` are bitmap fonts. What does "Times" match to in your system? For mine, it matches with "Noto Serif CJK SC Regular" in a `zh_CN.UTF-8` locale configuration:

```
mingcongbai@jelly-a1502 [ ~ ] $ fc-match Serif
NotoSerifCJK-Regular.ttc: "Noto Serif CJK SC" "Regular"
```

When using `C.UTF-8`...

```
mingcongbai@jelly-a1502 [ ~ ] $ env LANG=C.UTF-8 fc-match Serif
NotoSerif-Regular.ttf: "Noto Serif" "Regular"
```

**Comment by eatradish** [comment]
![Screenshot_20190812_225854](https://user-images.githubusercontent.com/19554922/62875223-39235f00-bd55-11e9-9daf-22ea0c6ca49f.png)

This is a list of installed fonts

**Comment by MingcongBai** [comment]
Does this file exist for you? `/etc/fonts/conf.d/66-google-noto-serif.conf`

**Comment by eatradish** [comment]
> Does this file exist for you? `/etc/fonts/conf.d/66-google-noto-serif.conf`

```
sakiiily@eat-x220i [ ~ ] ! ll  /etc/fonts/conf.d/66-google-noto-serif.conf
lrwxrwxrwx 1 root root 39 Mar 26  2018 /etc/fonts/conf.d/66-google-noto-serif.conf -> ../conf.avail/66-google-noto-serif.conf
```

**Comment by eatradish** [comment]
I tried `dpkg --force-all -r x11-font` and found the problem. The poor rendering problem was solved.

This is the comparison of `fc-match`:
Before uninstalled:
```
sakiiily@eat-x220i [ ~ ] $ fc-match "Times"
timR12-ISO8859-1.pcf.gz: "Times" "Regular"
```
After uninstalling:
```
sakiiily@eat-x220i [ ~ ] $ fc-match "Times"
LiberationSerif-Regular.ttf: "Liberation Serif" "Regular"
```

**Comment by MingcongBai** [comment]
Will add "Times" match for Noto Serif.

**Comment by MingcongBai** [comment]
Correction: Liberation Serif.

**Comment by MingcongBai** [comment]
Correction again: will install `70-no-bitmaps` to `/etc/fonts/conf.d` by default.

**Comment by MingcongBai** [comment]
@eatradish Fixes committed. Please look out for the following updates:

- fontconfig v2.13.0-3
- liberation-fonts v2.00.5

**Comment by MingcongBai** [comment]
No longer reproducible (addressed with updates above). Closing.
