### ISSUE TITLE
Cairo: Go Infinality? (Partially)

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#196]
Out of curiousity I looked at the patches applied in https://aur.archlinux.org/cgit/aur.git/tree/?h=cairo-infinality-lcdfilter.

It appears that all of the patches, except the "server side gradients" one, make lots of sense. I haven't seen any reports of "gradients" failing yet so I don't think it's necessary to add that particular patch.

By the way, where's `FT_LOAD_COLOR`?

**Comment by MingcongBai** [comment]
> Out of curiousity I looked at the patches applied in https://aur.archlinux.org/cgit/aur.git/tree/?h=cairo-infinality-lcdfilter.

Largely effective as I can see.

> By the way, where's `FT_LOAD_COLOR`?

It's an one-line patch is it not?

**Comment by MingcongBai** [comment]
Closing with commit above.
