### ISSUE TITLE
nodejs: unusable on NVIDIA Jetson TX1 Developer Kit in AArch32 state

### ISSUE THREAD

**Issue by KexyBiscuit** [AOSC-Dev/aosc-os-abbs#1960]
Bug description & Reproducing steps
-----------------------

```shell
$ node --help
Illegal instruction
```

Update channel(s)
--------------------------

Stable

Package and version
------------------------------

```shell
Package: nodejs
Status: install ok installed
Section: devel
Installed-Size: 748184
Maintainer: Kexy Biscuit <kexybiscuit@aosc.io>
Architecture: armel
Version: 2:10.16.3
Depends: python-2 (>= 2.7.16-2), zlib (>= 1.2.11), icu (>= 58.2-6)
Description: A JavaScript runtime built on the V8 JavaScript engine
```

**Comment by Icenowy** [comment]
what device and kernel are you using?

**Comment by KexyBiscuit** [comment]
[NVIDIA Jetson TX1 Developer Kit](https://developer.nvidia.com/embedded/jetson-tx1-developer-kit) with [L4T](https://developer.nvidia.com/embedded/linux-tegra) kernel. It's the "Tegra" build agent owned by @MingcongBai.

```shell
# uname -r
4.4.38-aosc-l4t
```

**Comment by KexyBiscuit** [comment]
Can't repro on other devices, what's worse is the problem can't be reproed even on tx1, all commands now returns SIGSEGV. Moving to backlog.

**Comment by KexyBiscuit** [comment]
Might be Tegra specific problem, .NET Core also crashes immediately.

**Comment by MingcongBai** [comment]
Device dead... Closing. Issue could be used for future reference.
