### ISSUE TITLE
kde: cannot find trackpad correctly

### ISSUE THREAD

**Issue by Plectranthus-fg** [AOSC-Dev/aosc-os-abbs#1962]
Bug description
-----------------------
Cannot find trackpad correctly (other DE can find the touchpad）

Update channel(s)
--------------------------

Testing

**Comment by Plectranthus-fg** [comment]
![image](https://user-images.githubusercontent.com/37979371/63207511-b0b10f80-c102-11e9-9e16-3b271bd397d0.png)

**Comment by LionNatsu** [comment]
Have the issue fixed?

**Comment by eatradish** [comment]
> Have the issue fixed?

yep, Closing.
