### ISSUE TITLE
KDE 5 and Intel Graphics: Random Freezes

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#197]
Well this seems to be a widespread issue. First experienced on AOSC OS3, now also on Arch Linux.

External references:
https://bugs.kde.org/show_bug.cgi?id=338999
https://bugs.launchpad.net/kubuntu-ppa/+bug/1384512
https://forums.opensuse.org/showthread.php/510662-KDE5-freezing-randomly
http://news.softpedia.com/news/critical-intel-graphics-driver-bug-puts-kde-plasma-5-in-a-really-bad-light-488621.shtml

**Comment by butangmucat** [comment]
Softpedia provided a workaround from Manjaro, untested:

`Section "Device"
        Identifier  "Intel Graphics"
        Driver      "intel"
        Option      "AccelMethod"  "uxa"
EndSection`

**Comment by butangmucat** [comment]
OK this will crash the whole X11.

**Comment by butangmucat** [comment]
KDE upstream has marked wontfix, probably xf86-video-intel related?

**Comment by butangmucat** [comment]
@bobcao3 seems to have similar issues

**Comment by MingcongBai** [comment]
Please re-open if you could still reproduce this.

**Comment by bobcao3** [comment]
The problem still exist, the occasion when it froze is diminished. I think the bug is on the whole i915/dri stack. The bug is hard to track and seemed no one in i915/dri care that bug.
