### ISSUE TITLE
i2pd: update to 2.28.0

### ISSUE THREAD

**Issue by r4sas** [AOSC-Dev/aosc-os-abbs#1984]
Current version in repository (2.23.0) is outdated.
Please update package to 2.28.0, because here was few network changes that are preferred to have, like using new transport protocol NTCP2 as default, new signature types and protocols bugfixes.

https://github.com/PurpleI2P/i2pd/releases/tag/2.28.0

**Comment by MingcongBai** [comment]
Addressed with bf4ea5d8f6b9c896f0db480d0c46400d956d58be. Closing.
