### ISSUE TITLE
ca-certs:  vision:20190820-x unusable

### ISSUE THREAD

**Issue by Plectranthus-fg** [AOSC-Dev/aosc-os-abbs#1985]
Bug description
-----------------------

after upgrade to vision 20190820-x, ca-certs is invalid.

Reproducing steps
---------------------------

upgrade to 20190820-x

Update channel(s)
--------------------------

stable-proposed

Package and version
------------------------------

ca-certs/stable-proposed 20190820-2 all 
ca-certs/stable-proposed 20190820-1 all
ca-certs/stable-proposed 20190820 all

**Comment by eatradish** [comment]
Fixed with `ca-certs/stable-proposed 20190820-3 all` , Closing.
