### ISSUE TITLE
ceph: FTBFS on PowerPC 64-bit

### ISSUE THREAD

**Issue by KexyBiscuit** [AOSC-Dev/aosc-os-abbs#2017]
Bug description
-----------------------

Before: [acbs-build_hxxg3sc9.log](https://github.com/AOSC-Dev/aosc-os-abbs/files/3634326/acbs-build_hxxg3sc9.log)
After 45bd930: [acbs-build_v981_s6h.log](https://github.com/AOSC-Dev/aosc-os-abbs/files/3634524/acbs-build_v981_s6h.log)

Reproducing steps
---------------------------

Build `ceph` on PowerPC 64-bit.

Update channel(s)
--------------------------

Stable

Package and version
------------------------------

45bd930

**Comment by KexyBiscuit** [comment]
805ba9a fixes some but not all problems.

**Comment by KexyBiscuit** [comment]
As #1997, Ceph will be dropped this iteration. Closing.

**Comment by LionNatsu** [comment]
Besides #2027, there is something more.
Long story short, neither PowerPC nor PPC64 is supported by [**nodeenv**](https://github.com/ekalinin/nodeenv/blob/e0914ddcd4e051243eca48403f32607f5e910ed5/nodeenv.py#L508-L518) which is wanted by [/src/pybind/mgr/dashboard/CMakeLists.txt](https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/CMakeLists.txt).

Question: is there any flag to work around the nodeenv? If there isn't, the solution will be rather straightforward: turn off `WITH_MGR_DASHBOARD_FRONTEND` (default: ON)

**Comment by MingcongBai** [comment]
`ppc64be` is now a Retro port. Closing.
