### ISSUE TITLE
ruby: update to 2.3.0

### ISSUE THREAD

**Issue by bobcao3** [AOSC-Dev/aosc-os-abbs#202]
Its upstream is already 2.3.0 for a long while
http://ftp.ruby-lang.org/pub/ruby/2.3/

**Comment by MingcongBai** [comment]
Give me two or three days... I will be updating Lua to 5.3 along with it.

**Comment by MingcongBai** [comment]
Well I guess I am doing this today... @bobcao3 was just going to make me do it.

**Comment by MingcongBai** [comment]
All done!
