### ISSUE TITLE
clp: FTBFS on AArch64 and Armv7-A

### ISSUE THREAD

**Issue by KexyBiscuit** [AOSC-Dev/aosc-os-abbs#2020]
Bug description
-----------------------

AArch64: [acbs-build_nxyv5qmj.log](https://github.com/AOSC-Dev/aosc-os-abbs/files/3635865/acbs-build_nxyv5qmj.log)

Armv7-A: [acbs-build_obmlxfv3.log](https://github.com/AOSC-Dev/aosc-os-abbs/files/3635866/acbs-build_obmlxfv3.log)

Reproducing steps
---------------------------

Build `clp` on AArch64 or Armv7-A.

Update channel(s)
--------------------------

Stable

Package and version
------------------------------

25a3d5c

**Comment by KexyBiscuit** [comment]
This blocks #1992 on AArch64.

**Comment by LionNatsu** [comment]
I don't know how this happened, and I guess it used incorrect header files. In the upstream zip package, besides Clp, I saw CoreUtils and Osi. It looks like a bundle. The "missing" member functions in both AArch64 and Armv7 cases can be easily found in directory "CoreUtils".

https://github.com/AOSC-Dev/aosc-os-abbs/blob/explosive/extra-scientific/clp/autobuild/build We build the top-level target.

It looks like a copy-and-paste from Arch coin-or-clp. However, Arch builds them seperately.
[coin-or-coinutils](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/coin-or-coinutils) <- [coin-or-osi](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/coin-or-osi) <- [coin-or-clp](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/coin-or-clp)

1. Are we taking a configure argument list written only for the Clp-level target and applying it to the top-level target? Could this cause the error?

2. What is the relationship between this and `coinutils`? There was a symbolic link https://github.com/AOSC-Dev/aosc-os-abbs/blob/c873fda7c9d8148e3ec2489dbdd73cb7c9556869/extra-scientific/coin-or-utils (2015, removed)

**Comment by LionNatsu** [comment]
FYI: the 2-level tree:
```
Clp-1.17.3
├── BuildTools
│   ├── compile_f2c
│   ├── headers
│   ├── MSVisualStudio
│   └── share
├── Clp
│   ├── doxydoc
│   ├── examples
│   ├── MSVisualStudio
│   ├── src
│   └── test
├── CoinUtils
│   ├── doxydoc
│   ├── MSVisualStudio
│   ├── src
│   └── test
├── Data
│   ├── Netlib
│   └── Sample
├── doxydoc
├── Osi
│   ├── doxydoc
│   ├── examples
│   ├── MSVisualStudio
│   ├── src
│   └── test
└── ThirdParty
    ├── ASL
    ├── Blas
    ├── Glpk
    ├── Lapack
    ├── Metis
    └── Mumps

```

**Comment by Icenowy** [comment]
The key is that coinutils should be updated. When the system has one copy, the bundled one seems to be ignored.

I have already finished the build (and LibreOffice included) on AArch64.

**Comment by LionNatsu** [comment]
@Icenowy So that's why it read an old definition. No wonder.

Thanks for the good news. Closing this.
