### ISSUE TITLE
xfce4-session: missing light-locker-command support in xflock4

### ISSUE THREAD

**Issue by Fearyncess** [AOSC-Dev/aosc-os-abbs#2021]
Bug description
-----------------------

The xfce-base in the tree has a light-locker dep but the xflock4 simple screensaver wrapper program has not "light-locker" support in it. It causes user can not directly use the "Lock" button provided by xfce4-session to lock the device quickly.

Reproducing steps
---------------------------

click Lock button in the xfce4's session dialog.

Update channel(s)
--------------------------

stable-proposed (maybe)

Package and version
------------------------------
xfce4-session: 1:4.12.1

**Comment by Fearyncess** [comment]
fixed in 4.14 and xfce 4.14 is in summer 2019

**Comment by MingcongBai** [comment]
As noted above. Closing.
