### ISSUE TITLE
it87: repository is gone

### ISSUE THREAD

**Issue by KexyBiscuit** [AOSC-Dev/aosc-os-abbs#2023]
Bug description
-----------------------

The SRCTBL in [spec](https://github.com/AOSC-Dev/aosc-os-abbs/blob/explosive/extra-kernel/it87/spec) returns 404, since the repository has been removed.

Reproducing steps
---------------------------

`curl https://github.com/groeck/it87/archive/v1.0.tar.gz`

Update channel(s)
--------------------------

Any

Package and version
------------------------------

6fd1f89

**Comment by KexyBiscuit** [comment]
The driver seems to be [in the mainline kernel](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/hwmon/it87?id=51b00d8509dc69c98740da2ad07308b630d3eb7d) (for some time).

**Comment by Garfield550** [comment]
I found a fork: https://github.com/a1wong/it87

**Comment by KexyBiscuit** [comment]
@MingcongBai ping?

**Comment by MingcongBai** [comment]
@KexyBiscuit This package has already been dropped (before the end of the last cycle), as it is now part of the mainline Kernel.

**Comment by KexyBiscuit** [comment]
Thanks for the clarification. Closing as resolved.
