### ISSUE TITLE
way-cooler: FTBFS

### ISSUE THREAD

**Issue by KexyBiscuit** [AOSC-Dev/aosc-os-abbs#2026]
Bug description
-----------------------

[acbs-build_2hie89z3.log](https://github.com/AOSC-Dev/aosc-os-abbs/files/3651058/acbs-build_2hie89z3.log)

`way-cooler` depends on `rlua`, which depends on `lua` v5.3, which isn't available.

Reproducing steps
---------------------------

Build `way-cooler`.

Update channel(s)
--------------------------

Stable-Proposed or Stable

Package and version
------------------------------

aceaadd951697c8fce18023180aaab4237a526a6, 45bd930b5022c3f926184d26af8f62e7a8806752

**Comment by MingcongBai** [comment]
Way Cooler stack was dropped earlier, as upstream ceased maintenance (3e482c0a6d71292cf4d7523c8c0171d19e6276a4). Closing.
