### ISSUE TITLE
ntfs-3g: include reparse point plugins

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#2029]
NTFS has a fancy feature called reparse point that serves as the basis for many of MS's backwards-compatible extensions to the filesystem. Jean-Pierre André from NTFS-3G provides three plugins to help us read some of these things:

* system compression: better readonly compression, used by some space-constrained installations
* file deduplication by chunk: used on some windows servers
* onedrive: it's onedrive

These fancy things are documented at https://jp-andre.pagesperso-orange.fr/junctions.html#other. The plugins are available at https://jp-andre.pagesperso-orange.fr/advanced-ntfs-3g.html#download. For the system-compression thing you should probably use the newer source at GitHub,

We can either just put these in the ntfs-3g package (they are tiny) or make three super small packages for them. I don't see them getting updated anytime soon so there's that.

**Comment by MingcongBai** [comment]
Addressed with #2882. Closing.
