### ISSUE TITLE
bash: pack examples as part of doc/

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#204]
Some scripts in examples are actually fun, e.g. http://git.savannah.gnu.org/cgit/bash.git/tree/examples/functions/autoload.v3.

(Well, this one can be modified slightly with the dict-as-a-set trick.)

**Comment by MingcongBai** [comment]
I will move this to https://github.com/AOSC-Dev/aosc-os-core.
