### ISSUE TITLE
linux-kernel: Refuse to generate GRUB menu on physical machine

### ISSUE THREAD

**Issue by misaka4e21** [AOSC-Dev/aosc-os-abbs#2044]
Bug description
-----------------------

Every time I upgrade linux-kernel, it will fail to regenerate grub entries, complaining "GRUB is not installed or in container/chroot, skipping regeneration of GRUB menu." Just like #636 

In the `postinst` script, however, a new method `systemd-detect-virt` has been used to detect chroot/container environments since acac7f70dc9d. It seems that it fixed #636.

But there still seems to be an error in the chroot/container env detection script, preventing `grub-mkconfig` from running.
https://github.com/AOSC-Dev/aosc-os-abbs/blob/stable/extra-kernel/linux-kernel/autobuild/postinst.in#L15-L27
```bash
if [[ -x /usr/bin/grub-mkconfig &&
    $_ret_chroot == 1 && $_ret_container == 1 ]]; then
	grub-mkconfig -o /boot/grub/grub.cfg
else
	echo "GRUB is not installed or in container/chroot, skipping regeneration of GRUB menu."
fi


if [[ -x /usr/bin/systemd-detect-virt ]]; then
	systemd-detect-virt --chroot 2>&1 > /dev/null
	_ret_chroot=$?
	systemd-detect-virt --container 2>&1 > /dev/null
	_ret_container=$?
fi
```
I think that the variable `_ret_chroot` and `_ret_container` were used before being assigned?
This problem was probably introduced in commit e1039d0ed42ab26f8a5414.

Reproducing steps
---------------------------

Upgrade linux+kernel (e.g. from 5.2.14 to 5.3.8)

Update channel(s)
--------------------------

stable.

Package and version
------------------------------
```
dpkg -s linux+kernel
Package: linux+kernel
Status: install ok installed
Section: kernel
Installed-Size: 44
Maintainer: Kexy Biscuit <kexybiscuit@aosc.io>
Architecture: all
Version: 2:5.3.8
Replaces: linux+image+new, linux+header+new, linux+image, linux+header, linux+image+old, linux+header+old
Provides: linux+image+new, linux+header+new, linux+image, linux+header, linux+image+old, linux+header+old
Depends: linux-kernel-5.3.8 (>= 5.3.8)
Description: The Linux Kernel for day-to-day desktop usage
```

**Comment by MingcongBai** [comment]
This has been addressed with the two commits above. Closing.
