### ISSUE TITLE
gwenview: broken dependency

### ISSUE THREAD

**Issue by misaka4e21** [AOSC-Dev/aosc-os-abbs#2045]
Bug description
-----------------------

gwenview: error while loading shared libraries: libKF5PurposeWidgets.so.5: cannot open shared object file: No such file or directory

Reproducing steps
---------------------------

Install gwenview and run it.

Update channel(s)
--------------------------

Stable

Package and version
------------------------------

```
dpkg -s gwenview 
Package: gwenview
Status: install ok installed
Section: kde
Installed-Size: 11112
Maintainer: Mingcong Bai <jeffbai@aosc.io>
Architecture: amd64
Version: 19.08.1
Replaces: kde-l10n (<= 16.12.3)
Depends: baloo (>= 5.62.0), kactivities (>= 5.62.0), kded (>= 5.62.0), kdelibs4support (>= 5.62.0), kimageformats (>= 5.62.0), libkdcraw (>= 19.08.1), libkexiv2 (>= 19.08.1), libkipi (>= 19.08.1)
Breaks: kde-l10n (<= 16.12.3)
Description: A fast and easy to use image viewer for KDE
```

**Comment by LionNatsu** [comment]
The fix is in the stable branch. Gwenview looks fine now.
