### ISSUE TITLE
pakreq: gh:sergev/bash-commander

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#205]
This is a funny extended version of bash,..

**Comment by MingcongBai** [comment]
Is this project ever going to have a tag?

**Comment by MingcongBai** [comment]
Stalled (feature/design change) issue, closing. Please open a new issue if this thought arises again. 

@Artoria2e5 Looks to have lost maintenance since 2019, also considering the slew of security vulnerabilities that have arisen since that time.
