### ISSUE TITLE
alpine: "patched" upstream ver

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#206]
The current upstream also provides a collection of patches on its site. A patched tarball is available at `http://patches.freeiz.com/alpine/patches/alpine-$VER/alpine-$VER.tar.xz`.

It might be desirable to check the `patchlevel` file for a sane PKGVER: `2.20.$(cat "$SRCDIR/patchlevel" || echo 0)`

**Comment by MingcongBai** [comment]
I've just realized that we are already using the "patched" version. I will have a look at the `patchlevel` file.

**Comment by Arthur2e5** [comment]
The one in /src/ is not "patched". (I am actually curious why the new upstream maintains 2 versions..)

**Comment by MingcongBai** [comment]
> The one in /src/ is not "patched". (I am actually curious why the new upstream maintains 2 versions..)

Just found out about it. BTW, patchlevel is 19.

**Comment by MingcongBai** [comment]
```configure: * * * SSL file "/etc/ssl/certs/factory.pem" is missing.
configure: * * *   This might indicate that CA certs did not get properly
configure: * * *   installed.  If you get certificate validation failures
configure: * * *   in Alpine, this might be the reason for them.```

Uh oh...
