### ISSUE TITLE
anthy: switch the upstream from Fedora to Debian

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#2065]
Issue description
-----------------------
Currently, we are using http://src.fedoraproject.org/repo/pkgs/anthy as the upstream of `anthy`, which is out of date.

Debian has taken over the repository years ago: https://salsa.debian.org/debian/anthy and it's under active development.

See also: https://wiki.debian.org/Teams/DebianAnthy

Package and version
------------------------------
`anthy` https://github.com/AOSC-Dev/aosc-os-abbs/blob/stable/extra-i18n/anthy/spec

!! Not the Modified Anthy (`anthy-ut`)

**Comment by MingcongBai** [comment]
Addressed with #2882. Closing.
