### ISSUE TITLE
scikit-sparse: wrong permissions

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#2066]
Bug description
-----------------------
https://packages.aosc.io/files/amd64/stable/scikit-sparse/0.4.4-2

Files in `/usr/lib/python2.7/site-packages/scikit_sparse-0.4.4-py2.7.egg-info/`
have `-rw------- 1 root root`.

Update channel(s)
--------------------------
Stable

Package and version
------------------------------
`scikit-sparse` 0.4.4-2

**Comment by eatradish** [comment]
Fixed with dd4ee8f, Closing
