### ISSUE TITLE
openjdk: "infinality" patches

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#207]
https://aur.archlinux.org/cgit/aur.git/tree/005_enable-infinality.patch?h=java8-openjdk

It actually looks like the patch does not require fc-infinality to me.

**Comment by MingcongBai** [comment]
It is already included since two updates ago. Thanks for telling us though.

**Comment by Arthur2e5** [comment]
Personally I would like to rename that patch to something like respect_fc_by_infinality_ppl

**Comment by MingcongBai** [comment]
Good point. There is a commit coming, doing that now.

**Comment by Arthur2e5** [comment]
May also want to change the macro names.

**Comment by Arthur2e5** [comment]
Bai, could you please confirm that https://bugs.archlinux.org/task/40871 is not happening on AOSC OS?

**Comment by MingcongBai** [comment]
![screenshot_20160422_105259](https://cloud.githubusercontent.com/assets/5006263/14748702/74b4e4ac-0878-11e6-8636-e6331aa22549.png)

**Comment by Arthur2e5** [comment]
Someone has mentioned a few Java options that made the problem show up on Arch. Can you test those too? Thanks.

**Comment by MingcongBai** [comment]
![screenshot_20160422_105839](https://cloud.githubusercontent.com/assets/5006263/14748831/30f8a9e6-0879-11e6-8070-c38b67f92dca.png)

It's all good here I think...

**Comment by Arthur2e5** [comment]
Then I should start an Arch openjdk7 bug too.

**Comment by MingcongBai** [comment]
Yep... I think that issue is effective mainly on JDK7.

**Comment by Arthur2e5** [comment]
.. or for the dark age when all sorts of important Infinality patches were not yet merged into FT

**Comment by MingcongBai** [comment]
Emm hmm.

**Comment by Arthur2e5** [comment]
OpenJDK guys are quite reluctant to changing this. Looks like I need to make a custom AUR build and prove the whole thing.

Time to get Hyper-V working.

**Comment by Artoria2e5** [comment]
Just saw a new commit on http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=2931. Remember to revert these or we will see a few regressions.

**Comment by Artoria2e5** [comment]
@Artoria2e5 @JeffBai （

**Comment by MingcongBai** [comment]
Interesting...

**Comment by MingcongBai** [comment]
Will take caution. Thanks.

**Comment by Artoria2e5** [comment]
(Um well, that came out a day after our release.)
