### ISSUE TITLE
latrace: FTBFS on stable, AMD64

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#2070]
Bug description
-----------------------
https://pastebin.aosc.io/paste/wppk7fsQMhxFGjwKLvL9QA
Blocked by an issue from https://github.com/AOSC-Dev/aosc-os-core/issues/75

Update channel(s)
--------------------------
Stable

Package and version
------------------------------
latrace 0.5.11

**Comment by MingcongBai** [comment]
Dropped in an upcoming PR. Closing.

**Comment by MingcongBai** [comment]
See #1389
