### ISSUE TITLE
amule: error while loading shared libraries libbfd-2.32.0.20190419.so

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/aosc-os-abbs#2072]
Bug description
-----------------------

```
➜  ~ amule
amule: error while loading shared libraries: libbfd-2.32.0.20190419.so: cannot open shared object file: No such file or directory
```

Update channel(s)
--------------------------

Testing-proposed

Package and version
------------------------------
```
➜  ~ apt show amule
Package: amule
Version: 1:2.3.2-5
Section: net
Maintainer: Mingcong Bai <jeffbai@aosc.io>
Installed-Size: 22.6 MB
Depends: binutils (>= 2.32-1), wxgtk (>= 2.8.12.1-8), libgd (>= 2.2.5-5), geoip-api-c (>= 1.6.12), libupnp (>= 1.6.20), crypto++ (>= 8.2.0), libwebp (>= 1.0.3), wx-base (>= 1)
Download-Size: 4337 kB
APT-Manual-Installed: yes
APT-Sources: https://repo.aosc.io/debs testing-proposed/main amd64 Packages
Description: An eMule-like client for ed2k network
```

**Comment by LionNatsu** [comment]
A rebuild should be enough.
https://packages.aosc.io/files/arm64/testing-proposed/binutils/2.33.1-1 **Library provides** `libbfd-2.33.1.20191220.so`

**Comment by eatradish** [comment]
> A rebuild should be enough.
> https://packages.aosc.io/files/arm64/testing-proposed/binutils/2.33.1-1 **Library provides** `libbfd-2.33.1.20191220.so`

But other Linux distributions doesn't depend `libbfd` (Debian, Arch Linux)

**Comment by LionNatsu** [comment]
They turned it off perhaps. Amule uses bfd to analyse its crash report, so it needs bfd naturally. Leave it be.

**Comment by eatradish** [comment]
> They turned it off perhaps. Amule uses bfd to analyse its crash report, so it needs bfd naturally. Leave it be.

(This is @MingcongBai )

I have been looking at this with @eatradish today, and I agree that `libbfd` is necessary (in Amule's case) to produce such crash report. However, this poses an issue whenever we update Core components - even the slightest bump to `binutils`'s version will lead to this particular issue.

I feel like this is some sort of "unnecessary trouble." Moreover, I seems that Arch Linux and Debian's binaries have no such dependency, but I couldn't find any relevant parameter/patch that could lead to this difference.

Just my two cents.

**Comment by LionNatsu** [comment]
No, it is not a slightest bump to binutils's version in practice. If the soname has a date part, every rebuild to the bfd is significant. QA should have addressed this issue. https://packages.aosc.io/qa/code/431/amd64/stable

> I couldn't find any relevant parameter/patch that could lead to this difference.

It needs more investigation indeed.

**Comment by LionNatsu** [comment]
It seems the rebuilding has solved the binutils API breakage. Further investigation of dependency policies goes on issue 2077.

**Comment by Artoria2e5** [comment]
I think we can cut the name part out and just use the rest of the soname. These people should have enough sensibility to commit a bump when they do break something, I hope

**Comment by LionNatsu** [comment]
Very true, libbfds with different names don't mean any incompatibility or API breakage. As a matter of fact, *the date part* comes with the version number we named it for a git checkout on the latest stable branch. We should address this as another issue for binutils.
