### ISSUE TITLE
binutils: libbfd-*.so.* file version problem

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/aosc-os-abbs#2082]
I noticed that the file names of our bindutils all have date names like `/usr/lib/libbfd-2.33.1.20191220.so`, which seems to cause some problems, such as https://github.com/AOSC-Dev/aosc-os-abbs/issues/2072 .

**Comment by MingcongBai** [comment]
Dropping shared libbfd in next Core patch release (forgotten).

**Comment by jiegec** [comment]
Done.
