### ISSUE TITLE
glibc: easily removable dependency for bash in glibc scripts

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#2088]
glibc's scripts all uses `#! /bin/bash` as the she-bang, to make use of the `$"msgid"` feature in bash.

Though such strings are non-POSIX (as in my memory) and may cause weird results, all the shells we provide plus busybox `ash` `hush` work well with the `$SHELL $(which ldd) /bin/bash` test. (zsh needs to `emulate -c sh` first, but it does it automatically when finding its `*argv` to be `(.*/)*sh`).

Therefore, it would be mostly safe to change it to `#!/bin/sh` so it can still go well without the `bash` dependency literally. However, I need someone to test if `LC_ALL=zh_CN.UTF-8 sh /bin/ldd` loses those gettext translations. If they are lost, we are not changing the shebang or we are making bugs.

Anyway, this may not be quite necessary for OS3 since we always have bash ready.

By the way, `ldd` in glibc2 supported `-V`, which does the same as `--version`. This can be easily implemented with in that `case` and maybe we can patch it in the same time, although there is no egg use.

**Comment by MingcongBai** [comment]
Stalled for over five years. It's best to leave this issue as-is, there is virtually no possibility of a non-Bash AOSC OS distribution/environment.
