### ISSUE TITLE
CPPFLAGS ?-> CXXFLAGS

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#209]
This mistake is seen in many of the solutions for #110. https://github.com/AOSC-Dev/aosc-os-abbs/search?p=1&q=CPPFLAGS&type=Code&utf8=%E2%9C%93 gives a lot of results.

**Comment by MingcongBai** [comment]
Okay... Let me go ahead and...

**Comment by KexyBiscuit** [comment]
Only 4 search results left, 2 are `unset`, 2 seems to be correct. Time to close this?

**Comment by Artoria2e5** [comment]
LGTM.
