### ISSUE TITLE
We should release unnecessary quotes in our lsb-release file in respect to * code written by careless guys.

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#2090]
See https://forge.univention.org/bugzilla/show_bug.cgi?id=37725#c5.

It's true that all we need is a segment of shell script that can get sourced by the shell script `lsb_release`, but many programmer, even those excellent ones writing code for [Python](https://bugs.python.org/issue1322) and [Deepin](https://cr.deepin.io/#/c/9023/1/systeminfo/distro.go) misses this point and only consider quotes for `DISTRIB_DESCRIPTION`.

**Comment by MingcongBai** [comment]
Stalled (feature/design change) issue, closing. Please open a new issue if this thought arises again.
