### ISSUE TITLE
GCC 10 now default to -fno-common which might break packaging

### ISSUE THREAD

**Issue by sztsian** [AOSC-Dev/aosc-os-abbs#2097]
Bug description
-----------------------
This is meant to be a tracker and reference.

GCC 10 now defaults to -fno-common.

https://gcc.gnu.org/gcc-10/changes.html

So if a package has variables with the same name in different object, when linking together ld will fail.

One valid but dirty workaround is to add `-z muldefs` in LDFLAGS.

Reproducing steps
---------------------------

Take trace-cmd 2.8.3 as an example

```
<mock-chroot> sh-5.0# make

... snip ...

  BUILD                  trace-cmd
/usr/bin/ld: /builddir/build/BUILD/trace-cmd-v2.8.3/tracecmd/trace-mem.o:/builddir/build/BUILD/trace-cmd-v2.8.3/tracecmd/trace-mem.c:33: multiple definition of `common_type_field'; /builddir/build/BUILD/trace-cmd-v2.8.3/tracecmd/trace-hist.o:/builddir/build/BUILD/trace-cmd-v2.8.3/tracecmd/trace-hist.c:30: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:60: /builddir/build/BUILD/trace-cmd-v2.8.3/tracecmd/trace-cmd] Error 1
make: *** [Makefile:273: trace-cmd] Error 2
<mock-chroot> sh-5.0# gcc --version
gcc (GCC) 10.0.1 20200130 (Red Hat 10.0.1-0.7)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Update channel(s)
--------------------------

N/A, of course we need to test in Explosive first.

Package and version
------------------------------

gcc 10

**Comment by jyhi** [comment]
Injecting `-fcommon` (overriding the default behavior) may also help.

**Comment by sztsian** [comment]
> Injecting `-fcommon` (overriding the default behavior) may also help.

Probably for other scenarios. But unfortunately it does not work for my scenario. Let keep it as a reference as well.

**Comment by MingcongBai** [comment]
Thanks for the note. We are now on GCC 10 as of Core 8, and as we comb through the tree with survey topics, we will fix them as we go along. Closing.
