### ISSUE TITLE
extra-creativity : Three more packages are needed

### ISSUE THREAD

**Issue by bobcao3** [AOSC-Dev/aosc-os-abbs#21]
K-3D : http://www.k-3d.org ( or Ayam http://ayam.sourceforge.net, in BSD Lisense)
Art of Illusion : http://www.artofillusion.org
LMMS : a musical software

**Comment by MingcongBai** [comment]
SourceForge is down currently...

**Comment by MingcongBai** [comment]
K-3D still needs ```libgnome```, seriously? I will not build this one, and not to other in here.

**Comment by MingcongBai** [comment]
LMMS, yes. AoI, not really...

**Comment by MingcongBai** [comment]
LMMS added to repository.
