### ISSUE TITLE
python-{2,3}: Use PGO (Profile Guided Optimization)

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#210]
This is a proposal made a long time ago (though not formally documented), we should enable PGO on our CPython interpreters, an optimization known to provide a considerable amount of performance gain.

Borrowing a screenshot from http://komodoide.com/blog/2014-06/python-pgo-on-linux/.

![2016-04-26 11-36-00](https://cloud.githubusercontent.com/assets/5006263/14828185/1bbc52e4-0ba3-11e6-8c9e-ff5e4aa17e5e.png)

A performance gain of 10-13% is observed from pyDes and pybench.

The main issue would be the adaptation of the "looped" build procedure necessary to carry out a profiled build. A `build` script might be needed for the time being.

**Comment by Arthur2e5** [comment]
Just a hacky idea in `autobuild3` usage: we can call `build_autotools_build` in `build.sh`.

**Comment by MingcongBai** [comment]
> Just a hacky idea in autobuild3 usage: we can call build_autotools_build in build.sh.

From `10-autotools.sh`? Well really we should be applying a PGO-like template to Autobuild3, as we do plan on widen PGO usage.

**Comment by MingcongBai** [comment]
Addressed. Closing.
