### ISSUE TITLE
xorg-server: add "dont force 96 dpi" patch

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#2101]
Bug description
-----------------------
xorg-server 1.7.0 broke its builtin detection of screen dpi by ignoring EDID information in favor of a default 96 dpi value. Whoever came up with this idea is drunk.

https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/589485

patch at https://gitlab.freedesktop.org/xorg/xserver/issues/253 / http://git.altlinux.org/gears/x/xorg-server.git?p=xorg-server.git;a=commitdiff;h=c5b77a90d7e0d6a1874fcb545969f355d1ed0293

Reproducing steps
---------------------------

I don't know, buy a 2014 display?

Update channel(s)
--------------------------

All

**Comment by MingcongBai** [comment]
It's funny how few people cared. I will try and patch against 1.20.9-2.

**Comment by MingcongBai** [comment]
Addressed with #2882. Closing.
