### ISSUE TITLE
 PPC64 upgrade from XFCE tarball fails as (what it seems) result of webkitgtk2

### ISSUE THREAD

**Issue by EchedelleLR** [AOSC-Dev/aosc-os-abbs#2106]
Bug description
-----------------------

In the "upgrade" step, following installation guide for powerpc, it seems that the same upgrade is being broken between gnome-online-accounts, webkitgtk and icu. It seems that gnome-online-accounts needs webkitgtk2 2.22.5 or higher but webkitgtk is only upgraded until 2.20 and icu breaks versions until 2.22.7.

Reproducing steps
---------------------------
Boot lubuntu-desktop image and follow the powermac installation steps with the PPC64 XFCE provided tarball until the "upgrade" one.

Update channel(s)
--------------------------

Stable ??

Package and version
------------------------------

Above provided.

**Comment by MingcongBai** [comment]
@EchedeyLR I’m really sorry but it might really be best if you could refrain from upgrading right this moment. We have been struggling to keep up with updates for this architecture and this is the result from that...

That said, we are not deprecating this port, but it will take some time before we are on sync again.

**Comment by EchedelleLR** [comment]
Well, since have been deprecated by Suse, Red Hat, Debian and followers I don't think I have so much to lose.

**Comment by EchedelleLR** [comment]
To add: is there any problem if I leave this issue opened just to see how evolves or there is another one to check that?

**Comment by MingcongBai** [comment]
@EchedeyLR Nope, please do leave this open... for a period of time the only customer for this port are the machines that builds these packages (PowerMac G5 Quads). Glad that someone’s picking it up and now (as I am really the sole advocate to keep this port alive here) there’s a legitimate reason to keep maintaining it.

**Comment by EchedelleLR** [comment]
WTF (sorry for saying it). I have no idea if I should be glad to catch this before (maybe) you are not going to support it or sad because (maybe) I am the only user and other people (with your exception) is not interested on this port.

I think (not sure) I could get a new machine since people here is not using some old iMacs. I got this one from one of these people who use to repair similar computers and I had been using it hardly with FreeBSD without hardware acceleration (only from powerpc 32 bits but in that version only ports were available), browser support (qutebrowser not working because of acceleration and disabling got crashed because of css and js) and without wifi (firmware or driver only available to build from ports to x86). Neither OpenBSD nor NetBSD didn't boot (crashed with the provided image) and Adelie Linux just got something working recently but also crashing a bit in the middle.

**Comment by MingcongBai** [comment]
> WTF (sorry for saying it).

No worries! As long as it's not a directed attack [we are all for expressive speech](https://wiki.aosc.io/users/guidelines/community-guidelines).

Back to your comments...

> I have no idea if I should be glad to catch this before (maybe) you are not going to support it or sad because (maybe) I am the only user and other people (with your exception) is not interested on this port.

I am not sure about how many users we have - we know it's not a large number regardless of the architecture. But I am personally a PowerPC/POWER hobbist and will do everything in my power to keep AOSC OS running on them.

> I think (not sure) I could get a new machine since people here is not using some old iMacs...

At this point though I should point out the challenges in maintaining this port - with the exception of POWER8/9 (little endian), it's safe to say that limitations and reliability issues are numerous on the PowerPC architecture. There is the lack of (usable) hardware acceleration on Radeon-based PowerPC Macs, there are issues with [colours in OpenGL applications](https://bugreports.qt.io/browse/QTBUG-56975).

The other challenge comes in the form of sheer computing power. I own two PowerMac G5 Quads and they are solely used for compiling packages and updates. Let's face it, they are barely faster than a higher end NetBurst-based Pentium D. It takes a lot of time to build stuff (~8-10 hours for Qt 5), and not to mention that upstreams don't tend to test their code on big endian architectures any more.

That said, I do have plans to mitigate this issue, and this will involve a plan called "AOSC OS/Retro", moving old architectures to a new release and maintenance system (as in planning and other criteria). A preliminary plan is to move `ppc32be` (G3, G4), `ppc64be` (G5), and add `i486` to the project, updating them on a semi-annual or annual schedule, and limiting the package selection. Desktop-enabled distributions will use (at least) IceWM, and (at most) XFCE.

I have many plans for it, and I can't wait to get started with the Retro project. Alas, I am only two months away from graduation and my senior thesis is biting hard. But for now, here's a little teaser...

![photo_2020-03-04_11-53-01](https://user-images.githubusercontent.com/5006263/75907875-b9eb9a80-5e0e-11ea-984f-085b5a9b4410.jpg)

**Comment by MingcongBai** [comment]
PPC64 is now an active Retro port, and distributions will be available in the near future. Closing.
