### ISSUE TITLE
An old experimental development branch of BIND has been shipped on stable

### ISSUE THREAD

**Issue by KexyBiscuit** [AOSC-Dev/aosc-os-abbs#2155]
Bug description
-----------------------

An old experimental development branch of BIND has been shipped on stable.

Reproducing steps
---------------------------

https://packages.aosc.io/packages/bind shows 9.15.6 is the latest version on all branches.

Update channel(s)
--------------------------

Stable

Package and version
------------------------------

N/A

**Comment by MingcongBai** [comment]
Done with #2156. Closing.
