### ISSUE TITLE
mutt, neomutt: security update to 1.14.4, 20200619

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#2201]
**CVE IDs:** TBD

**Other security advisory IDs:** N/A

**Description:**
https://github.com/neomutt/neomutt/releases/tag/20200619

> * Abort GnuTLS certificate check if a cert in the chain is rejected
> * TLS: clear data after a starttls acknowledgement
> * Prevent possible IMAP MITM via PREAUTH response

http://lists.mutt.org/pipermail/mutt-announce/Week-of-Mon-20200608/000022.html

> This is an important security release fixing two issues.
>
> The first is a possible IMAP man-in-the-middle attack.  No credentials 
are exposed, but could result in unintended emails being "saved" to an 
attacker's server.  The $ssl_starttls quadoption is now used to check 
for an unencrypted PREAUTH response from the server.

http://lists.mutt.org/pipermail/mutt-announce/Week-of-Mon-20200615/000023.html

> This is an important security release fixing a possible 
machine-in-the-middle response injection attack when using STARTTLS with 
IMAP, POP3, and SMTP.  (For packagers, I've requested a CVE and will 
update the website when I have the number).

**Architectural progress (Mutt):**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`

**Architectural progress (NeoMutt):**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`

**Comment by MingcongBai** [comment]
All done. Closing.

@l2dy Please assign an AOSA.

**Comment by l2dy** [comment]
Use AOSA-2020-0144.
