### ISSUE TITLE
poedit: debundle deps and check PKGDEP completeness

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#221]

**Comment by MingcongBai** [comment]
I do believe they are all debundled...

**Comment by Arthur2e5** [comment]
ICU and db appear missing in PKGDEP.

**Comment by MingcongBai** [comment]
> ICU and db appear missing in PKGDEP.

`icu` is pulled in as dependency of `harfbuzz` anyways; `db`, too, is pulled in by lower dependency levels.
