### ISSUE TITLE
libgdiplus: cairo impl does not consider fc fallbacks; --with-pango may be a fix

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#224]
See https://bugzilla.xamarin.com/show_bug.cgi?id=39418.

@farseerfc asked about using Chinese fonts in C# apps, and our suggestion was `"Sans"`. Then he found out that all the fonts became tofu, so I went to luke libgdiplus and wrote this report.

Using pango may be a workaround since it considers fallbacks in its implementation of cairo interaction. I have not luked the source to see how libgdiplus uses pango and if that really works, but that's worth a try anyway.

Also consider applying this PR which fixes some bugs in libgdiplus with pango enabled: https://github.com/mono/libgdiplus/pull/39. (In GH PRs, a patch can be obtained by appending `.patch` to the link.)

**Comment by Arthur2e5** [comment]
Here is the testcase (modified version of Winforms Hello World):

```C#
using System;
using System.Drawing;
using System.Windows.Forms;
 
public class HelloWorld : Form
{
    static public void Main ()
    {
        Application.Run (new HelloWorld ());
    }
 
    public HelloWorld ()
    {
        Button b = new Button ();
        b.Text = "Click Me! 我是方框。";
        b.Font = new Font("Sans", b.Font.Size);
        b.Click += new EventHandler (Button_Click);
        Controls.Add (b);
    }
 
    private void Button_Click (object sender, EventArgs e)
    {
        MessageBox.Show ("Button Clicked!");
    }
}
```

**Comment by MingcongBai** [comment]
Will do in about 9 hrs. And I will report back with screenshots of runtime.

**Comment by Arthur2e5** [comment]
Oh, and you may want to take this patch: https://bazaar.launchpad.net/~ubuntu-branches/ubuntu/wily/libgdiplus/wily/view/head:/debian/patches/initialize_png_transparency.patch

**Comment by MingcongBai** [comment]
> Here is the testcase (modified version of Winforms Hello World):

Your file does not seem to compile...

```
jeffbai [ ~ ] $ mcs test.cs -pkg:dotnet
test.cs(16,18): error CS1502: The best overloaded method match for `System.Drawing.Font.Font(string, float)' has some invalid arguments
/usr/lib/mono/4.5/System.Drawing.dll (Location of the symbol related to previous error)
test.cs(16,42): error CS1503: Argument `#2' cannot convert `System.Drawing.FontStyle' expression to type `float'
Compilation failed: 2 error(s), 0 warnings
```

**Comment by Arthur2e5** [comment]
Hmm, it wants a number? Say 11.

**Comment by MingcongBai** [comment]
Revised source.

```csharp
using System;
using System.Drawing;
using System.Windows.Forms;

public class HelloWorld : Form
{
    static public void Main ()
    {
        Application.Run (new HelloWorld ());
    }

    public HelloWorld ()
    {
        Button b = new Button ();                                                                       
        b.Text = "我是方框。";                                                                          
        b.Font = new Font("Sans", 11);                                                                  
        b.Click += new EventHandler (Button_Click);                                                     
        Controls.Add (b);                                                                               
    }                                                                                                   
                                                                                                        
    private void Button_Click (object sender, EventArgs e)
    {
        MessageBox.Show ("Button Clicked!");
    }
}
```

And runs like so (pre-patch, pre-fix).
![screenshot_20160502_221315](https://cloud.githubusercontent.com/assets/5006263/14974521/1605c546-10b3-11e6-9011-38de1feb2dcf.png)

**Comment by MingcongBai** [comment]
Seems like it's okay here?

**Comment by Arthur2e5** [comment]
Run `fc-match 'Sans'` and make sure it's not anything CJK.

**Comment by MingcongBai** [comment]
It matches to Noto Sans CJK SC per my configuration... Well let me try matching that to Noto Sans.

**Comment by MingcongBai** [comment]
Okay, I got you.
![screenshot_20160502_222321](https://cloud.githubusercontent.com/assets/5006263/14974633/7d75db52-10b4-11e6-9b46-0b4444f96c0e.png)

**Comment by Arthur2e5** [comment]
\<ping\>

**Comment by MingcongBai** [comment]
With patches included (PR #38) and `--with-pango`.

![2016-05-05 21-27-45](https://cloud.githubusercontent.com/assets/5006263/15063550/57891ba6-1308-11e6-8caf-802333d29437.png)

May I close it with the next commit?

**Comment by MingcongBai** [comment]
Well obviously the "label" did not show properly...

**Comment by MingcongBai** [comment]
@Arthur2e5 Says "yes" so... wait for it.

**Comment by Artoria2e5** [comment]
@MingcongBai Please reconsider patching https://patch-diff.githubusercontent.com/raw/mono/libgdiplus/pull/39.patch.
