### ISSUE TITLE
fc: Wine Tahoma == Tahoma mapping

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#227]

**Comment by MingcongBai** [comment]
I've just removed the two fonts from Wine (unbelievably ugly)...

**Comment by Arthur2e5** [comment]
This is a mistake. Wine Tahoma's in-TTF name is just Tahoma.

**Comment by Arthur2e5** [comment]
> unbelievably ugly

Kill the bitmaps and they work and align.
