### ISSUE TITLE
libgdiplus: generic sans-serif not generic

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#237]
https://bugzilla.xamarin.com/show_bug.cgi?id=40795

**Comment by MingcongBai** [comment]
I need more information...

> This is like a follow-up for bug 40791, but for libgdiplus. By reading GdipGetGenericFont*() functions, one can get a list about what libgdiplus considers as "generic", and how different this is from system/fontconfig views:

Is this defined within libgdiplus source?

**Comment by Arthur2e5** [comment]
Yes. grep for GdipGetGenericFont.

**Comment by MingcongBai** [comment]
Okay. Is there a good test case for this issue?

**Comment by MingcongBai** [comment]
```c
GpStatus
GdipGetGenericFontFamilySansSerif (GpFontFamily **nativeFamily)
{
        const WCHAR MSSansSerif[] = {'M','S',' ','S','a','n','s',' ', 'S','e','r','i','f', 0};
        GpStatus status = Ok;
        
        g_static_mutex_lock (&generic);

        if (ref_familySansSerif == 0)
                status = GdipCreateFontFamilyFromName (MSSansSerif, NULL, &familySansSerif);

        if (status == Ok)
                ref_familySansSerif++;
        else
                familySansSerif = NULL;
```

Weird... I am going to have an IB testing tomorrow morning so I am afraid that I must leave it here for the night. Thanks for the report.

**Comment by Arthur2e5** [comment]
For a test case, just replace `"Sans"` in #224 with `FontFamily.GenericSansSerif`. `FontFamily.GenericMonospace` might be easier to spot (this affects monospace too.)

**Comment by Artoria2e5** [comment]
Hmm, with this [fc bug](https://bugs.freedesktop.org/show_bug.cgi?id=95232) categorizing "MS Sans Serif" as a "sans-serif" (i.e. uses generic "sans-serif" fallback), fontconfig kind of masks this issue.

**Comment by MingcongBai** [comment]
Any more input here?

**Comment by Artoria2e5** [comment]
Use old patch suggestion (replace with 'S', 'a', 'n', 's', 0)

**Comment by MingcongBai** [comment]
Since https://github.com/mono/libgdiplus/pull/39 is already merged. Closing.
