### ISSUE TITLE
pakreq: haveged

### ISSUE THREAD

**Issue by Icenowy** [AOSC-Dev/aosc-os-abbs#240]

**Comment by Icenowy** [comment]
This is useful for headless usage, especially for ARM development boards, for they have few way to gain entropy.

**Comment by Icenowy** [comment]
If you are not sure, whether you need haveged, run:
```
# cat /proc/sys/kernel/random/entropy_avail
```
This command shows you how much entropy your server has collected. If it is rather low (<1000), you should probably install haveged. Otherwise cryptographic applications will block until there is enough entropy available, which eg. could result in slow wlan speed, if your server is a Software access point.

-- from ArchWiki

On my Allwinner A33 tablet, the value is usually less than 900.

**Comment by MingcongBai** [comment]
It's done a long time ago so... tada.
