### ISSUE TITLE
wxgtk{2,3}: missing tslib dependencies

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#246]

**Comment by bobcao3** [comment]
LMMS is also missing tslib.

**Comment by liushuyu** [comment]
Not only LMMS, it is Qt actually.

**Comment by bobcao3** [comment]
Maybe it's wxQt instead of Qt

**Comment by liushuyu** [comment]
If LMMS is really affected, then it will be pure Qt…… And Qt is rely on that to provide touch support
