### ISSUE TITLE
mpv 0.17.0: missing tslib dependencies

### ISSUE THREAD

**Issue by netarmy** [AOSC-Dev/aosc-os-abbs#247]
```
user [ ~ ] $ mpv
mpv: error while loading shared libraries: libts-1.0.so.0: cannot open shared object file: No such file or directory
user [ ~ ] ? sudo apt install tslib
......
Unpacking tslib (1.1) ...
Setting up tslib (1.1) ...
user [ ~ ] $ mpv
mpv 0.17.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Tue Apr 12 08:40:08 MDT 2016
```

#246

**Comment by MingcongBai** [comment]
Still, a bug that's introduced by `qt-5`. I will sort this out hopefully this weekend, graduating tomorrow LOL...

**Comment by liushuyu** [comment]
>I will sort this out hopefully this weekend

It seems your week is longer than us human on the earth……

**Comment by MingcongBai** [comment]
Let's say the Internet connection was worse than expected on the way LOL...

**Comment by Icenowy** [comment]
abbs 应该加入接入 proxychains4 功能

**Comment by MingcongBai** [comment]
But still, this is an issue on `qt-5` and nowhere else, I will sort it out with the Qt 5.6.1 update.
