### ISSUE TITLE
What are your plans for the Pale Moon package?

### ISSUE THREAD

**Issue by zqqw** [AOSC-Dev/aosc-os-abbs#2518]
Dear AOSC, apologies if this is not the correct place to make this enquiry, but I didn't see any contact email or similar on your website.
There is a link on the Pale Moon website that now gives a 404:
https://www.palemoon.org/contributed-builds.shtml
https://github.com/AOSC-Dev/aosc-os-abbs/tree/testing/extra-web/palemoon
Searching this repo on GitHub doesn't find anything. I did find some packages here:
https://packages.aosc.io/packages/palemoon
but the latest version there is 28.13.0, while the current version of Pale Moon is 28.15.0, and the link on that page to the source also does not return anything.
Pale Moon recently moved from Git Hub (which perhaps confused your build process if it is automated ?) :
https://repo.palemoon.org/MoonchildProductions

This question occurred while updating the Pale Moon website:
https://repo.palemoon.org/MoonchildProductions/www.palemoon.org/pulls/9
So do you plan to resume packaging Pale Moon in future or has the package been dropped, and the link should be removed ?

**Comment by Cyanoxygen** [comment]
Hi zqqw,
Thank you for your notice! We have [switched to a topic-based iteration plan](https://wiki.aosc.io/developer/packaging/topic-based-maintenance-guideline/), so the old iteration cycle was dropped, old branches (`testing`, `testing-proposed`, `stable-proposed`) are merged to `stable` and removed. Everything is done under the `stable` branch once a topic is finished. And we are sorry for not informing you to modify the source link when we switching the iteration cycle.
As you mentioned, our palemoon source link on your website is now outdated, but we are still maintaining this package. Our Packages site can track for the new version, but the update process is artificial. 
The source link can now point to the `stable` branch as the old `testing` branch is no longer exists: https://github.com/AOSC-Dev/aosc-os-abbs/tree/stable/extra-web/palemoon
As for the latest version, I'm going to create a topic to update the package.

Thanks,
Cyan

**Comment by zqqw** [comment]
That's great news, thank you.
