### ISSUE TITLE
lurch / libomemo: 12-byte IVs patch

### ISSUE THREAD

**Issue by Neustradamus** [AOSC-Dev/aosc-os-abbs#2568]
Hello @AOSC-Dev,

Here:
- https://github.com/AOSC-Dev/aosc-os-abbs/tree/stable/extra-web/lurch

Can you add the missing 12-byte IVs patch:
- https://github.com/gkdr/libomemo/pull/27

Explanation:
- https://github.com/gkdr/libomemo/issues/24

Thanks in advance.

**Comment by Fearyncess** [comment]
XEP doesn't recommend use 12-bytes IV.
https://github.com/xsf/xeps/pull/894#issuecomment-596255509
https://github.com/xsf/xeps/pull/903

**Comment by Neustradamus** [comment]
@fearyncess: The upstream is now good like all other OMEMO XMPP clients.
Please update it to libomemo 0.7.0.

Can you reopen this ticket, close only when it will be good?

Thanks in advance.

**Comment by Fearyncess** [comment]
AOSC doesn't have libomemo. It only have lurch. The lurch isn't updated.
And more, the XMPP clients almost can be compatible with 16bytes IV, except chatsecure. I think it needn't to change this for only chatsecure, even the 12bytes IV may has the security problem.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Neustradamus** [comment]
@fearyncess: Thanks for your comment :)

ChatSecure is good, there is a problem with Monal.
Please read all for explanation: https://github.com/gkdr/libomemo/pull/27
The problem is that there was not a XEP-0384 0.3.1 before 0.4.0 with this.
All clients send now with good 12-byte IV.

It is not possible to have separate libs like Debian for example?

At the same time, I have requested a 0.7.0 lurch build.

PS: You can always create a patch to have a perfect lurch because without, like currently, there is an incompatibility with other lurch and other clients.

**Comment by Neustradamus** [comment]
@fearyncess: Any news?
Thanks in advance.
