### ISSUE TITLE
multipath-tools: installed in wrong location

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#2592]
Bug description
-----------------------
There are

    /usr/bin/kpartx
    /usr/bin/multipath
    etc.

but also

    /usr/usr/include/libdmmp/libdmmp.h
    /usr/usr/lib/libmultipath.so
    etc.

Package and version
------------------------------
multipath-tools/stable,now 0.8.3-3 amd64

**Comment by MingcongBai** [comment]
Addressed with #2882. Closing.
