### ISSUE TITLE
lightdm: should start on TTY1

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#263]
This is a slight annoyance, LightDM starts in TTY7 while systemd shows all startup message on TTY1, this results in a brief display of the TTY login prompt on machines with slower storage I/O. Set LightDM to start on TTY1 should solve this issue.

**Comment by lmy441900** [comment]
I am just a little curious about how to set it...

**Comment by MingcongBai** [comment]
I am not sure either... But my initial investigation shows a source-level patch is needed.

**Comment by MingcongBai** [comment]
Found it. http://pkgs.fedoraproject.org/cgit/rpms/lightdm.git/tree/lightdm-1.18-fedora_config.patch#n8
