### ISSUE TITLE
radvd 2.19

### ISSUE THREAD

**Issue by Neustradamus** [AOSC-Dev/aosc-os-abbs#2695]
Dear @MingcongBai, @colin4124, @gumblex,

Can you update radvd to 2.19?
- https://github.com/radvd-project/radvd
- https://github.com/radvd-project/radvd/releases
- https://github.com/radvd-project/radvd/releases/tag/v2.19
- https://github.com/AOSC-Dev/aosc-os-abbs/commits/stable/extra-network/radvd

Thanks in advance.

**Comment by liushuyu** [comment]
Thanks for the notification. We will be updating `radvd` pretty soon.

**Comment by Neustradamus** [comment]
@cthbleachbit and @MingcongBai: Thanks! :)

At the same time: Have you looked for PPP 2.4.9 (PR is here) and Dnsmasq 2.83?

**Comment by cthbleachbit** [comment]
I‘m handling dnsmasq in a second.

**Comment by MingcongBai** [comment]
@Neustradamus We were experiencing some failure with our authentication services that prevented me from uploading the packages. I have already build-tested the updates, and they will merge shortly.

**Comment by Neustradamus** [comment]
@cthbleachbit and @MingcongBai: Thanks! :)
