### ISSUE TITLE
Dnsmasq 2.84

### ISSUE THREAD

**Issue by Neustradamus** [AOSC-Dev/aosc-os-abbs#2729]
@cthbleachbit and @MingcongBai: Can you update to 2.84?
- http://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2021q1/014640.html

There was a bug in Dnsmasq 2.83, I have informed you here:
- https://github.com/AOSC-Dev/aosc-os-abbs/issues/2715#issuecomment-766280179

Thanks in advance.

**Comment by MingcongBai** [comment]
I'm on it.

**Comment by MingcongBai** [comment]
Done with #2730. Closing.

**Comment by Neustradamus** [comment]
@MingcongBai: Thanks! :)
