### ISSUE TITLE
Libgcrypt to 1.9.1

### ISSUE THREAD

**Issue by Neustradamus** [AOSC-Dev/aosc-os-abbs#2744]
Libgcrypt to 1.9.1:
- https://gnupg.org/software/libgcrypt/index.html

Here:
- https://github.com/AOSC-Dev/aosc-os-abbs/blob/stable/extra-libs/libgcrypt
- https://github.com/AOSC-Dev/aosc-os-abbs/blob/stable/extra-optenv32/libgcrypt+32

**Comment by MingcongBai** [comment]
Addressed with #2758 . Closing.
