### ISSUE TITLE
Libgpg-error to 1.41

### ISSUE THREAD

**Issue by Neustradamus** [AOSC-Dev/aosc-os-abbs#2745]
Libgpg-error to 1.41:
- https://gnupg.org/software/libgpg-error/index.html

Here:
- https://github.com/AOSC-Dev/aosc-os-abbs/blob/stable/extra-libs/libgpg-error
- https://github.com/AOSC-Dev/aosc-os-abbs/blob/stable/extra-optenv32/libgpg-error+32

**Comment by MingcongBai** [comment]
Addressed with dd7a8e6462ef0bbd4d90f9061b9b3dd57f4abe66. Closing.
