### ISSUE TITLE
m4: missing dep libsigsegv

### ISSUE THREAD

**Issue by Icenowy** [AOSC-Dev/aosc-os-abbs#281]

**Comment by lmy441900** [comment]
In Arch Linux Database:

>Dependencies (2)
>
>    bash
>    glibc

https://www.archlinux.org/packages/core/x86_64/m4/

**Comment by MingcongBai** [comment]
AMD64 has `libsigsegv` as a base library, which is optionally linked by both `m4` and `gawk` (which just had this dep added).

**Comment by MingcongBai** [comment]
Anyways, a missing dep.
