### ISSUE TITLE
pkgreq: rtl8812AU wireless module (dkms version)

### ISSUE THREAD

**Issue by liushuyu** [AOSC-Dev/aosc-os-abbs#284]
rtl8812AU chip is widely used in Chinese TP-LINK wireless cards, and it seems like Debian Raspberry Pi included this module in their packages here: https://github.com/diederikdehaas/rtl8812AU . This fork supposed to be support up to Linux kernel 4.7 .

**Comment by MingcongBai** [comment]
Fixed by ae391a5aab7e819ffd4ba6eea7be65d4b70411b9. Closing.
