### ISSUE TITLE
current 6-8-2020 kde image aarch64 rockpro64 pinebookpro

### ISSUE THREAD

**Issue by sabazk** [AOSC-Dev/aosc-os-abbs#2870]
kde plasma doesn't launch from sddm - blank screen or could not sync evironment to dbus in a small window in the corner
tried manual launch from console with wayland and X same result
tried commands below
To start Plasma with xinit/startx, append export DESKTOP_SESSION=plasma and exec startplasma-x11 to your .xinitrc file. If you want to start Xorg at login, please see Start X at login.
To start a Plasma on Wayland session from a console, run XDG_SESSION_TYPE=wayland dbus-run-session startplasma-wayland

**Comment by MingcongBai** [comment]
@javan-z Issue moved. In the future, please report AOSC OS issues here.

**Comment by Icenowy** [comment]
Could you check `journalctl -xrb` for any error?

**Comment by KexyBiscuit** [comment]
Images are no longer supported, closing for now.
