### ISSUE TITLE
man-db and info/dir generation optimize

### ISSUE THREAD

**Issue by Icenowy** [AOSC-Dev/aosc-os-abbs#291]
They will cost a lot of time.
On a SSD machine (RMBP 2013), it costs even more time than unpacking!
And it's also a disaster on non-x86 platforms.

**Comment by MingcongBai** [comment]
A slough of rebuilds incoming. I am tagging this longterm as we are not seeing this soon, due to obvious time and performance constrains (as most packages has man pages).

**Comment by MingcongBai** [comment]
Oh God damn it. `postinst` takes the actual trigger script instead of `mandb` commands. Taking off the longterm tag! I will fix that later tomorrow. Cheers.

**Comment by MingcongBai** [comment]
(I look stupid don't I...)

**Comment by lmy441900** [comment]
> (I look stupid don't I...)

:new_moon_with_face:

**Comment by MingcongBai** [comment]
Here's the plan. I will instead create a systemd unit, which will be run on timer. Also, the trigger that `man-db` provides will be removed.

No user visible changes should be observed.

**Comment by MingcongBai** [comment]
@MingcongBai @Icenowy
