### ISSUE TITLE
tree: import not-in-abbs-tree packages

### ISSUE THREAD

**Issue by Icenowy** [AOSC-Dev/aosc-os-abbs#294]
Now there're still some packages not in abbs tree.

We should either drop them or add them to tree.

(We can promise armel/arm64/mipsel ports have no out-of-tree packages, as they're all built from abbs tree, so we should only check amd64-only packages)

**Comment by MingcongBai** [comment]
Right... I should get on it soon. Sooner.

**Comment by MingcongBai** [comment]
`z*` all done.

**Comment by MingcongBai** [comment]
`y*` all done.

**Comment by MingcongBai** [comment]
`x*` all done.

**Comment by MingcongBai** [comment]
`w*` all done.

**Comment by MingcongBai** [comment]
`v*` all done.

**Comment by MingcongBai** [comment]
`u*` all done.

**Comment by MingcongBai** [comment]
Oh jeez...

**Comment by MingcongBai** [comment]
```bash
root [ repo@staging ] # find . -mindepth 1 -maxdepth 2 -type d | wc -l
3234
```

Still about 500 package away at this point.

**Comment by MingcongBai** [comment]
`t*` all done.

**Comment by MingcongBai** [comment]
`s*` all done.

**Comment by MingcongBai** [comment]
`r*` all done.

**Comment by MingcongBai** [comment]
`q*` all done.

**Comment by MingcongBai** [comment]
`p*` done.

**Comment by MingcongBai** [comment]
`o*` all done.

**Comment by liushuyu** [comment]
@MingcongBai How can you come to this conclusion? (

**Comment by MingcongBai** [comment]
@liushuyu I meant all packages started with an "o" are done.

**Comment by MingcongBai** [comment]
`n*` all done.

**Comment by MingcongBai** [comment]
`m*` all done.

**Comment by MingcongBai** [comment]
`l*` all done.

**Comment by MingcongBai** [comment]
`k*` all done.

**Comment by MingcongBai** [comment]
`j*` all done.

**Comment by MingcongBai** [comment]
`i*` all done.

**Comment by MingcongBai** [comment]
`h*` all done.

**Comment by MingcongBai** [comment]
`g*` all done. `lib*` now.

**Comment by MingcongBai** [comment]
`liba*` all done.

**Comment by MingcongBai** [comment]
`libb*` all done.

**Comment by MingcongBai** [comment]
`libc*` all done.

**Comment by MingcongBai** [comment]
`libd*` all done.

**Comment by MingcongBai** [comment]
`libe*` all done.

**Comment by MingcongBai** [comment]
`libf*` all done.

**Comment by MingcongBai** [comment]
`libg*` all done.

**Comment by MingcongBai** [comment]
`libh*` all done.

**Comment by MingcongBai** [comment]
`libi*` all done.

**Comment by MingcongBai** [comment]
`libk*` all done.

**Comment by MingcongBai** [comment]
`libl*` and `libm*` all done.

**Comment by MingcongBai** [comment]
`libn*` all done.

**Comment by MingcongBai** [comment]
`libo*` all done.

**Comment by MingcongBai** [comment]
`libp*` all done. I find my lack of Force disturbing.

**Comment by MingcongBai** [comment]
`libq*` all done.

**Comment by MingcongBai** [comment]
`libr*` all done.

**Comment by MingcongBai** [comment]
`libs*` all done.

**Comment by MingcongBai** [comment]
`libt*` all done.

**Comment by MingcongBai** [comment]
`libu*` all done.

**Comment by MingcongBai** [comment]
`libv*` all done (with no effort).

**Comment by MingcongBai** [comment]
`libw*` all done with no effort.

**Comment by MingcongBai** [comment]
`libx*` all done.

**Comment by MingcongBai** [comment]
`liby*` has nothing to do. So close.

**Comment by MingcongBai** [comment]
`libz*` has nothing to do either! All done! ABBS tree now contains all packages in the repository.

**Comment by lmy441900** [comment]
\o/

**Comment by Artoria2e5** [comment]
@lmy441900 Dup of an old issue.

**Comment by MingcongBai** [comment]
Oh yes, almost forgot.

**Comment by LionNatsu** [comment]
Where is package `geoip`?

**Comment by LionNatsu** [comment]
@LionNatsu @JeffBai
