### ISSUE TITLE
fontforge: themes and l10n data not installed

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#298]
As kindly pointed out by @gumblex.

**Comment by MingcongBai** [comment]
Weird. Locale files were installed, but not used. Couldn't find a setting entry for languages either.

**Comment by MingcongBai** [comment]
Still couldn't find the culprit.

**Comment by LionNatsu** [comment]
Still in English. I cannot find any language settings.

**Comment by MingcongBai** [comment]
This was resolved with #2763 . Closing.
