### ISSUE TITLE
Request: new packages (RecordMyDesktop, Kazam, 0ad)

### ISSUE THREAD

**Issue by bobcao3** [AOSC-Dev/aosc-os-abbs#3]
RecordMyDesktop : http://sourceforge.net/projects/recordmydesktop
0ad ---- it's awesome ...

**Comment by bobcao3** [comment]
Well .. Kazman is better than RecordMyDesktop

**Comment by Arthur2e5** [comment]
```Bash
# translate https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/0ad
PKGNAME=0ad
PKGVER=0.0.18
PKGREL=4
PKGRECOM=0ad-data
PKGDEP='binutils boost-libs curl enet libogg libpng libvorbis gloox miniupnpc icu nspr'
export WX_CONFIG=/usr/bin/wx-config-2.8
ABTYPE=autotools
configure='./update-workspaces.sh'
AUTOTOOLS_AFTER='--with-system-miniupnpc --datadir=/usr/share/0ad/data'
# End of defines
# echo 'sed -i "s/env python/env python2/g" libraries/source/cxxtest-4.4/bin/cxxtestgen' > patch
# echo 'patch -Np1 -i patches/0001-9f24795fa4935aa1adcdea8c1008541011b3964f.patch' >> patch
# wget -O patches/0001-9f24795fa4935aa1adcdea8c1008541011b3964f.patch  https://projects.archlinux.org/svntogit/community.git/plain/trunk/9f24795fa4935aa1adcdea8c1008541011b3964f.patch?h=packages/0ad
```

**Comment by bobcao3** [comment]
。。→_→
You should teach me first......


来自 魅蓝

-------- 原始邮件 --------
发件人：Mingye Wang <notifications@github.com>
时间：周一 6月29日 09:42
收件人：AOSC-Dev/aosc-os-abbs <aosc-os-abbs@noreply.github.com>
抄送：bobcao3 <bobcaocheng@163.com>
主题：Re: [aosc-os-abbs] Need several packages (#3)

**Comment by MingcongBai** [comment]
(Why is wx-2.8 been used anyways)

I can certainly add them to the repo.

**Comment by MingcongBai** [comment]
@Arthur2e5 ```0.0.18``` as per say, but the source says ```0.0.18-alpha```, should we follow the upstream for it?

**Comment by MingcongBai** [comment]
@bobcao3 RecordMyDesktop is rather old now, and I don't think we should include that until the next tag.

**Comment by MingcongBai** [comment]
@bobcao3 kazam is now in the repository c262863b69339f302d0700fc3ec064dc4ba21ebb

**Comment by MingcongBai** [comment]
0ad is in. Closing.
