### ISSUE TITLE
Octave: dependencies broken

### ISSUE THREAD

**Issue by bobcao3** [AOSC-Dev/aosc-os-abbs#303]
bobcao3 [ ~ ] $ octave
/usr/lib/octave/4.0.2/exec/x86_64-unknown-linux-gnu/octave-gui: error while loading shared libraries: liboctgui.so.1: cannot open shared object file: No such file or directory
bobcao3 [ ~ ] ? find /usr/lib | grep liboctgui.so.1
/usr/lib/octave/4.0.2/liboctgui.so.1.1.0
/usr/lib/octave/4.0.2/liboctgui.so.1

**Comment by MingcongBai** [comment]
Try running `ldconfig`?

```
jeffbai [ ~ ] $ cat /etc/ld.so.conf.d/octave.conf 
/usr/lib/octave/4.0.2
```

That's meant to solve your issue.

**Comment by bobcao3** [comment]
Solved
