### ISSUE TITLE
Pakreq: FlightGear fgfs pkgreq

### ISSUE THREAD

**Issue by StephDC** [AOSC-Dev/aosc-os-abbs#304]
Requesting for FlightGear Flight Simulator

Btw is there already any games that I could use to test for joystick support?

**Comment by MingcongBai** [comment]
@StephDC SuperTuxKart should be a good bet.

**Comment by Icenowy** [comment]
Do you want to try RetroArch? (escape
2016年7月28日 下午12:57于 Steph de Los Estados Unidos <notifications@github.com>写道：Requesting for FlightGear Flight Simulator

Btw is there already any games that I could use to test for joystick support?

**Comment by tonghuix** [comment]
@StephDC please install the package `jstest-gtk`, you wold find it may help you test your joystick.
