### ISSUE TITLE
pakreq: PeaZip

### ISSUE THREAD

**Issue by Garfield550** [AOSC-Dev/aosc-os-abbs#306]
PeaZip is free file archiver utility, based on Open Source technologies of 7-Zip, p7zip, FreeArc, PAQ, and PEA projects.
Cross-platform, full-featured but user-friendly alternative to WinRar, WinZip and similar general purpose archive manager applications, works with 180+ archive formats: 001, 7Z, ACE, ARC, ARJ, BZ2, CAB, DMG, GZ, ISO, LHA, PAQ, PEA, RAR, TAR, UDF, WIM, XZ, ZIP ZIPX - view full list of supported file formats for archiving and extraction.

Released under Open Source (LGPLv3) license, free for any use, all versions of PeaZip are secure downloads and do not contain advertising or harmful software.

https://github.com/giorgiotani/PeaZip

**Comment by MingcongBai** [comment]
Right. Hopefully I can get that Lazarus deal sorted out.

**Comment by MingcongBai** [comment]
`peazip` is added to the tree with https://github.com/AOSC-Dev/aosc-os-abbs/commit/d342012fa2b916466fde56cc9be6e6c3e8bf990f, but it crashes when opening any archive, while decompressing them seems to work fine.

**Comment by MingcongBai** [comment]
This still won't work on a 64-bit build. Giving up.
