### ISSUE TITLE
pakreq: 王汉宗自由字体

### ISSUE THREAD

**Issue by Icenowy** [AOSC-Dev/aosc-os-abbs#308]
https://zh.wikipedia.org/wiki/%E7%8E%8B%E6%BC%A2%E5%AE%97%E8%87%AA%E7%94%B1%E5%AD%97%E5%9E%8B?wprov=sfla1

**Comment by MingcongBai** [comment]
Couldn't seem to find the upstream for it.

**Comment by tonghuix** [comment]
现在看来法律问题尚没有明了啊

**Comment by MingcongBai** [comment]
> 现在看来法律问题尚没有明了啊

"王漢宗自由字型由研发天蚕字库的台湾中原大学数学系王汉宗教授先分别在2000年和2004年先后捐出十套WCL系列字型和32套新字型，全部以GNU GPL許可分发。" https://zh.wikipedia.org/wiki/%E7%8E%8B%E6%BC%A2%E5%AE%97%E8%87%AA%E7%94%B1%E5%AD%97%E5%9E%8B

许可上倒是没有问题

**Comment by Icenowy** [comment]
另外就「隸書」、「仿宋」、等字型來說，文鼎公司也並非獨創，有許多字型公司的同名字型幾乎長得其實一模一樣。這麼一來其實很難說誰抄誰。不過，為了避免爭議，我們在此還是列出文鼎公司主張侵權的王漢宗字型供大家參考：
王漢宗中仿宋
王漢宗中仿宋簡體
王漢宗隸書體
王漢宗中明體
王漢宗粗明體
王漢宗特明體
王漢宗細圓體
王漢宗特圓體
王漢宗疊圓體
王漢宗勘亭流
王漢宗綜藝體
王漢宗中行書
王漢宗綜藝體雙空陰
王漢宗粗楷體簡體
文鼎公司主張以上王漢宗字型侵權，使用前請斟酌。其他部分的王漢宗字體則無爭議。

http://tips.justfont.com/post/113397509827/freeandcarefreefonts

**Comment by MingcongBai** [comment]
Oh...

**Comment by Icenowy** [comment]
https://code.google.com/archive/p/wangfonts/downloads is a rearranged version of the fonts...

**Comment by MingcongBai** [comment]
That works.

**Comment by MingcongBai** [comment]
Fixed with 83fdb62ccc40a7957b9e8c22b9ba451503e844de. Closing.
