### ISSUE TITLE
pakreq: apt-fast

### ISSUE THREAD

**Issue by gumblex** [AOSC-Dev/aosc-os-abbs#310]
[apt-fast](https://github.com/ilikenwf/apt-fast) is a shellscript wrapper for apt-get and aptitude that can drastically improve apt download times by downloading packages in parallel, with multiple connections per package.
GPLv3+

**Comment by MingcongBai** [comment]
I will pack this once I got the `apt` deal sorted out so I have a complete mirror list available for `apt-fast.conf`.
