### ISSUE TITLE
pakreq: libmaxminddb

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#314]
Library of the MaxMind DB format (mmdb) used by GeoIP2.

It also includes `mmdblookup`, which was `geoiplookup` in package `geoip-api-c`

https://github.com/maxmind/libmaxminddb

**Comment by MingcongBai** [comment]
`geoip-api-c` still provides `geoiplookup` though.

**Comment by LionNatsu** [comment]
Ummm, but how about the new package called libmaxminddb (or something else)?

They are the next generation of geoip-api-c.

**Comment by LionNatsu** [comment]
geoip-api-c -- GeoIP
libmaxminddb -- GeoIP 2
