### ISSUE TITLE
pax/grsecurity: prepare for support

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#322]
Several steps till we can declare PaX/Grsecurity supported by AOSC OS as a mainline technology add-on:
- [ ] Account for all declared in `pax-bites.conf` [here](https://github.com/AOSC-Dev/aosc-os-grsecurity-profile/blob/master/pax-bites.conf)
- [ ] Kernel import as tree package
- [ ] Testing and staging work

No details so far though, we should aim for the Christmas for this issue to finish.

**Comment by LionNatsu** [comment]
Especially, the KDE.
Do we need to check all the softwares of KDE? Are there a simple way to list them? (eg. special dependency?)

**Comment by biergaizi** [comment]
Christ...Christmas, death flag triggered :fearful:

**Comment by LionNatsu** [comment]
How about the new stuff in AutoBuild?
https://github.com/AOSC-Dev/aosc-os-abbs/wiki/Autobuild3#the-pax-file

`pax-bites.conf` should now be apply to each package (which is an elegant way) shouldn't it?

**Comment by Icenowy** [comment]
@LionNatsu it's not elegant at all.

**Comment by LionNatsu** [comment]
@Icenowy I mean, move *those options for each package* from pax-bites.conf into theirs package pax file.

**Comment by MingcongBai** [comment]
> @Icenowy I mean, move those options for each package from pax-bites.conf into theirs package pax file.

Could you explain a bit more on this?

**Comment by Icenowy** [comment]
@MingcongBai @Lionium I think it's good, but we should also keep a pax-bites.conf .

**Comment by LionNatsu** [comment]
@MingcongBai 
> Could you explain a bit more on this?

Cleanup options in `pax-bites.conf`, move it into packages' autobuild configuration.

e.g., delete this line:
```
/usr/bin/dolphin;m
```
then create `pax` file in `.../dolphin/autobuild/`(I guess.)
```
abpaxctl m /usr/bin/dolphin
```

**Comment by Icenowy** [comment]
@LionNatsu I will do the latter, but I disagree with the former

**Comment by MingcongBai** [comment]
> @LionNatsu I will do the latter, but I disagree with the former

A reasoning here would be nice.

**Comment by Icenowy** [comment]
@MingcongBai We have currently no way to bootstrap pax flags...

**Comment by Icenowy** [comment]
@MingcongBai Or maybe we should keep autobuild/pax file of every package at some location...

**Comment by LionNatsu** [comment]
Maybe a packages contains some scripts/configurations (or directory) to configure these flags? PaX/Grsecurity kernel depends on it, then we could do more around it? (I am not sure...)

**Comment by MingcongBai** [comment]
> Maybe a package contains some scripts/configurations (or directory) to configure these flags? PaX/Grsecurity kernel depends on it, then we could do more around it? (I am not sure...)

If we do have a way to detect problematic executables/libraries, even a `trigger` may be used for this purpose.

**Comment by LionNatsu** [comment]
Are there something new...? After the big news.

**Comment by Icenowy** [comment]
It's sorry that, at least from my own perspective of view, PaX/Grsecurity is no longer FLOSS. The last free version of it won't get update.

Things for PaX/Grsecurity in this repo, or in anywhere other of AOSC OS, should be dropped.
I may keep the pax bits, as they may someday play again after PaX things are merged into mainline.

If there's still something left, please leave an issue in this repository.

**Comment by Artoria2e5** [comment]
@Icenowy Free-ness or Kosher-ity should not be cited as a reason against packages width source code available and properly licensed (open source, that is). Just cite the actual problem: lack of access and support.
