### ISSUE TITLE
xrdp: compromised package containing private keys

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#3227]
**CVE IDs:** N/A

**Other security advisory IDs:** AOSA pending. @l2dy 

**Description:**

The `xrdp` package contains build-time generated `/etc/xrdp/cert.pem` and `/etc/xrdp/key.pem`, which are then shipped with every system distribution with this package installed. This compromises security by shipping identical private keys across multiple devices.

**Patches:** N/A

**Topic PR:** #3228

**Comment by MingcongBai** [comment]
All done. @l2dy Please assign an AOSA.

**Comment by l2dy** [comment]
Use AOSA-2021-0088.
