### ISSUE TITLE
linux-kernel: feature-univt.patch uses proprietary font

### ISSUE THREAD

**Issue by gumblex** [AOSC-Dev/aosc-os-abbs#323]
We found that the bitmap font used in [0000-feature-univt.patch](https://github.com/AOSC-Dev/aosc-os-abbs/blob/staging/extra-kernel/linux-kernel/autobuild/patches/0000-feature-univt.patch) is (almost) exactly the same as *SimSun 3.12*, which is a known proprietary-licensed Chinese font found in Windows XP. Using this font in the kernel is an obvious violation of the licenses, which must be corrected.

**Comment by MingcongBai** [comment]
This is indeed an unfortunate oversight we have taken earlier (if this is indeed true). You have discussed the possibility of replacing all type faces with the ones in Unifont, which certainly is clean license wise. Is it possible for you to produce a patch with the replaced font? It will be a great help...

**Comment by MingcongBai** [comment]
A new `fonts_utf8.h` has been made with a re-generated Unifont 9.0 font embedded, thanks to @gumblex .

[fonts_utf8.h.txt](https://github.com/AOSC-Dev/aosc-os-abbs/files/418215/fonts_utf8.h.txt)

Building a test kernel now.

**Comment by gumblex** [comment]
It seems fixed by using [these scripts](https://github.com/AOSC-Dev/scriptlets/tree/master/univt-fonts) to generate a new `fonts_utf8.h` with *Unifont 9.0.01*.

**Comment by MingcongBai** [comment]
> It seems fixed by using these scripts to generate a new fonts_utf8.h with Unifont 9.0.01.

Awesome, this has made it way easier for us to even update univt with Unifont updates! Thanks.
