### ISSUE TITLE
man-db: cannot clean cache correctly

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#328]
apt full-upgrade

```
Unpacking man-db (2.7.5-1) over (2.7.5) ...
dpkg: warning: unable to delete old directory '/var/cache/man': Directory not empty
```

**Comment by MingcongBai** [comment]
That should be an easy fix... I will just include that directory in the package then.

**Comment by MingcongBai** [comment]
But on the other hand, this should be an one-time warning, and you will not see this again on the next update.
