### ISSUE TITLE
spectacle: upgrade to v16.08.0

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#332]
Significant, upstream has FIXED the hotkey problem caused by invalid version number in `v16.04.2`, but ours is still stay on `v16.04.0`.

**Comment by MingcongBai** [comment]
I will update KDE Applications to 16.08.0 tonight. Opening a new issue for that now.

**Comment by LionNatsu** [comment]
Good, fixed.
