### ISSUE TITLE
pakreq: Yubico Yubikey supports

### ISSUE THREAD

**Issue by lmy441900** [AOSC-Dev/aosc-os-abbs#336]
This includes:

- [yubikey-personalization-gui](https://github.com/Yubico/yubikey-personalization-gui): Personalization tool for Yubikeys, including Yubico OTP, OATH-HOTP, Static Password, Challenge-Response, NDEF for NEO, etc. **(Update: front-end of yubikey-personalization)**
- [yubico-piv-tool](https://github.com/Yubico/yubico-piv-tool): Configure PIV (PKCS ＃11) mode of Yubikeys, in command line interface.
- [yubico-piv-manager](https://github.com/Yubico/yubikey-piv-manager): Configure PIV (PKCS ＃11) mode of Yubikeys, in graphical user interface, a front-end of yubico-piv-tool.
- [yubioath-desktop](https://github.com/Yubico/yubioath-desktop): A client to use Yubikeys' TOTP and HOTP feature to enable it to login websites configured with OTP 2FA.
- ~~[yubikey-manager](https://github.com/Yubico/yubikey-manager) **(BETA)**: An all-in-one configurator for Yubikeys, still in beta. Can ignore this package.~~

**Comment by lmy441900** [comment]
> We've got some other Yubico related packages as well

These are new packages, and existing packages are not shown here, but update checking might be needed.

> older versions simply won't work with new cards.

Just update to (or pack) the newest version.

**Comment by MingcongBai** [comment]
All done. Closing.
