### ISSUE TITLE
pakreq: pcap_dnsproxy

### ISSUE THREAD

**Issue by septs** [AOSC-Dev/aosc-os-abbs#337]
see https://github.com/chengr28/Pcap_DNSProxy

**Comment by septs** [comment]
default not "out of the box"
see https://github.com/chengr28/Pcap_DNSProxy/blob/master/Documents/ReadMe_Linux.zh-Hans.txt#L62-L71

**Comment by Artoria2e5** [comment]
The Linux install script is just setting up systemd stuff. The WorkingDirectory thing seems to assume some pretty BS (or java-ish) all-in-usr-share directory structure.

**Comment by MingcongBai** [comment]
> The Linux install script is just setting up systemd stuff. The WorkingDirectory description seems to assume some pretty BS (or java-ish) all-in-usr-share directory structure, while the binary doesn't seem to have to be put that way.

The most depressing fact about Electron.
