### ISSUE TITLE
pakreq: screenfetch

### ISSUE THREAD

**Issue by LER0ever** [AOSC-Dev/aosc-os-abbs#339]
[Github: KittyKatt/screenFetch](https://github.com/KittyKatt/screenFetch)  
Fetches system/theme information in terminal for Linux desktop screenshots.
(The tool for zhuangbility :)

**Comment by MingcongBai** [comment]
We will need to make a patch for our own logo though...

**Comment by LER0ever** [comment]
[http://www.ascii-art-generator.org/](http://www.ascii-art-generator.org/)
This can help generate a basic text logo

**Comment by gumblex** [comment]
@LER0ever Even GIMP supports that.

**Comment by MingcongBai** [comment]
I'll try to make a patch for them, and create a PR (packaging starts with PR creation, not sure if they will take it into the mainline though...).

**Comment by MingcongBai** [comment]
Still not done.

**Comment by LionNatsu** [comment]
Ping?

**Comment by liushuyu** [comment]
Alternative ready: `neofetch`
