### ISSUE TITLE
networkmanager-openconnect: missing dep for package

### ISSUE THREAD

**Issue by LER0ever** [AOSC-Dev/aosc-os-abbs#341]
The package "networkmanager-openconnect" should also depend on "networkmanager-vpnc" because openconnect relies on vpnc. 
For now, I have to manually install both "networkmanager-openconnect" and "networkmanager-vpnc" to make the cisco thing work.

**Comment by MingcongBai** [comment]
> This is the  default behavior on most distributions. (Like Arch, Fedora, etc.) - jsteward @ #aosc 

However this breaks Cisco VPN support with Plasma-NM...
