### ISSUE TITLE
dkms: generealize all installation and uninstallation

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#345]
Currently in `postinst` and `prerm`, the scriplets only accounts for module installation of the currently running kernel, however, it may help aid in user experience to just build modules for every kernel version - so that when updating a kernel, it won't be necessary to rebuild the kernel modules on boot (which slows the boot process significantly).

**Comment by MingcongBai** [comment]
Fixed by 7949b3e3bf2f3995e6d9c378b514c650f43d09f4. Closing.

**Comment by LionNatsu** [comment]
It works well now.
