### ISSUE TITLE
linux-kernel-*: reconfigurate grub after uninstall

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#346]

**Comment by MingcongBai** [comment]
For the sake of completeness:

The package `linux-kernel` configures initrd with `dracut` and GRUB with post-installation script. However, when uninstalling a particular Kernel version, GRUB configuration was never updated, leaving invalid entries that attempts to start AOSC OS with an uninstalled Kernel, causing "no such file or directory" errors on boot (system unusable).

We should remove old initrd files too, as they just takes up ~30MB each for our `aosc-main` kernel.
