### ISSUE TITLE
dpkg, OS3-rpm: update-alternatives is in dpkg package

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#35]
Maybe we should split it.

**Comment by MingcongBai** [comment]
Voting +1 for this.

@Icenowy @butangmucat @bobcao3

**Comment by bobcao3** [comment]
+1 We should have it

**Comment by Arthur2e5** [comment]
> +1 We should have it
> Voting +1 for this.

Am I on Google+?

**Comment by butangmucat** [comment]
+1

**Comment by MingcongBai** [comment]
Fixed #44, then this is fixed too.
