### ISSUE TITLE
pakreq: (network) monitoring tools

### ISSUE THREAD

**Issue by gumblex** [AOSC-Dev/aosc-os-abbs#356]
- [x] nload
- [x] iftop
- [x] iptraf
- [x] bmon
- [x] slurm
- [x] tcptrack
- [x] bwm-ng
- [x] cbm
- [x] speedometer
- [x] pktstat
- [x] netdiag
- [x] dstat
- [x] collectl
- [x] powertop

**Comment by MingcongBai** [comment]
`netdiag` is just a pain in the arse.

**Comment by MingcongBai** [comment]
All done by 3a474ba27c11f3718476aa66e1f7ca4e2743d897. Closing.
