### ISSUE TITLE
linux-kernel: config outdated on Loongson 3

### ISSUE THREAD

**Issue by KexyBiscuit** [AOSC-Dev/aosc-os-abbs#3563]
### Intended Version

5.14.11

### Target Branch

stable

### Description

When working on #3561, it was found that config for Loongson 3 is outdated for a while.

**Comment by cthbleachbit** [comment]
I believe loongson3 config is now on par as of 5.16? Config is updated for 5.17 as well (although we have no way to actually test whether the kernels will boot)
