### ISSUE TITLE
wiki: where are the autobuild3's configurations?

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#359]
https://github.com/AOSC-Dev/aosc-os-abbs/wiki/Autobuild3#initial-configurations

`/etc/autobuild/default/` ?

I have no `default` but `ab3cfg.sh` and `ab3_defcfg.sh`, in the latest buildkit tarball.

**Comment by MingcongBai** [comment]
https://github.com/AOSC-Dev/aosc-os-abbs/wiki/Autobuild3 It's now fixed, thanks for pointing that out.
