### ISSUE TITLE
Do libcacard split?

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#36]
I personally would suggest `libcacard` being split from `qemu`, as this library is needed for multiple VNC/rdp clients, and a spice-based xf86 video driver.

Instead of installing a full Qemu, can we save the hassle?

**Comment by Icenowy** [comment]
If only you can build it independently

**Comment by MingcongBai** [comment]
@Icenowy well, of course I can, with abbs.

**Comment by MingcongBai** [comment]
Closing.
