### ISSUE TITLE
croscore-fonts: version numbering

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#363]
It seems to me that the version numbers that many distros are derived from https://gsdview.appspot.com/chromeos-localmirror/distfiles/, which basically uses the newest version in the font metadata as the [major.minor] version.

I think we should do the same for our repacks (i.e. 1:1.32.0).

**Comment by MingcongBai** [comment]
Funny enough, our `croscore-fonts` is on a 20160503 snapshot. But if there is indeed a stable version, downgrading anyways.

**Comment by Artoria2e5** [comment]
It is not a stable one. It's a stale mirror actually.

**Comment by MingcongBai** [comment]
> It is not a stable one. It's a stale mirror actually.

Would have been useful to know.

**Comment by MingcongBai** [comment]
Addressed with b2011f02c9832c62ae315a8ee1b4c9d4328f6dae. Closing.
