### ISSUE TITLE
croscore-fonts: consider adding SymbolNeu from 1.23.0

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#364]
[Symbol](https://en.wikipedia.org/wiki/Symbol_%28typeface%29) is a typeface with many symbols mapped directly into the ASCII & naive single-byte extended ASCII area, intended to typeset mathematical symbols in the dark ages. It would be interesting to include Google's version of this font, SymbolNeu, which is recognized by fontconfig as a Symbol substitute.

Warning: Do NOT use SymbolNeu as a normal font.

[1.23.0](https://gsdview.appspot.com/chromeos-localmirror/distfiles/croscorefonts-1.23.0.tar.gz)

**Comment by MingcongBai** [comment]
Fixed with b2011f02c9832c62ae315a8ee1b4c9d4328f6dae.

**Comment by Artoria2e5** [comment]
Hey, I am seeing a regression in the font version…

We should keep making custom tarballs for 1.32.0  (current).

**Comment by MingcongBai** [comment]
> Hey, I am seeing a regression in the font version…

That was my doubt too... Any idea on why they stopped making versioned tarballs?

**Comment by Artoria2e5** [comment]
Looks like this: https://bugs.chromium.org/p/chromium/issues/detail?id=252858
