### ISSUE TITLE
pakreq: JPEXS Free Flash Decompiler

### ISSUE THREAD

**Issue by Garfield550** [AOSC-Dev/aosc-os-abbs#369]
虽然这并不是什么好东西（关于反编 Flash）

[JPEXS Free Flash Decompiler](https://github.com/jindrapetrik/jpexs-decompiler)

**Comment by MingcongBai** [comment]
Not strictly legal to use, but legal to ship either way. Got it.

**Comment by liushuyu** [comment]
This is not easy to package `apache-ant` and full `openjdk` are needed, in addition, ant's `build.xml` should be carefully examined to determine which build cycle should be used for AOSC OS
