### ISSUE TITLE
tree: survey and re-mark AB_FLAGS_PIE=0

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#370]
Core 3 invokes `-fPIE` for both compiler and linker with no regard for the co-existing `-fPIC` flag passed to the two. While most Autotools projects can cope with this quite well by disabling one of them in regard to what is actually being built (executable or shared object), there are many more that failed to build due to this flawed design.

With Core 4, we are shipping Autobuild3 with hardened specs for GCC and LD, making it possible to build all packages with PIE flags enabled by default (with several exceptions while doing rebuild for #366 though, maybe an issue to look into later on).

We should now survey the whole tree (well, `grep -r`) for `AB_FLAGS_PIE=0` config, try to build those packages without this config:
- If the build passes, good, remove that line of shame;
- If the build still fails, replace them with `AB_FLAGS_SPECS=0` - as the issue here will be that the package may not be built with PIE enabled anyways (thumbs down), and therefore the compiler and the linker should take no more effort in building them with specs.

Those packages which fails to build with `AB_FLAGS_SPECS=1` (default) should have a bug report filed regarding this issue.

**Comment by gumblex** [comment]
Note that extra-lisp/chibi-scheme has a `AB_FLAGS_PIE=no`

**Comment by MingcongBai** [comment]
> Note that extra-lisp/chibi-scheme has a AB_FLAGS_PIE=no

There are a lot more... A simple `grep -r` will yeld a list if you try it.

**Comment by gumblex** [comment]
I mean others are all AB_FLAGS_PIE=0 except that extra-lisp/chibi-scheme has a no.

**Comment by MingcongBai** [comment]
> I mean others are all AB_FLAGS_PIE=0 except that extra-lisp/chibi-scheme has a no.

Both yes/no and 0/1 works on this parameter.

**Comment by gumblex** [comment]
`yes` won't work. https://github.com/AOSC-Dev/autobuild3/blob/master/arch/_common_switches.sh#L5

**Comment by MingcongBai** [comment]
> yes won't work. https://github.com/AOSC-Dev/autobuild3/blob/master/arch/_common_switches.sh#L5

My bad.

**Comment by Artoria2e5** [comment]
`yes` should work if you have `lib/base.sh` sourced.

**Comment by liushuyu** [comment]
I think this is outdated since we already have `gcc` specs just for dealing with that.

**Comment by liushuyu** [comment]
@MingcongBai Is this issue resolved?

**Comment by MingcongBai** [comment]
@liushuyu No, this still has to be done - especially now that this flag is deprecated and replaced with `AB_FLAGS_SPECS`

**Comment by MingcongBai** [comment]
We have moved past using hard-coded `-fPIE` since Core 5, see https://github.com/AOSC-Dev/autobuild3/commit/b18916f063598476d5f5139d4ccfc2fd7208e990.
