### ISSUE TITLE
expat: security update to 2.4.6

### ISSUE THREAD

**Issue by hartwork** [AOSC-Dev/aosc-os-abbs#3753]
Hi!

[libexpat ~2.4.3~ ~2.4.4~ ~2.4.5~ 2.4.6](https://github.com/libexpat/libexpat/releases/tag/R_2_4_6) with **security fixes** has been released, the upstream [change log](https://github.com/libexpat/libexpat/blob/R_2_4_6/expat/Changes) has more details.

Thanks for updating! :pray: 

Best, Sebastian

**Comment by MingcongBai** [comment]
Thanks for your report, we will address this shortly.

**Comment by hartwork** [comment]
@MingcongBai thank you!

**Comment by hartwork** [comment]
I made the ticket about 2.4.4 now, released yesterday

**Comment by hartwork** [comment]
I made the ticket about 2.4.5 now, released a few hours ago.

**Comment by hartwork** [comment]
I made the ticket about 2.4.6 now, released a few minutes ago.

**Comment by hartwork** [comment]
#3857 has been merged by now, closing as fixed. Please re-open if that was too eager.
