### ISSUE TITLE
dropbox: too outdated to login

### ISSUE THREAD

**Issue by LER0ever** [AOSC-Dev/aosc-os-abbs#377]
The latest version is around 3.16.\* , and the outdated dropbox in the repo can't even login.

> "You are using an old version of dropbox"

**Comment by MingcongBai** [comment]
Actually it doesn't work any more in a case of packages...

It will complain about `/usr/lib/dropbox/library.zip` not being a Zip file. However, it wasn't a Zip file in the first place (when I decompressed the official binary tarball).

**Comment by MingcongBai** [comment]
Updated multiple times since then. If this issue arises again, please open another issue.
