### ISSUE TITLE
wiki: Autobuild3-Filters. How are these filters apply to ab? Any options?

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#378]
https://github.com/AOSC-Dev/aosc-os-abbs/wiki/Autobuild3-Filters

**Comment by MingcongBai** [comment]
"Here below is a list of options for the `elf` filter. Option variables should be appended to `autobuild/defines` or its respective architectural counterpart."

"Here below is a list of options for the `lib_archives` filter. Option variables should be appended to `autobuild/defines` or its respective architectural counterpart."

**Comment by LionNatsu** [comment]
I mean, for example, where is the option that **switch** 'elf' on/off?

**Comment by MingcongBai** [comment]
> I mean, for example, where is the option that switch 'elf' on/off?

Not designed to be switched on/off all together, all the options are listed below, if you set all three to `0`, it essentially means they are turned off.

**Comment by LionNatsu** [comment]
Wait... You mean these filters be used, always? Well, if the answer is yes, I strongly suggest to tell readers this behavior on the top of this page.

**Comment by MingcongBai** [comment]
> Wait... You mean these filters are used, always?

It is always installed, for some options like the `perl` filter - you simply can't package properly without it.

> Well, if the answer is yes, I strongly suggest to tell readers this behavior on the top of this page.

One second.

**Comment by MingcongBai** [comment]
https://github.com/AOSC-Dev/aosc-os-abbs/wiki/Autobuild3-Filters It's now updated, see if it's easier for you to understand.

Close this if you do agree.

**Comment by LionNatsu** [comment]
Good enough.

`$PKGDIR` is undefined yet, though, it is another issue (https://github.com/AOSC-Dev/aosc-os-abbs/issues/379#issuecomment-247858750).
