### ISSUE TITLE
wiki: Autobuild3-Tips-and-Tricks.

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#379]
https://github.com/AOSC-Dev/aosc-os-abbs/wiki/Autobuild3-Tips-and-Tricks

I think you have to answer some important questions.

### Case 1
What is `$PKGDIR`? It is not mentioned before.
I often see `make install` and 'they work perfectly', but is the additional `DESTDIR="$PKGDIR"` necessary? What do template `plainmake` do?

### Case 2
Why is `/usr` in `AUTOTOOLS_DEF="-prefix /usr"`?
What is *shadow build* ?

**Comment by MingcongBai** [comment]
> What is $PKGDIR? It is not mentioned before.

Updated the wiki, see if it clears it up.

"`"$PKGDIR"` is Autobuild3's internal definition for "packaging directory", which is usually `abdist` in the source root."

> I often see make install and 'they work perfectly', but is the additional DESTDIR="$PKGDIR" necessary?

`DESTDIR="$PKGDIR"` specifies the installation target for `make install` is the "packaging root" instead of `/`.

> What do template plainmake do?

https://github.com/AOSC-Dev/aosc-os-abbs/wiki/Autobuild3#build-types Check this out again.

> Why is /usr in AUTOTOOLS_DEF="-prefix /usr"?

This is a non-autotool `configure` parameter, which serves as an example of how you can manipulate Autobuild3 into using an existing `ABTYPE` even when it doesn't fit the template.

> What is shadow build ?

"`ABSHADOW=` expects a binary value (0/1) that decides whether to perform a "shadow build", or building the source from a separate directory (outside the source root), some sources likes it, some not so much (Defaults to 1 or "on")."

https://github.com/AOSC-Dev/aosc-os-abbs/wiki/Autobuild3#the-defines-file

**Comment by LionNatsu** [comment]
> > What is $PKGDIR? It is not mentioned before.
>
> Updated the wiki, see if it clears it up.

It is better now, but I suggest you move that line to somewhere before this page, because Autobuild3-Filters has this problem too. (ref. will be following this post)

**Comment by LionNatsu** [comment]
> > What do template plainmake do?
> 
> https://github.com/AOSC-Dev/aosc-os-abbs/wiki/Autobuild3#build-types Check this out again.

Will be better if Autobuild3#build-types provide the directory where these templates are.

**Comment by MingcongBai** [comment]
> Will be better if Autobuild3#build-types provide the directory where these templates are.

Will do, sir.

**Comment by MingcongBai** [comment]
Updated, https://github.com/AOSC-Dev/aosc-os-abbs/wiki/Autobuild3#build-types : 

"Pre-defined scripts of these build types may be found [here](https://github.com/AOSC-Dev/autobuild3/tree/master/build). You may find that they are all prefixed with numbers - prefixes with smaller numbers are of higher priority when detecting for build types. More explained in the example below."

**Comment by LionNatsu** [comment]
> > Why is /usr in AUTOTOOLS_DEF="-prefix /usr"?
> 
> This is a non-autotool `configure` parameter, which serves as an example of how you can manipulate Autobuild3 into using an existing `ABTYPE` even when it doesn't fit the template.
> 

An example??! Oh... additional descriptions is necessary.

BTW, why `/usr`?

**Comment by MingcongBai** [comment]
> BTW, why /usr?

Please just read about this https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard. Although AOSC OS is not 100% compliant with that standard, it is still useful to read about.

**Comment by LionNatsu** [comment]
A simple 'for example' on that autotools_def example will help a lot.

**Comment by MingcongBai** [comment]
> A simple 'for example' on that autotools_def example will help a lot.

Do you have an idea on how that could be presented intuitively?

**Comment by LionNatsu** [comment]
> ...building the source from a separate directory (outside the source root),...

What does it mean? Somewhere in /tmp/..?

It's hard to understand...

**Comment by LionNatsu** [comment]
> Do you have an idea on how that could be presented intuitively?

Ummm... No.

**Comment by MingcongBai** [comment]
> What does it mean? Somewhere in /tmp/..?

It would technically work, but there **is** a default behavior for Autobuild3 to create a `build` directory at source root and build stuff from there. I will add it there.

**Comment by MingcongBai** [comment]
> What does it mean? Somewhere in /tmp/..?

"ABSHADOW= expects a binary value (0/1) that decides whether to perform a "shadow build", or building the source from a separate directory (outside the source root), some sources likes it, some not so much (Defaults to 1 or "on"). Note: when "shadow build" is specified, Autobuild3 will create a build directory at source root, change directory into the directory, and invoke build commands in relation to the location of the source root (for example, ../configure opposed to ./configure when not doing a "shadow build")."

Wiki updated.

**Comment by MingcongBai** [comment]
> Ummm... No.

The point of the example is to show how Autobuild3 can use non-standard arguments with a standard ABTYPE (build template)... I guess it should be fine for now.

**Comment by LionNatsu** [comment]
*Click*, Noice.

**Comment by MingcongBai** [comment]
> Click, Noice.

You learn fast, young one.
