### ISSUE TITLE
wiki: Autobuild3. How to build?

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#380]
How to build? There is no even a word...

Alright, 12 words in a pair of round brackets.

https://github.com/AOSC-Dev/aosc-os-abbs/wiki/Autobuild3
> Autobuild3 is essentially a set of scripts (`autobuild` is the only command script useful for 
> invoking a build process) that works to automatically ...

But what and where does it output? Where do we must be (I mean the current directory)? Are there any command arguments can be used?

**Comment by MingcongBai** [comment]
Rephrase your question please? I don't think I fully understand what you are talking about.

**Comment by LionNatsu** [comment]
After reading through the wiki of Autobuild3, all I realized is how to configure it especially what do these files mean. But after configuration, what can I do?

I don't know how to start to build a package... use Autobuild3, I mean.

**Comment by MingcongBai** [comment]
> I don't know how to start to build a package... use Autobuild3, I mean.

Oops! That's quite an oversight. Let me append that somewhere.

Also, any idea on how I could notify people about the changes in Autobuild3 Core 4 update apart from using IRC/Telegram messages?

**Comment by MingcongBai** [comment]
> I don't know how to start to build a package... use Autobuild3, I mean.

Added info here https://github.com/AOSC-Dev/aosc-os-abbs/wiki/Autobuild3#invoking-autobuild3. If you do find it helpful with understanding this process, close this issue.

**Comment by LionNatsu** [comment]
README.md maybe?

**Comment by MingcongBai** [comment]
> README.md maybe?

Well that won't help as it's not a part of wiki, or a way of notification... I mean, IRC/Telegram messages are helpful, and Wiki must be updated as well. 

Are notifications sent out with updates to GH wiki pages?

**Comment by LionNatsu** [comment]
How about...
change
> ... - and simply type in the `autobuild` command to start building.
to
> ... - and simply type in the `autobuild` command at the source root to start building.

**Comment by MingcongBai** [comment]
Good idea.

**Comment by MingcongBai** [comment]
Updated. All clear?

**Comment by MingcongBai** [comment]
Good.
