### ISSUE TITLE
pakreq: repack `cinnamon`, `gnome-shell` 

### ISSUE THREAD

**Issue by nexplorer-3e** [AOSC-Dev/aosc-os-abbs#3881]
description: their depend package `vino` and `caribou` was deprecated and is not avaliable in the repo, cause GNOME and Cinnamon cannot be installed properly.

**Comment by nexplorer-3e** [comment]
and if possible, please include `equivs` to solve the depend problem as a workaround.

**Comment by CamberLoid** [comment]
Hi there.
I am writing this to inform you we are aware of this issue, and currently, I am trying to fix this problem under branch gnome-shell-40.4-dependencies-fix #3880 . These changes is partially available on testing repo `deb https://repo.aosc.io/debs gnome-shell-40.4-dependencies-fix main` and waiting to be tested. 

> and if possible, please include equivs to solve the depend problem as a workaround.

This package is not yet introduced into our distro. If you are interested please join our telegram channel and we can have a deep discussion about this.

**Comment by CamberLoid** [comment]
The fix of gnome #3880 is merged and will be deployed in a few hours.

As for cinnamon, I can confirm that cinnamon will fail to start without `caribou`(more test needed). This means we may revert the drop of `caribou`. I will post here if there is any update related available.

**Comment by Cyanoxygen** [comment]
Hi,
We are bringing back `caribou` as it is necessary for Cinnamon to run. PR #3883 is being reviewed, updates to stable will be pushed as soon as this PR is merged.

**Comment by CamberLoid** [comment]
Hi.
I have noticed that #3883 is merged and the packages have been pushed to the repository, stable branch. You can help test them if possible.

If there is still any problem please let us know.

**Comment by CamberLoid** [comment]
Closing issue #3881 as PR #3883 is merged and tested. 
Re-open this issue or open a new issue if there is any other problems.
