### ISSUE TITLE
clash-premium: waiting upstream releases for `ppc64el` and `loongarch64`

### ISSUE THREAD

**Issue by CamberLoid** [AOSC-Dev/aosc-os-abbs#3894]
This issue is opened to mark that currently there is no upstream support/release of closed-source clash `clash-premium` for our secondary architecture `ppc64el`, `riscv64` and `loongarch64`. I on behalf of the AOSC community have submitted a request to upstream for support of those architecture Dreamacro/clash#2032 and still await response. 

Affected packages:
- `clash-premium`: `ppc64el`, `riscv64`, `loongarch64`

Pull request #3873 will be proceeded anyway.

**Comment by KexyBiscuit** [comment]
Go 1.19 now supports loongarch64, adding it.

**Comment by CamberLoid** [comment]
Upstream has begun to release riscv64 build. Editing.

**Comment by KexyBiscuit** [comment]
`loong64` builds were available for 2023.08.17, after that version the upstream disappeared, closing.
