### ISSUE TITLE
git: default editor

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#393]
It should not be `vi` or `vim` while we provide `nano` in distributions.

**Comment by LionNatsu** [comment]
Default editor is `vi` yet (for over months). Reopening.

**Comment by LionNatsu** [comment]
Reproduces on my laptop, Neo and Rasp 3.

The fix at https://github.com/AOSC-Dev/aosc-os-abbs/blob/master/extra-vcs/git/autobuild/build#L6 does not work.

Please check this in shell.
```shell
git var -l
```

```
lion@Lion-Laptop [ testgit@ ] $ echo $GIT_EDITOR $EDITOR $VISUAL

lion@Lion-Laptop [ testgit@ ] $ git config -l
user.email=lion@aosc.xyz
user.name=Lion Yang
http.cookiefile=/home/lion/.gitcookies
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
lion@Lion-Laptop [ testgit@ ] $ git var -l
user.email=lion@aosc.xyz
user.name=Lion Yang
http.cookiefile=/home/lion/.gitcookies
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
GIT_COMMITTER_IDENT=Lion Yang <lion@aosc.xyz> 1492313921 +0800
GIT_AUTHOR_IDENT=Lion Yang <lion@aosc.xyz> 1492313921 +0800
GIT_EDITOR=vi
GIT_PAGER=less
lion@Lion-Laptop [ testgit@ ] $ ssh root@Lion-Neo-5 'git var -l'
GIT_COMMITTER_IDENT=root <root@Lion-Neo-5.(none)> 1492313955 +0000
GIT_AUTHOR_IDENT=root <root@Lion-Neo-5.(none)> 1492313955 +0000
GIT_PAGER=less
lion@Lion-Laptop [ testgit@ ] $ ssh root@Lion-RPi3 'git var -l'
GIT_COMMITTER_IDENT=root <root@Lion-RPi3.(none)> 1492313965 +0000
GIT_AUTHOR_IDENT=root <root@Lion-RPi3.(none)> 1492313965 +0000
GIT_PAGER=less
lion@Lion-Laptop [ testgit@ ] $
```

FYI.

> GIT_EDITOR::
>     Text editor for use by Git commands.  The value is meant to be
>     interpreted by the shell when it is used.  Examples: `~/bin/vi`,
>     `$SOME_ENVIRONMENT_VARIABLE`, `"C:\Program Files\Vim\gvim.exe"
>     --nofork`.  The order of preference is the `$GIT_EDITOR`
>     environment variable, then `core.editor` configuration, then
>     `$VISUAL`, then `$EDITOR`, and then the default chosen at compile
>     time, which is usually 'vi'.
> ifdef::git-default-editor[]
>     The build you are using chose '{git-default-editor}' as the default.
> endif::git-default-editor[]

https://github.com/git/git/blob/master/editor.c
```c
#ifndef DEFAULT_EDITOR
#define DEFAULT_EDITOR "vi"
#endif

const char *git_editor(void)
{
	const char *editor = getenv("GIT_EDITOR");
	const char *terminal = getenv("TERM");
	int terminal_is_dumb = !terminal || !strcmp(terminal, "dumb");

	if (!editor && editor_program)
		editor = editor_program;
	if (!editor && !terminal_is_dumb)
		editor = getenv("VISUAL");
	if (!editor)
		editor = getenv("EDITOR");

	if (!editor && terminal_is_dumb)
		return NULL;

	if (!editor)
		editor = DEFAULT_EDITOR;

	return editor;
}
```

I don't know why...

**Comment by liushuyu** [comment]
```c
#ifndef DEFAULT_EDITOR
#define DEFAULT_EDITOR "vi"
```

Well, in this case, let's just hard-code `nano` instead 😄

**Comment by lmy441900** [comment]
@liushuyu No.

**Comment by LionNatsu** [comment]
Wait, There are something very interesting.

```
lion@Lion-Laptop [ testgit@ ] $ ssh root@Lion-Neo-5
Last login: Sun Apr 16 03:26:38 2017 from 10.0.2.1
root@Lion-Neo-5 [ ~ ] # git var -l
GIT_COMMITTER_IDENT=root <root@Lion-Neo-5.(none)> 1492315014 +0000
GIT_AUTHOR_IDENT=root <root@Lion-Neo-5.(none)> 1492315014 +0000
GIT_EDITOR=vi
GIT_PAGER=less
root@Lion-Neo-5 [ ~ ] # exit
logout
Connection to lion-neo-5 closed.
lion@Lion-Laptop [ testgit@ ] $ ssh root@Lion-Neo-5 'git var -l'
GIT_COMMITTER_IDENT=root <root@Lion-Neo-5.(none)> 1492315064 +0000
GIT_AUTHOR_IDENT=root <root@Lion-Neo-5.(none)> 1492315064 +0000
GIT_PAGER=less
```

**Comment by lmy441900** [comment]
> It should not be vi or vim while we provide nano in distributions.

Well, that's true.

**Comment by MingcongBai** [comment]
> Wait, There are something very interesting.

Weird...

**Comment by MingcongBai** [comment]
> Well, in this case, let's just hard-code nano instead

So I'd say define that in `$CPPFLAGS`?

**Comment by LionNatsu** [comment]
But wait, configure.?? and Makefile have the flag DEFAULT_EDITOR. But I can't understand these formats. Would you please look into them...?2017/04/16 午後1:43 Mingcong Bai <notifications@github.com>:
Well, in this case, let's just hard-code nano instead

So I'd say define that in $CPPFLAGS?

**Comment by MingcongBai** [comment]
Will do...
