### ISSUE TITLE
kdegraphics-thumbnailers not working with KDE

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#40]
Well, now no thumbnails are shown even when this package is installed. kdegraphics-thumbnailers-15.04.3-0.x86_64, AOSC OS3 RPM 0802.

**Comment by MingcongBai** [comment]
Okay, I will have a check on this soon.

**Comment by MingcongBai** [comment]
Refer to #64, closing this.
