### ISSUE TITLE
PakReq: NCBI-Toolkit

### ISSUE THREAD

**Issue by StephDC** [AOSC-Dev/aosc-os-abbs#403]
This includes NCBI sra-tools, ngs, and ncbi-vdb, all under GitHub NCBI account.
- https://github.com/ncbi/sra-tools
- https://github.com/ncbi/ngs
- https://github.com/ncbi/ncbi-vdb

**Comment by MingcongBai** [comment]
You were right... These things are tough to package, I will push this to a later date.

**Comment by StephDC** [comment]
Any updates on this?

**Comment by MingcongBai** [comment]
> Any updates on this?

Not yet...

**Comment by MingcongBai** [comment]
Packager experience 0/10... Done anyways, will build `blast+` as a bonus.
