### ISSUE TITLE
Common usability improvements on various server software 

### ISSUE THREAD

**Issue by Cyanoxygen** [AOSC-Dev/aosc-os-abbs#4043]
Description
------

After deploying Sandman (the name of the VPS, which I installed AOSC OS on it), I found some inconveniences configuring some server software.

TO-DO List
------
- [x] No `nginx` user (`nginx`) (or just unify web server users)
- [x] No *.d config directories for virtual servers, like `sites-{available,enabled}` in Debian)  (`apache`, `nginx`)

- [x] SSH still asking for password even `PasswordAuthentication no` (`ssh`)
- [x] duplicate webroots in `/srv` ('apache`, `nginx`)
- [x] Wrong document root path in default host of `nginx.conf` (`nginx`)
- [x] #4045
- [x] Default config file renders MariaDB setup impossible (mariadb)

TBD, Sandman can live up to two months. After that, I think I just use a regular VM in my home infra.

Branch
------
`sandman-improvements`

**Comment by KexyBiscuit** [comment]
Seems that all tasks are done, closing for now.
