### ISSUE TITLE
sddm: Why replaces default user face (avatar) with a white one?

### ISSUE THREAD

**Issue by shunf4** [AOSC-Dev/aosc-os-abbs#4055]
I noticed https://github.com/AOSC-Dev/aosc-os-abbs/blob/stable/extra-displaymanagers/sddm/autobuild/patches/0001-use-white-face-for-users.patch . This patch causes white blank icons with default theme selected in sddm:

![image](https://user-images.githubusercontent.com/20991618/177266674-36486fa2-b25c-447b-90c4-42c5b98b661e.png)

The original default face has a more normal appearance, e. g. in Arch Linux:

![image](https://user-images.githubusercontent.com/20991618/177266940-9944ba16-edf7-46d9-b0cd-fbc884724385.png)

**Comment by MingcongBai** [comment]
This issue will be addressed in an upcoming KDE update topic, we introduced this patch when we first packaged KDE 5, which did not handle the default SDDM avatar well.
