### ISSUE TITLE
build-essential

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#417]
Description:  Base tools for software building/development

But why  autoconf automake cmake are in suggests.

**Comment by LionNatsu** [comment]
Also, ` --install-suggests`doesn't work.

```
lion [ mtr@2016-09-29 ] $ sudo apt install build-essential --install-suggests
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
将会同时安装下列软件：
  pkg-config
推荐安装：
  autoconf automake cmake help2man
下列【新】软件包将被安装：
  build-essential pkg-config
升级了 0 个软件包，新安装了 2 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
需要下载 39.5 kB 的归档。
解压缩后会消耗 238 kB 的额外空间。
您希望继续执行吗？ [Y/n] 
```

**Comment by MingcongBai** [comment]
> But why autoconf automake cmake are in suggests.

Yeah that's a mistake...

**Comment by MingcongBai** [comment]
> Also, --install-suggestsdoesn't work.

It's actually in Recommends.

**Comment by LionNatsu** [comment]
`--no-install-recommends` in man... Is there `--install-recommends`?

Or they will be installed in default? (No, I think.)

**Comment by MingcongBai** [comment]
> Or they will be installed in default? (No, I think.)

I will need to look into that...
