### ISSUE TITLE
tpm: broken support

### ISSUE THREAD

**Issue by lmy441900** [AOSC-Dev/aosc-os-abbs#422]
```
lmy441900 [ ~ ] $ sudo dmesg | grep tpm
[    1.637811] tpm_crb MSFT0101:00: can't request region for resource [mem 0xfed40040-0xfed4103f]
[    1.637842] tpm_crb: probe of MSFT0101:00 failed with error -16
lmy441900 [ ~ ] $ sudo tcsd -f
TCSD TDDL ERROR: Could not find a device to open!
lmy441900 [ ~ ] ! tpmtool 
tpmtool: error while loading shared libraries: libopts.so.25: cannot open shared object file: No such file or directory
lmy441900 [ ~ ] ? 
```

**Comment by MingcongBai** [comment]
Got it. Will be fixed by tomorrow.

**Comment by lmy441900** [comment]
Found the patch in mainline Linux Kernel:

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=422eac3f7deae34dbaffd08e03e27f37a5394a56

And it is merged into Linux Kernel in 4.7.

**Comment by lmy441900** [comment]
We need more tests. Users who have:

1. TPM on their computer;
2. AOSC OS with at least Kernel 4.7.x

can help us to deal with this problem.

**Comment by MingcongBai** [comment]
> lmy441900 [ ~ ] ! tpmtool 
> tpmtool: error while loading shared libraries: libopts.so.25: cannot open shared object file: No > such file or directory
> lmy441900 [ ~ ] ? 

This part's fixed. The rest, will need more tester. But before this, could you check if your `tcsd.service` is up and running?

**Comment by lmy441900** [comment]
A detailed test.

![2016-10-07 12-16-56](https://cloud.githubusercontent.com/assets/4285573/19178698/0c061c66-8c88-11e6-993a-75da20937fb1.png)

**Comment by MingcongBai** [comment]
Could anyone test this again?

**Comment by Icenowy** [comment]
@MingcongBai ?

**Comment by MingcongBai** [comment]
@Icenowy I thought this bug was supposed to be fixed with 4.7.7... And we have 4.8.1 now.

**Comment by lmy441900** [comment]
Upgraded to 4.8.1 just now.

```
Oct 17 20:36:16 localhost kernel: tpm_crb MSFT0101:00: can't request region for resource [mem 0xfed40080-0xfed40fff]
Oct 17 20:36:16 localhost kernel: tpm_crb: probe of MSFT0101:00 failed with error -16
```

**Comment by MingcongBai** [comment]
Is this issue still here? @lmy441900

**Comment by MingcongBai** [comment]
@lmy441900 Is this still an issue (since you've got a new laptop already)? I have ran into other TPM issues before with other laptops, but nonetheless, it may be best to direct these kinds of issue to the upstream in the future.
