### ISSUE TITLE
NetworkManager - Broadcom wl related issue/bug

### ISSUE THREAD

**Issue by StephDC** [AOSC-Dev/aosc-os-abbs#423]
Original Bug report:
<https://bugzilla.gnome.org/show_bug.cgi?id=770456>
This would fix my BCM4360 Could not connect to internet - Too many opened files issue.

**Comment by MingcongBai** [comment]
Will need to upgrade `networkmanager`.

**Comment by MingcongBai** [comment]
According to @StephDC this is now fixed.
