### ISSUE TITLE
pakreq: ghostpdl-urwfonts

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#429]
Source: http://svn.ghostscript.com/ghostscript/trunk/ghostpdl/urwfonts/
Mapping: https://en.wikipedia.org/wiki/Ghostscript#Free_fonts; https://wiki.archlinux.org/index.php/Metric-compatible_fonts

**Comment by MingcongBai** [comment]
We have most of these don't we?

**Comment by Artoria2e5** [comment]
I don't think we have URW Classico or U001.

**Comment by MingcongBai** [comment]
Fair enough...

**Comment by MingcongBai** [comment]
Maybe I should merge this into `urw-fonts`?

**Comment by MingcongBai** [comment]
@Artoria2e5 Requesting response.

**Comment by Artoria2e5** [comment]
Sure, why not.

**Comment by MingcongBai** [comment]
Addressed with 051f2615d2ca1f45c766dabb07328f3f3d412686 (and many commits since then). Closing.
