### ISSUE TITLE
krb5 and man-db questions

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#43]
**NOTICE**: `krb5` is not yet in this repo. Move it in.

I have noticed that `krb5` contains empty directories `cat{1,5,8}` in `/usr/share/man`. Maybe we should add something to deal with it.

When I wanted to add some `cat* -> man*` symlinks to `man-db`, I also noticed the `0` section in `build`. I am quite curious how that section appeared. A crude search `dpkg -S man0` didn't mention any package installed which uses that section, so it must be quite rare (and of course nonstandard).

**Comment by LionNatsu** [comment]
I found a `install-catman:`(not `install:`) in `src/man/Makefile.in`. https://pastebin.anthonos.org/view/f8f6c58e#L61

But it seems can not be executed.

**Comment by LionNatsu** [comment]
> When I wanted to add some `cat* -> man*` symlinks to `man-db`...

Are you sure? File type of catman is different to man isn't it?

http://man7.org/linux/man-pages/man8/catman.8.html

**Comment by Artoria2e5** [comment]
> catman file format

Ah interesting..

**Comment by MingcongBai** [comment]
No input for 7 months... Any more coming?

**Comment by LionNatsu** [comment]
I don't think it's a bug. I think it is working as intended. What we can do may be call `make` with an `install-catman` or just ignore it unless anyone needs catman support.

**Comment by MingcongBai** [comment]
Okay. Let's get this closed then.
