### ISSUE TITLE
cor: migrated, update SRCTBL schema.

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#438]
From: https://github.com/nemomobile/cor
To: https://git.merproject.org/mer-core/cor

BTW, update please, from 0.1.7 (in 2013) to 0.1.18 （10 months ago）

**Comment by MingcongBai** [comment]
> BTW, update please, from 0.1.7 (in 2013) to 0.1.18 （10 months ago

Sorry I will drop this package... Nemo packages should have been dropped a long time ago. I will close this once they are removed.

**Comment by LionNatsu** [comment]
What excatly the Nemo is? I tried to find this but...

**Comment by MingcongBai** [comment]
> What excatly the Nemo is? I tried to find this but...

https://wiki.merproject.org/wiki/Nemo

BTW... It's "what exactly is blablabla?".

**Comment by LionNatsu** [comment]
Oh, thanks
