### ISSUE TITLE
dsme: remove

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#439]
As a part of Nemo, #438.

**Comment by Icenowy** [comment]
@LionNatsu I think it proper to drop all Nemo components now.

**Comment by LionNatsu** [comment]
@Icenowy After a bit of micro 'grep job', `cor` and `dsme` is all the packages which are relevant to Nemo.

BTW, `extra-cinnamon/nemo` has nothing to do with this stuff right?

**Comment by Icenowy** [comment]
@LionNatsu yes
