### ISSUE TITLE
config: remove the `build` scripts

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#44]
Many `build`s for armel seem to be simple workarounds (with `--host=$HOST` added).

I have finally got tired with that detection script, since `grep -H /configure */*/autobuild/build` solves most issues. (and `^cmake`, `^qmake`)

**Comment by Arthur2e5** [comment]
testing org webhook.

**Comment by MingcongBai** [comment]
Ongoing work.
