### ISSUE TITLE
upstream: qterminal merged into lxde

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#445]
From:
https://github.com/qterminal/qterminal
https://github.com/qterminal/qtermwidget

To:
https://github.com/lxde/qterminal
https://github.com/lxde/qtermwidget

https://github.com/qterminal/ does not exist now.

**Comment by LionNatsu** [comment]
Should I move `extra-lxqt/qterminal` to `extra-lxde/qterminal` and `extra-lxqt/qtermwidget` to `extra-lxde/qtermwidget`?

**Comment by MingcongBai** [comment]
Technically it's still part of the Qt port... So I would think not yet.

**Comment by LionNatsu** [comment]
Yes sir. (?
