### ISSUE TITLE
torsocks: upstream moved

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#448]
From https://github.com/dgoulet/torsocks
> NOTE: upstream has been moved to https://gitweb.torproject.org/torsocks.git

**Comment by LionNatsu** [comment]
@MingcongBai Can you do this? ( It is the 'raw git' type, with tags )

**Comment by MingcongBai** [comment]
Okay.

**Comment by MingcongBai** [comment]
> From https://github.com/dgoulet/torsocks

This still works though...
