### ISSUE TITLE
google-chrome: call desktop-file-utils on postinst

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#449]
Currently `google-chrome` does not call `desktop-file-utils` on installation, resulting in an "invisible" desktop entry (until the next reboot/login, depending on desktop environment).

Call this on `postinst`:

```bash
sh /var/ab/triggered/desktop-file-utils
```

**Comment by LionNatsu** [comment]
Yes, and because of the issue, I have to use Alt+Space now. (it's more convenient than shortcut indeed.)

**Comment by MingcongBai** [comment]
Fixed by https://github.com/AOSC-Dev/aosc-os-abbs/commit/9b910b184a116e4067816fa383a50b0a52eacac2.
