### ISSUE TITLE
numix-icon-theme-bevel: miss upstream

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#450]
Origin: https://github.com/numixproject/numix-icon-theme-bevel

Where is it now?

**Comment by LionNatsu** [comment]
I found this one: https://slackbuilds.org/repository/14.2/desktop/numix-icon-theme-bevel/

> numix-icon-theme-bevel (Numix Bevel icon theme)
> 
> Numix Bevel is a original set of current Numix Circle an icon theme
> for Linux from the Numix project.
> 
> Maintained by: Edinaldo P. Silva 
> Keywords: Desktop,Icons,Numix,Numix Bevel,
> 
> Homepage:
> https://github.com/numixproject/numix-icon-theme-circle/releases/

Here's someone in AUR upload it on his/her GH : https://aur.archlinux.org/packages/numix-bevel-icon-theme-git/

> Numix Bevel is the legacy version of Numix Base and Circle, icon themes for Linux. Note that this is not officially supported, though it may recieve occasional updates and new icons. Feel free to contribute to the theme here with your own icons - it's all licensed under GPLv3+.


Shall we remove this repo and add the new one (may be `numix-icon-theme-circle`), or hold this repo and add `numix-icon-theme-circle`?

**Comment by MingcongBai** [comment]
> Shall we remove this repo and add the new one (may be numix-icon-theme-circle), or hold this repo and add numix-icon-theme-circle?

Well the package may be kept, but fixing the src link will still be necessary.

**Comment by LionNatsu** [comment]
> Well the package may be kept, but fixing the src link will still be necessary.

But it has gone... Maybe we can use that backup repo uploaded by the AUR one?

**Comment by MingcongBai** [comment]
> But it has gone... Maybe we can use that backup repo uploaded by the AUR one?

That's fine.

**Comment by MingcongBai** [comment]
> But it has gone... Maybe we can use that backup repo uploaded by the AUR one?

What is up now?

**Comment by LionNatsu** [comment]
> What is up now?

The GH repo (the AUR one) has been removed.

Two choices:
- Read-only Git: https://aur.archlinux.org/numix-bevel-icon-theme.git
- Link from [SlackBuild](https://slackbuilds.org/repository/14.2/desktop/numix-icon-theme-bevel/): https://launchpad.net/~numix/+archive/ubuntu/ppa/+files/numix-icon-theme-bevel_1.0+201410212340~8~ubuntu14.10.1.tar.xz

Can someone(~~you~~) do this? :-<

**Comment by MingcongBai** [comment]
AUR Link 404... We have one choice then.

**Comment by LionNatsu** [comment]
> AUR Link 404... We have one choice then.

Wait,

> Note: Git clone URLs are not meant to be opened in a browser.
> To clone the Git repository of numix-bevel-icon-theme, run git clone https://aur.archlinux.org/numix-bevel-icon-theme.git.
> Click here to return to the numix-bevel-icon-theme details page.

**Comment by MingcongBai** [comment]
Okay that makes sense.

**Comment by MingcongBai** [comment]
This package will be dropped.
