### ISSUE TITLE
cutter: update to 2.3.2

### ISSUE THREAD

**Issue by XVilka** [AOSC-Dev/aosc-os-abbs#4566]
Cutter 2.3.2 has been released, depending on the corresponding Rizin 0.6.2 release:
- https://github.com/rizinorg/cutter/releases/tag/v2.3.2
- https://github.com/rizinorg/rizin/releases/tag/v0.6.2

Since 2.1.0 version there were many changes in the Rizin core:
- https://github.com/rizinorg/rizin/releases/tag/v0.5.0
- https://github.com/rizinorg/rizin/releases/tag/v0.6.0

**Comment by XVilka** [comment]
@MingcongBai

**Comment by MingcongBai** [comment]
@XVilka Thank you for bringing this to our attention. One of us should address this soon.

**Comment by XVilka** [comment]
Cutter 2.3.1 has been released, depending on the corresponding Rizin 0.6.1 release:

https://github.com/rizinorg/cutter/releases/tag/v2.3.1
https://github.com/rizinorg/rizin/releases/tag/v0.6.1

**Comment by XVilka** [comment]
Cutter 2.3.2 has been released, depending on the corresponding Rizin 0.6.2 release:
- https://github.com/rizinorg/cutter/releases/tag/v2.3.2
- https://github.com/rizinorg/rizin/releases/tag/v0.6.2

**Comment by jiegec** [comment]
Updated
