### ISSUE TITLE
Semi-Annually Security Survey Tracker, 2023H1

### ISSUE THREAD

**Issue by CamberLoid** [AOSC-Dev/aosc-os-abbs#4575]
## Background & Rules

This is a tracker issue of the upcoming Security Survey 2023H1, and also an experiment of "Roll-Up topic" as previously discussed[^1].

Version of packages related to the topics will not be **freezed** during the processing of security survey. 

### Timeline (Postponed. Update soon)

- Before Jun 30, 2023: Surveying and Opening issues. 
  - For issues with major severity, updates should be finished in this period.
- Jul 1 - Jul 10: Processing updates of security survey; finishing previously mentioned important issues.
- Jul 11 - Jul 15: Finishing updating, testing, and merging to stable.

### main: Roll-up Topic 2023H1

Packages in main has minor security severity, and will be summed to the `security-survey-2023h1-main`

- libTIFF `libtiff`
- `openssh` Issue to be open
- `nautilus` Issue #4579 , not important.

(To be filled)

### firefox

Issues #4608 #4609 
PR #4611 

### Golang toolchain

- `go` and related packages (To be opened separately)

---

[^1]: https://wiki.aosc.io/developer/minutes/20230604/#roll-up-type-topics

**Comment by KexyBiscuit** [comment]
Everything is fixed except `libtiff`, closing for now.
