### ISSUE TITLE
duplicate packages

### ISSUE THREAD

**Issue by gumblex** [AOSC-Dev/aosc-os-abbs#465]
* `desktop-file-utils` found in `extra-misc/desktop-file-utils` and `extra-admin/desktop-file-utils`
* `diffutils` found in `base-utils/diffutils` and `extra-devel/diffutils`
* `libcdio` found in `extra-multimedia/libcdio` and `extra-libs/libcdio`
* `cuda` found in `extra-devel/cuda` and `extra-libs/cuda`
* `ttf-adf` found in `extra-fonts/wangfonts` and `extra-fonts/ttf-adf`
* `cantarell-fonts` found in `extra-fonts/cantarell-fonts` and `extra-gnome/cantarell-fonts`
* `extra-cmake-modules` found in `extra-devel/extra-cmake-modules` and `extra-kde/extra-cmake-modules`
* `lxdm` found in `extra-lxde/lxdm` and `extra-displaymanagers/lxdm`
* `gdm` found in `extra-gnome/gdm` and `extra-displaymanagers/gdm`
* `python-gnuplot` found in `extra-python/gnuplot-py` and `extra-python/python-gnuplot`
* `bc` found in `base-utils/bc` and `extra-utils/bc`

**Comment by LionNatsu** [comment]
Every thing looks good as an issue, but

* `ttf-adf` found in `extra-fonts/wangfonts` and `extra-fonts/ttf-adf`

I checked `extra-fonts/wangfonts` 's `defines`, 
```
PKGNAME=ttf-adf
PKGSEC=fonts
PKGDEP="fontconfig"
PKGDES="Wang Hanzong font family"

ABHOST=noarch
```

This is definitely a terrible mistake. Opening another issue and pending for confirmation.

**Comment by LionNatsu** [comment]
> * `python-gnuplot` found in `extra-python/gnuplot-py` and `extra-python/python-gnuplot`

This one will be more complicated.

![screenshot_20161017_213850](https://cloud.githubusercontent.com/assets/6694582/19439826/24ca6a5e-94b2-11e6-9a2f-b1cdea0e2416.png)

**Comment by LionNatsu** [comment]
Wow, quiz

desktop-file-utils
- [ ] `extra-misc`
- [ ] `extra-admin`

diffutils
- [ ] `base-utils`
- [ ] `extra-devel`

libcdio
- [ ] `extra-multimedia`
- [ ] `extra-libs`

cuda
- [ ] `extra-devel`
- [ ] `extra-libs`

cantarell-fonts
- [ ] `extra-fonts`
- [ ] `extra-gnome`

extra-cmake-modules
- [ ] `extra-devel`
- [ ] `extra-kde`

lxdm
- [ ] `extra-lxde`
- [ ] `extra-displaymanagers`

gdm
- [ ] `extra-gnome`
- [ ] `extra-displaymanagers`

bc
- [ ] `base-utils`
- [ ] `extra-utils`

**Comment by MingcongBai** [comment]
Which ever is updated the latest is the one to keep.

**Comment by MingcongBai** [comment]
Mind you though, the case of `gdm` is a symlink.

**Comment by LionNatsu** [comment]
Oooooh, you are right. `lxdm` is a symlink too.

I'll check the type (if it's a symlink) and the version.

**Comment by LionNatsu** [comment]
Symlinks:
- `gdm`
- `lxdm`
- `cantarell-fonts`

**Comment by LionNatsu** [comment]
`extra-python/gnuplot-py` and `extra-python/python-gnuplot`
