### ISSUE TITLE
systemctl: units not found

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#480]
Input `systemctl start <Tab>`, some error message comes out.

RPi tarball: `Unit auditd.service could not be found.`
KDE tarball: `Unit boot.mount could not be found.`

**Comment by lmy441900** [comment]
@LionNatsu Ouch, I have this problem too.

**Comment by MingcongBai** [comment]
This is fixed in https://github.com/systemd/systemd/commit/bd5b9f0a12dd9c1947b11534e99c395ddf44caa9.
