### ISSUE TITLE
pakreq: gifsicle & giflossy

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#481]
[gifsicle](https://github.com/kohler/gifsicle) is a command-line util for dealing with gifs. All it provides is three standalone binaries. `gifview` depends on X.

[giflossy](https://kornel.ski/lossygif) is a gifsicle fork which modifies the `gifsicle` util to use lossy LZW instead. Consider `./configure`'ing with everything but `gifsicle` disabled, followed by an extra `mv "$PKGDIR"/usr/bin/{gifsicle,giflossy}` step.

PS: It appears that giflossy's author forgot to tag later versions which contain commits rebased from gifsicle 1.82~1.88. Consider inventing a version number for current git head.

**Comment by MingcongBai** [comment]
Added by 5ad1483aa374958d1f06c93a65cd4d3b0d86f3e0 and 67fe8eb7240c013351bb7d6cb71572d0453a0585.
