### ISSUE TITLE
pakreq: ngrok

### ISSUE THREAD

**Issue by ChizuruAmamiya** [AOSC-Dev/aosc-os-abbs#482]

**Comment by MingcongBai** [comment]
Note, upstream dir: https://ngrok.com/

**Comment by ChizuruAmamiya** [comment]
References: Gentoo ebuild: https://gpo.zugaina.org/AJAX/Ebuild/16342962/View

EAPI=5
DESCRIPTION="Introspected tunnels to localhost"
SRC_URI="https://github.com/inconshreveable/ngrok/archive/${PV}.tar.gz"
HOMEPAGE="https://ngrok.com"

**Comment by MingcongBai** [comment]
Much appreciated, thanks.

**Comment by ChizuruAmamiya** [comment]
According to the AUR (Arch Linux User Repo)：

This package is now based on ngrok 2.x, and is binary only. There is some auto-updating functionality built into ngrok now, but as I only recently switched to 2.x, I am not sure what effect this will have on the packaging. Please let me know if you run into any problems.  
So just binary installation is OK.

Ref: 
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ngrok

**Comment by MingcongBai** [comment]
> This package is now based on ngrok 2.x, and is binary only. There is some auto-updating functionality built into ngrok now, but as I only recently switched to 2.x, I am not sure what effect this will have on the packaging. Please let me know if you run into any problems.

Okay... This makes this package kind of risky to build.

**Comment by MingcongBai** [comment]
So they have decided to go closed source since 2.x?

**Comment by ChizuruAmamiya** [comment]
Maybe, so I decide to close this request now.
