### ISSUE TITLE
blender: freeze in "User Preference" > "System"

### ISSUE THREAD

**Issue by lmy441900** [AOSC-Dev/aosc-os-abbs#494]
When clicking into "User Preference" > "System" tab, the whole blender freezes, without any kind of error, warning, or high CPU usage.

Use `blender --debug-all` to start blender, and the following lines can be seen after clicking into the "System" tab:

```
I1108 12:56:54.024356  2374 device_cuda.cpp:1353] CUEW initialization failed: Error opening the library
I1108 12:56:54.024703  2374 device_opencl.cpp:3304] CLEW initialization succeeded.
```

**Comment by MingcongBai** [comment]
The log certainly did look normal... As it detects for both platforms and (hopefully) chose the right one?

**Comment by cthbleachbit** [comment]
Cannot reproduce here.

**Comment by MingcongBai** [comment]
This is actually quite old now. Let's have this closed, and if @lmy441900 if you would please, test this issue again.

**Comment by lmy441900** [comment]
@MingcongBai Fixed, closing.
