### ISSUE TITLE
xdg-utils: WTF is the version naming?

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#5]
Just explain the `869b22b75fc6e7c9e29ba5367bd97ebf7ce76cb3+git` stuff. 

You have to use a version that increments over time. See the ab3's defines for a brief versioning hack.

**Comment by MingcongBai** [comment]
Will add epoch.
2015年7月6日 下午6:12于 "Mingye Wang" <notifications@github.com>写道：

**Comment by MingcongBai** [comment]
Actually it was not a "will", it was already "fixed" accidentally by non-matching version number. I will simply rebuild that package on the server and tada.

Closing.
