### ISSUE TITLE
Blender missing libjasper.so.1

### ISSUE THREAD

**Issue by bobcao3** [AOSC-Dev/aosc-os-abbs#506]
`bobcao3@bobcao3 [ ~ ] $ ldd /usr/bin/blender | grep jasper
	libjasper.so.1 => /usr/lib/libjasper.so.1 (0x00007f0cfff67000)
bobcao3@bobcao3 [ ~ ] $ dpkg -L jasper | grep libjasper.so
/usr/lib/libjasper.so.4.0.0
/usr/lib/libjasper.so
/usr/lib/libjasper.so.4
bobcao3@bobcao3 [ ~ ] $ apt search jasper
Sorting... Done
Full Text Search... Done
jasper/os-amd64,now 1.900.28 amd64 [installed]
  Jasper JPEG2000

bobcao3@bobcao3 [ ~ ] $ `

**Comment by MingcongBai** [comment]
Mass rebuild underway.

**Comment by bobcao3** [comment]
`apt-cache rdepends jasper` Does not show Blender, but gegl is showned
