### ISSUE TITLE
pakreq: nginx modules

### ISSUE THREAD

**Issue by septs** [AOSC-Dev/aosc-os-abbs#517]
see http://labs.frickle.com/files/ngx_cache_purge-2.3.tar.gz
see http://labs.frickle.com/files/ngx_slowfs_cache-1.10.tar.gz
see https://github.com/Martchus/nginx-accesskey
see https://github.com/aperezdc/ngx-fancyindex
see https://github.com/arut/nginx-dav-ext-module
see https://github.com/arut/nginx-rtmp-module
see https://github.com/gnosek/nginx-upstream-fair
see https://github.com/masterzen/nginx-upload-progress-module
see https://github.com/nbs-system/naxsi
see https://github.com/openresty/echo-nginx-module
see https://github.com/openresty/headers-more-nginx-module
see https://github.com/openresty/lua-nginx-module
see https://github.com/stogh/ngx_http_auth_pam_module

x86 ONLY module
see https://github.com/pagespeed/ngx_pagespeed

**Comment by MingcongBai** [comment]
Woo hoo, right, I will try and chew through them.

**Comment by MingcongBai** [comment]
It's quite interesting that Arch/AUR only has **variants of Nginx**  bundling these modules... I wonder why?
