### ISSUE TITLE
apt: suggest aspcud & apt-cudf for dependency resolution

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#525]
The whole [external solver](http://www.dicosmo.org/MyOpinions/index.php?post/2014/10/30/139-saved-yet-another-time-by-an-external-solver-for-apt) stuff for apt looks pretty cool, especially with [user preferences](http://www.dicosmo.org/MyOpinions/index.php?post/2014/03/05/137-user-preferences-for-dependency-solvers-a-short-survey-and-new-features-added-in-the-latest-aspcud-solver) that can be configured in [`/etc/apt-cudf.conf`](http://www.dicosmo.org/MyOpinions/index.php?post/2012/05/24/122-using-external-solvers-with-apt-get-in-wheezy).

**Comment by liushuyu** [comment]
Probably this is not needed now.
