### ISSUE TITLE
kingsoft-office: remove bundled fonts

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#53]
For the sake of users in North America, please remove the bundled fonts.

**Comment by Arthur2e5** [comment]
So those fonts will be PKGRECOMed? With all those proprietary stuffs I am not sure if we can..

**Comment by butangmucat** [comment]
@Arthur2e5 I am not even sure if a split package can be used for these fonts. These fonts carry a very restrictive license that only allows the fonts to be used in the WPS programs ONLY and it also has regional limitations. We need further discussion on the legal issues before we ship these fonts.

**Comment by MingcongBai** [comment]
As it's been done. Closing.
