### ISSUE TITLE
terminology: PKGRECOM contains underscore

### ISSUE THREAD

**Issue by gumblex** [AOSC-Dev/aosc-os-abbs#545]
https://github.com/AOSC-Dev/aosc-os-abbs/blob/staging/extra-enlightenment/terminology/autobuild/defines#L4

Package name shall not contain _

**Comment by MingcongBai** [comment]
@LER0ever I think GitHub only takes "fixes"...

**Comment by LER0ever** [comment]
> @LER0ever I think GitHub only takes "fixes"...

Actually more than `fix` and `fixes`. [Closing issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/)

**Comment by MingcongBai** [comment]
@LER0ever I see.
