### ISSUE TITLE
tun/tap: a stub in filesystem after removed the old kernel

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#580]
That is, `/dev/net/tun` does not exist.

BTW, If there is no solution to restart this module immediately, would you add any warning or caution to somewhere for this?

**Comment by MingcongBai** [comment]
This is a tough question as we would need to know first, what is the component updated that resulted in this issue?

After which, a warning/notice shall be added.

**Comment by LionNatsu** [comment]
I guess it was kernel? I will test this in the next update of kernel package.

**Comment by Icenowy** [comment]
@LionNatsu did you do autoremove after upgrade?

**Comment by MingcongBai** [comment]
Well our Kernel update is not invasive as far as I'm concerned...

Oh wait are you talking about the sunxi line of releases?

2017年2月10日 10:48，"Icenowy Zheng" <notifications@github.com>写道：

**Comment by LionNatsu** [comment]
@Icenowy Yes, I did. `--autoremove` exactly.

**Comment by Icenowy** [comment]
@LionNatsu it's no wonder — as autoremove included, our kernel upgrade will act like Arch's, so please reboot

**Comment by MingcongBai** [comment]
But still it shouldn't do with anything in /dev should it?

**Comment by Icenowy** [comment]
@MingcongBai tun/tap is a kernel module

**Comment by MingcongBai** [comment]
But I wouldn't have though merely removing a kernel would  result in any changes in /dev?

**Comment by Icenowy** [comment]
@MingcongBai seems that the device file is only a stub — it loads a module when using

**Comment by MingcongBai** [comment]
Right... Let me just suppose that then. Let's wait till @LionNatsu gets his next kernel update and see if it happens. If so, I will close with `wontfix`.

**Comment by LionNatsu** [comment]
![photo_2017-02-11_01-43-47](https://cloud.githubusercontent.com/assets/6694582/22837630/638cd290-effc-11e6-86cd-42230556c8fa.jpg)

I think I need a notice for this Bizarre Natural Phenomenon.

@Icenowy You're right. It is a stub.

**Comment by MingcongBai** [comment]
> I think I need a notice for this Bizarre Natural Phenomenon.

As in notifying users that if they remove the old kernels whilst running that particular kernel (confusion), they are likely to run into issues such as... this?

See, we need an Errata page right about now...

**Comment by MingcongBai** [comment]
@LionNatsu Input needed, if not, please close this issue...

**Comment by LionNatsu** [comment]
Are there any ways to remove that stub?

**Comment by Icenowy** [comment]
@LionNatsu I think it doesn't need to be removed

**Comment by LionNatsu** [comment]
@LionNatsu Shall we address it as a little kernel bug…？

**Comment by MingcongBai** [comment]
> @LionNatsu Shall we address it as a little kernel bug…？

@Icenowy Needing your verdict here.

**Comment by MingcongBai** [comment]
Stale issue with no further information providence. Closing.
