### ISSUE TITLE
pakreq: PSPP

### ISSUE THREAD

**Issue by lmy441900** [AOSC-Dev/aosc-os-abbs#589]
> PSPP is a free software application for analysis of sampled data, intended as a free alternative for IBM SPSS Statistics. It has a graphical user interface and conventional command-line interface. It is written in C and uses GNU Scientific Library for its mathematical routines.
> -- _Wikipedia https://en.wikipedia.org/wiki/PSPP_

Official site https://www.gnu.org/software/pspp/
Source code download https://mirrors.ustc.edu.cn/gnu/pspp/ (Ouch, officially jumped to here...)

And, kindly

```
 ____                           _           _   _           
|  _ \ _ __ ___  ___  ___ _ __ | |_ ___  __| | | |__  _   _ 
| |_) | '__/ _ \/ __|/ _ \ '_ \| __/ _ \/ _` | | '_ \| | | |
|  __/| | |  __/\__ \  __/ | | | ||  __/ (_| | | |_) | |_| |
|_|   |_|  \___||___/\___|_| |_|\__\___|\__,_| |_.__/ \__, |
                                                      |___/ 
  ____ _   _ _   _ 
 / ___| \ | | | | |
| |  _|  \| | | | |
| |_| | |\  | |_| |
 \____|_| \_|\___/ 
                   
```

**Comment by Artoria2e5** [comment]
Yay! PSPP is awesome.
