### ISSUE TITLE
pakreq: k2pdfopt

### ISSUE THREAD

**Issue by RedL0tus** [AOSC-Dev/aosc-os-abbs#594]
`K2pdfopt re-flows text from multi-column PDF/DJVU files for e-readers and smartphones`

Homepage: http://www.willus.com/k2pdfopt/
GitHub: https://github.com/JohannesBuchner/k2pdfopt

**Comment by MingcongBai** [comment]
This utility/library seemed to be out of maintenance and it certainly is not compatible with our new Jasper and MuPDF libraries...

Ports needed.

**Comment by MingcongBai** [comment]
Closing, no hope.
