### ISSUE TITLE
udev: make device node permission control more speicified

### ISSUE THREAD

**Issue by Icenowy** [AOSC-Dev/aosc-os-abbs#597]
Some devices currently do not have special group, e.g. I2C.

Some of them are worth to be granted access by some new special groups, for example, some group can get the capability automatically to I2C. This is especially useful for some embedded situations (although at least PCs with Intel HD Graphics 3000/4000 and a VGA port can have a usable I2C bus)

**Comment by MingcongBai** [comment]
Any input on this?

**Comment by MingcongBai** [comment]
Stalled (feature/design change) issue, closing. Please open a new issue if this thought arises again.
