### ISSUE TITLE
gtk-2 missing libdep libgdk_pixbuf-2.0.so.0

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#6]
gtk-update-icon-cache: error while loading shared libraries: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by Arthur2e5** [comment]
gtk-query-immodules-2.0 is also down.

**Comment by Arthur2e5** [comment]
Also killing vim.
Falling back to busybox vi.

**Comment by MingcongBai** [comment]
@Arthur2e5 Can you try reinstalling ```gdk-pixbuf``` and ```gtk-2```? I can't really reproduce that on my new install.

**Comment by Arthur2e5** [comment]
@MingcongBai The real problem is that `gdk-pixbuf` is not even installed. There must be a missing PKGDEP.

**Comment by MingcongBai** [comment]
@Arthur2e5 Sorry, I misinterpreted your issue.

**Comment by MingcongBai** [comment]
Fixed as of f5856ebe1f77643c7b728a238bd4257c27b4b1e1.
