### ISSUE TITLE
extra-utils/blueman: polikt related failure

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#606]
AOSC Core 4.2.1, blueman 2.0.4-3

Whenever blueman-applet launches, the following message is displayed, but one can still connect to Bluetooth devices and function as normal.

![blueman-exception](https://cloud.githubusercontent.com/assets/1846907/24391283/1b0df8e0-135c-11e7-9d3f-21a9e46c3605.jpg)

**Comment by MingcongBai** [comment]
It is a known issue... Couldn't figure out what's wrong there. Alternatively, try and use `blueberry` for now.

**Comment by MingcongBai** [comment]
Still need help on this...

**Comment by MingcongBai** [comment]
Is this fixed with the newest update? @butangmucat

**Comment by MingcongBai** [comment]
This is now working.
