### ISSUE TITLE
extra-mono/mono: possible winform-related issue making KeePass unusable

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#607]
KeePass (which uses Mono for execution on Linux) has its UI (fonts) completely distorted, both in the version built from extra-security/keepass and the official binary.

Here is a screenshot of KeePass built from extra-security/keepass:
![keepass-aosc](https://cloud.githubusercontent.com/assets/1846907/24391325/68c42942-135c-11e7-90f9-f53a8dfc507c.jpg)

Here is a screenshot of the official KeePass binary:
![keepass-official](https://cloud.githubusercontent.com/assets/1846907/24391331/732da7be-135c-11e7-887a-793d168000ce.jpg)

**Comment by MingcongBai** [comment]
Might ve libgdiplus related.

**Comment by butangmucat** [comment]
Arch Linux built libgdiplus with "--with-cairo=system" however this should not matter as our libgdiplus does have a dependency on cairo when examined with ldd. Also the latest mono release is 4.8.0.520, wounder if this will contain related bugfixes.

**Comment by MingcongBai** [comment]
> Arch Linux built libgdiplus with "--with-cairo=system" however this should not matter as our libgdiplus does have a dependency on cairo when examined with ldd. Also the latest mono release is 4.8.0.520, wounder if this will contain related bugfixes.

But it actually worked fine before... Could you do a test build with Cairo instead of Pango and see what happens?

**Comment by butangmucat** [comment]
fixed.
