### ISSUE TITLE
Remove Hard-coded Package Dependencies

### ISSUE THREAD

**Issue by late-in-autumn** [AOSC-Dev/aosc-os-abbs#610]
Certain packages may rely on system components like `cron` or `mta`, and it is possible that multiple implementations exist. For example, both `fcron` and `systemd-cron-next` provides `cron` and both `opensmtpd` and `postfix` provides `mta`. It is worth considering removing hardcoded dependencies like these dependencies for `fcron` as in `packagekit` for these virtual packages, adding flexibility on the user end.

**Comment by MingcongBai** [comment]
Stalled (feature/design change) issue, closing. Please open a new issue if this thought arises again.
