### ISSUE TITLE
Some typos in wiki.

### ISSUE THREAD

**Issue by ensigma96** [AOSC-Dev/aosc-os-abbs#614]
I found some typos in the [wiki](https://github.com/AOSC-Dev/aosc-os-abbs/wiki) with `aspell` and other tools, corrected them, and put the modified version [here](https://github.com/ensigma96/aosc-os-abbs-wiki-forked) (because one cannot make PRs to wikis on github).

**Comment by MingcongBai** [comment]
Well this could be hard to merge with proper committer... @lmy441900 Any ideas on how to handle this?

**Comment by lmy441900** [comment]
@MingcongBai May be able to perform a local merge.

**Comment by MingcongBai** [comment]
@ensigma96 : @lmy441900 will be helping with merging the changes very soon, thank you for your contribution. For you contribution, you are eligible for a personal page on our community portal, as seen [here](https://aosc.io/people/) - I will provide you with the details on configuring your personal page via e-mail.

**Comment by ensigma96** [comment]
Is this method of proposing changes to repo wiki (learned from [stackoverflow](http://stackoverflow.com/a/11481887)) causing problems for merging? For when it comes to typo checking, it would be convenient to clone the wiki and do batch work locally, so I‘d like to know if there is any recommended way for contributing in such cases.

**Comment by MingcongBai** [comment]
Well, as how GitHub implements the Wiki system, the best we could do is to invite you to our organization (sending an invitation now), or to add you as a collaborator of this repo.

**Comment by lmy441900** [comment]
Merged. Closing.
