### ISSUE TITLE
dracut: jump ship to dracut-ng

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#6194]
Arch Linux has jumped ship to dracut-ng over a stagnant upstream. Do we\* want to follow?

https://archlinux.org/packages/extra/x86_64/dracut/
https://github.com/dracut-ng/dracut-ng

\* I say "we", but everyone knows I'm not contributing. I'm one of those 2 people in your group project.

**Comment by MingcongBai** [comment]
Addressed in https://github.com/AOSC-Dev/aosc-os-abbs/pull/6565. Closing.
