### ISSUE TITLE
meta: provide standard `editor` and `pager` alternatives

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#622]
To provide a standardized and open-box experience for certain programs, and to prevent recurrence of #393, it is suggested by @Icenowy to provide standard `editor` and `pager` alternative symlinks to `/usr/bin/editor` and `/usr/bin/pager`, respectively.

Plan of action:

- [ ] Enable alternatives on command-line editors and pagers (`vi`, `nano`, etc), and set all alternative to `50`.
- [ ] Check on programs and fix hard-coded editor/pager specifications (say, `git`).

Current issues:

- Upon upgrade (with fixed alternatives), given the same alternative priority, users may be expecting changes on `/usr/bin/editor` which are unexpected/not to their preferences.
- (Could be more).

**Comment by gumblex** [comment]
Where's pagers?

**Comment by MingcongBai** [comment]
@gumblex We only have less right now, if someone pakreqs more, then yes, there will be another one.

**Comment by gumblex** [comment]
We already have less, more, most, w3m

**Comment by MingcongBai** [comment]
Right, but for the record, `more` is not here.

**Comment by gumblex** [comment]
more is in util-linux

**Comment by MingcongBai** [comment]
Oops.

**Comment by MingcongBai** [comment]
Done.

**Comment by gumblex** [comment]
Why set those pagers all 80, since `less` is superior to `more`?

**Comment by MingcongBai** [comment]
I did not realize the breakage... So, `less` at 80, `more` at 50, `w3m` at 30?

**Comment by gumblex** [comment]
less > most > more > w3m?

**Comment by MingcongBai** [comment]
Sounds reasonable enough.
