### ISSUE TITLE
fcitx-kkc: crash 

### ISSUE THREAD

**Issue by late-in-autumn** [AOSC-Dev/aosc-os-abbs#630]
`fcitx-kkc` version: 0.1.2-1 (local rebuild with latest version of buildkit, updated Apr 25 2016)

When switching to Kana Kanji IME, Fcitx crashes and reloads itself, then the Kana Kanji IME disappears. Tried to run Fcitx from terminal, no error output was given.

**Comment by MingcongBai** [comment]
No longer reproducible. Closing.
