### ISSUE TITLE
linux-kernel: doesn't regenerate grub entries on non-extfs

### ISSUE THREAD

**Issue by ekd123** [AOSC-Dev/aosc-os-abbs#636]
Every time I upgrade linux-kernel, it will fail to regenerate grub entries, complaining "GRUB is not installed or in container/chroot, skipping regeneration of GRUB menu."

I checked the postinst and postrm scripts, 
```        if [[ $(uname -m) = x86_64 ]]; then
                if [[ -x /usr/bin/grub-mkconfig && $(stat -c %i /) == 2 && \
                      ! $(grep 'machine' /proc/1/cgroup) && ! $(grep 'docker' /proc/1/cgroup) ]]; then
                        grub-mkconfig -o /boot/grub/grub.cfg
                else
                        echo "GRUB is not installed or in container/chroot, skipping regeneration of GRUB menu."
                fi
        fi
```
However, the inode of the root directory doesn't necessarily have to be 2 if the filesystem is not ext4 [1]. Btrfs, for example, the inode is not 2 [2]. This should be considered a bug.

[1] https://ext4.wiki.kernel.org/index.php/Ext4_Disk_Layout
[2] Here the inode of / is 256, and 2 is for /boot.

**Comment by MingcongBai** [comment]
Will deal with this when I upgrade GRUB to 2.02 final.

**Comment by MingcongBai** [comment]
This was addressed long ago. Closing.
