### ISSUE TITLE
zsh: unexpected lag when Ctrl+E is pressed

### ISSUE THREAD

**Issue by ensigma96** [AOSC-Dev/aosc-os-abbs#638]
There is an unexpected lag (around/less than 0.5s) after `^E` is pressed, before the cursor (as expected) moves to the end of a line. For comparison, `^A` works perfectly, as the cursor moves instantly to the beginning of a line. 

`zsh --version` returns `zsh 5.3.1 (x86_64-aosc-linux-gnu)` .

This slightly annoying behavior could also be reproduced under Ubuntu 16.04 (zsh 5.1.1) by replacing `.zshrc` with grml's zsh configuration (which is shipped with AOSC OS's `zsh` package):

```
cd $HOME
cp .zshrc .zshrc_before_grml
wget -O .zshrc http://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
```

---

Some additional information:

`bindkey | fgrep '^E'` returns

```
"^E" end-of-line
"^Ed" insert-datestamp
"^X^E" edit-command-line
```

When the key binding of `^Ed` is removed, the lag also disappears, and when it is re-added, the lag re-appears.

`bindkey | fgrep '^A'` returns 

```"^A" beginning-of-line``` .

**Comment by butangmucat** [comment]
@ensigma96 No description

**Comment by MingcongBai** [comment]
@butangmucat Any update?

**Comment by butangmucat** [comment]
I am actually not quite sure where to report this. Digging their site.

**Comment by MingcongBai** [comment]
@butangmucat If not... I would suggest dropping it.

**Comment by butangmucat** [comment]
@MingcongBai Well I did find an email address.

**Comment by MingcongBai** [comment]
No longer an issue after grml configs are removed from the package with the latest change to `extra-shell/zsh`.
