### ISSUE TITLE
crontab command get permission denied

### ISSUE THREAD

**Issue by zwg-zero** [AOSC-Dev/aosc-os-abbs#6393]
### Bug description

when normal user run the command "crontab -e", after adding some content and then save and exit the editor, it gave error message: ERROR could not open file laofa.orig.tmp: Permission denied

### reproduce
1. login to a normal user's desktop
2. open konsole
3. run command "crontab -e" and enter the editor
4. add any correct content, like "2 * * * * echo xxx", save and exit the editor
5. get error message: 
 `2024-05-31 22:35:03  INFO fcrontab : editing laofa's fcrontab
no fcrontab for laofa - using an empty one
2024-05-31 22:35:30 ERROR could not open file laofa.orig.tmp: Permission denied
`
### fixing
1. sudo chown fcron:fcron /var/spool/fcron
2. sudo chmod g+w /var/spool/fcron

### Update channel(s)

none

### Package and version

```bash
Package: fcron
Status: install ok installed
Section: admin
Installed-Size: 1608
Maintainer: Mingcong Bai <jeffbai@aosc.io>
Architecture: loongarch64
Version: 3.3.0-1
Provides: cron
Depends: linux-pam (>= 1.5.2), debianutils (>= 5.7)
Suggests: mta
Conffiles:
 /etc/fcron/fcron.allow 93d3d6c83b3a63100d27d0a55dbf611d
 /etc/fcron/fcron.conf 9bdea65dacd7454a4fe06e0b377b6448
 /etc/fcron/fcron.deny 30d070acb371209bb6f3035d2390dadf
 /etc/fcron/pam.conf 12d3108f36fd343196b49e1d4c7d92f3
 /etc/pam.d/fcron 2090d6ff64e2c1a037f3c196b8f2e882
 /etc/pam.d/fcrontab f659349d3f24fa1b57684af8f495efe6
Description: A feature-rich Cron implementation
X-AOSC-ACBS-Version: 20221105
X-AOSC-Commit: b1b9ac7bd0-dirty
X-AOSC-Packager: Mingcong Bai <jeffbai@aosc.io>
X-AOSC-Autobuild3-Version: 2:1.6.107
```

**Comment by MingcongBai** [comment]
This has been addressed in the recent pull requests:

- #6528 
- #6718
