### ISSUE TITLE
KDE5 Desktop Wallpaper Thumbnails Broken

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#64]
See details in my screenshot. Wallpaper thumbnails are broken, but Dolphin thumbnails are fine.
![6](https://cloud.githubusercontent.com/assets/1846907/9244336/e983499a-41cc-11e5-8860-898b5429e82b.png)

**Comment by MingcongBai** [comment]
Seems to be fixed upon update to KDE Frameworks 5.15 (using a KDE Plasma tarball).
