### ISSUE TITLE
rebuild: packages which have "go(<1.8)" as build-time dependencies

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#643]
`glide` uses SSL with SHA256, and it always dies on my computer.

Search result in GitHub
```
extra-database/mongodb-tools/autobuild/defines
extra-security/keybase/autobuild/defines
extra-network/syncthing/autobuild/defines
extra-network/kcptun/autobuild/defines
extra-shells/elvish/autobuild/defines
extra-go/glide/autobuild/defines
extra-vcs/hub/autobuild/defines
extra-network/obfs4proxy/autobuild/defines
extra-network/gost/autobuild/defines
extra-go/godep/autobuild/defines
extra-doc/go-md2man/autobuild/defines
```

**Comment by MingcongBai** [comment]
I do apologize but I could not build all packages listed above for obvious connectivity issues. But for the matter of `glide`, it's done.

**Comment by LionNatsu** [comment]
Maybe we should keep this open…

**Comment by MingcongBai** [comment]
@LionNatsu Maybe, but as another issue to show as a note.

**Comment by LionNatsu** [comment]
@MingcongBai Well, I reopened this. This IS a rebuild note…

**Comment by KexyBiscuit** [comment]
@MingcongBai I think you have done this?

**Comment by MingcongBai** [comment]
@KexyBiscuit Indeed, this has become a standard protocol in groups/go-rebuild.

**Comment by KexyBiscuit** [comment]
Closing.
