### ISSUE TITLE
TODO: add Condition* to systemd service units (for BuildKit)

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#649]
Reason
---------
Some services can only work on certain targets, so we need to disable them on other targets, when we create distributions. For example, `gpm.service` cannot run on systemd-nspawn container where the Buildkit usually is. The better way is: investigate that how it failed, and add the powerful Conditions[1] into services.

There are `ConditionArchitecture=, ConditionVirtualization=, ConditionHost=, ConditionKernelCommandLine=, ConditionSecurity=, ConditionCapability=, ConditionACPower=, ConditionNeedsUpdate=, ConditionFirstBoot=, ConditionPathExists=, ConditionPathExistsGlob=, ConditionPathIsDirectory=, ConditionPathIsSymbolicLink=, ConditionPathIsMountPoint=, ConditionPathIsReadWrite=, ConditionDirectoryNotEmpty=, ConditionFileNotEmpty=, ConditionFileIsExecutable=`

[1] https://www.freedesktop.org/software/systemd/man/systemd.unit.html#ConditionArchitecture=

Method of Investigating and Adding Condition
---------
Take a failed service `gpm` as my example.
We may firstly check the unit file: `systemctl cat gdm`
```ini
# /usr/lib/systemd/system/gpm.service
[Unit]
Description=Virtual console mouse server

[Service]
Type=forking
ExecStart=/usr/sbin/gpm -m /dev/input/mice -t imps2

[Install]
WantedBy=multi-user.target
```

It seems it  need to access `/dev/input/mice` which probably doesn't exist in a container. Let's confirm that.
```
root@buildkit [ ~ ] ! ls /dev/input/mice
ls: cannot access '/dev/input/mice': No such file or directory
```

Now we know the key, the condition of starting service, is whether `/dev/input/mice`can be read, or exists.  So now add `ConditionPathExists=/dev/input/mice` into `/usr/lib/systemd/system/gpm.service`

```ini
[Unit]
Description=Virtual console mouse server
ConditionPathExists=/dev/input/mice

[Service]
Type=forking
ExecStart=/usr/sbin/gpm -m /dev/input/mice -t imps2

[Install]
WantedBy=multi-user.target
```

Result:
```
root@buildkit [ ~ ] # systemctl daemon-reload && systemctl status gpm
● gpm.service - Virtual console mouse server
...
Condition: start condition failed at Fri 2017-06-02 22:55:55 CST; 49ms ago
           └─ ConditionPathExists=/dev/input/mice was not met
...
```

List
----
To be continued...

**Comment by LionNatsu** [comment]
There is a part of the recipe of creating BuildKit.
  - all
    - [ ] gpm
    - [ ] NetworkManager
    - [ ] NetworkManager-dispatcher
    - [ ] ModemManager
    - [ ] fc-cache
    - [ ] bluetooth
    - [ ] systemd-timesyncd
    - [ ] lvm2-monitor
    - [ ] sshd
  - amd64
    - [ ] tlp
    - [ ] tlp-sleep
    - [ ] acpid

**Comment by LionNatsu** [comment]
`NetworkManager` needs capabilities `CAP_NET_ADMIN`.
`NetworkManager-dispatcher` will exit automatically after 10s if there is no `NetworkManager`.

**Comment by LionNatsu** [comment]
Removing sshd from the list.

**Comment by LionNatsu** [comment]
Removing sshd from the list.

**Comment by MingcongBai** [comment]
Just as a note, we should try and contact upstream(s) regarding these changes - as they are not specific to AOSC OS, and many others should benefit from more scientifically crafted units.

**Comment by MingcongBai** [comment]
As noted above, and with no further input. Closing.
