### ISSUE TITLE
update-alternatives: broken under rpm systems

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#65]
Original issue here: https://github.com/AOSC-Dev/autobuild3/issues/44

When update-alternatives are invoked in rpm packages:

*update-alternatives: error: cannot scan directory '/var/lib/dpkg/alternatives': No such file or directory*

Currenlty update-alternatives is totally broke in rpm systems.

**Comment by MingcongBai** [comment]
A simple fix will be to add essential directories by `update-alternatives` package. Changes are currently in `dev/new-packages` branch.

**Comment by Arthur2e5** [comment]
test integram reply

**Comment by MingcongBai** [comment]
Merged `master`, closing.
