### ISSUE TITLE
pakreq: acbs

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#651]
(and drop `abbs` from tree maybe)

**Comment by lmy441900** [comment]
@LionNatsu abbs is still used. (e.g. AOSC-Dev/linux-kernel-extra since acbs cannot recognize non-abbs directory names.) However manually install abbs or acbs can be very simple, I must say.

**Comment by MingcongBai** [comment]
Added with ebfab97c54392919317479bae5f4ebbe2ab9acda. Coming in July Wave, closing.
