### ISSUE TITLE
gcc: illegal instruction on AMD ryzen

### ISSUE THREAD

**Issue by cthbleachbit** [AOSC-Dev/aosc-os-abbs#661]
#### What happened

On compiling linux kernel 4.11.6 in tree after commit 1d860787.

```
In file included from ./include/uapi/linux/signal.h:4:0,
                 from ./include/linux/signal_types.h:9,
                 from ./include/linux/signal.h:5,
                 from drivers/usb/misc/sisusbvga/sisusb.c:42:
./arch/x86/include/asm/signal.h:37:30: internal compiler error: Illegal instruction
 extern void do_signal(struct pt_regs *regs);
                              ^~~~~~~
  CC [M]  drivers/staging/lustre/lustre/fid/fid_request.o
```

#### Sources

* [Upstream 4.11.6 source xz](https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.11.6.tar.xz)
* [Patches folder](https://github.com/AOSC-Dev/aosc-os-abbs/tree/1d86078701cc3fe41a0bbe839a45e41143cae478/extra-kernel/linux-kernel/autobuild/patches) 
* [Kernel config](https://github.com/AOSC-Dev/aosc-os-abbs/blob/1d86078701cc3fe41a0bbe839a45e41143cae478/extra-kernel/linux-kernel/autobuild/amd64/config)

#### System info
```
# gcc --version
gcc (GCC) 6.3.0 20161221 (AOSC OS, Core)
# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 1
Model name:            AMD Ryzen 5 1500X Quad-Core Processor
Stepping:              1
CPU MHz:               1550.000
CPU max MHz:           3500.0000
CPU min MHz:           1550.0000
BogoMIPS:              6989.71
Virtualization:        AMD-V
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 mwaitx hw_pstate vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic overflow_recov succor smca
````

**Comment by cthbleachbit** [comment]
#### Extra testing info
With the same set of patches and kernel config, 4.11.5 builds without problem.

#### Extra hardware info
Motherboard Gigabyte GA-AB350-Gaming Rev 1
Firmware AGESA 1.0.0.6

**Comment by MingcongBai** [comment]
This issue, according to @cthbleachbit - could not be reproduced after re-upgrading AGESA the second time, to the same 1.0.0.6 version.

**Comment by cthbleachbit** [comment]
This did not happen for 3 months. If anyone else using AMD ryzen has this problem during compilation please re-open.

**Comment by xiangzhai** [comment]
@cthbleachbit and it is better to use GCC 8.x master branch to reproduce :)

**Comment by xiangzhai** [comment]
@MingcongBai please Cc Toolchain (GCC and LLVM) relative issues to me, thanks!

**Comment by MingcongBai** [comment]
Will keep that in mind. However, this is a known issue with the first batch of Ryzen processors... A hardware flaw really.

**Comment by xiangzhai** [comment]
@MingcongBai 现在流行CPU的锅由编译器来背 :)
