### ISSUE TITLE
nm: work with systemd-resolved

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#667]
Now we have an active resolved service provided by systemd, but it cannot handle name resolving because Network Manager took over the resolv.conf. According to its configure script's help message, this behaviour can be disabled by arguments (switches). Investigating...

**Comment by MingcongBai** [comment]
Yes?

**Comment by LionNatsu** [comment]
To be continued.

**Comment by lmy441900** [comment]
AMD64 packages built and uploaded.
