### ISSUE TITLE
kdeconnect: cannot send file to mobile phone

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#668]
When I tried to send some file by the right-click menu...

```
(journalctl --user)
kdeconnectd[3827]: kdeconnect.core: Error opening a port in range 1739-1764 for file transfer
```

Reproducible here by command line.
```
kdeconnect-cli -d 861155f8ce????? --share /home/lion/atextfile
```

Version: kdeconnect/os-amd64,now 1.0.2

No firewall, nothing was sitting on these ports.

**Comment by LionNatsu** [comment]
I can't reproduce now, yes, without restarting the computer. Very strange.
The code, where reported this error message, may be helpful for debugging.

**Comment by MingcongBai** [comment]
Could it be related to LAN settings? I have heard that from @LER0ever .

**Comment by LionNatsu** [comment]
No idea. But I did change QoS setting on router.

**Comment by liushuyu** [comment]
Marking as resolved since unable to reproduce
