### ISSUE TITLE
一些32位程序崩溃

### ISSUE THREAD

**Issue by startmenu** [AOSC-Dev/aosc-os-abbs#67]
比如Wine32，一运行就崩溃。 
aosc [ ~ ] ! winecfg
wine: loadlocale.c:130: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_COLLATE) / sizeof (_nl_value_type_LC_COLLATE[0]))' failed.
已放弃 (核心已转储)

疑似是32subsys的glibc问题

**Comment by MingcongBai** [comment]
@startmenu 更新 glibc+32 为 2.21 后，问题不复存在。54f39f143ec368739c604e82a66a8694132630e4 感谢报告。
