### ISSUE TITLE
shadow: invalid systemd config

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#676]
https://github.com/AOSC-Dev/aosc-os-abbs/blob/e30619c955fe9514ecc0315d0d6ebcf70c7ff470/base-admin/shadow/autobuild/overrides/usr/lib/systemd/system/multi-user.target.wants/shadow.timer
```
../shadow.timer
```

This is invalid.

> multi-user.target: Wants dependency dropin /usr/lib/systemd/system/multi-user.target.wants/shadow.timer is not a symlink, ignoring.

**Comment by Artoria2e5** [comment]
Did someone's git somehow forgot to keep the link property?

**Comment by MingcongBai** [comment]
Will have this fixed in `bugfix`.

**Comment by MingcongBai** [comment]
Fixed in https://github.com/AOSC-Dev/aosc-os-abbs/commit/87e8886ab42c0e3663044bd8df8eb3e22c6ca99e.
