### ISSUE TITLE
pakreq: super pi

### ISSUE THREAD

**Issue by septs** [AOSC-Dev/aosc-os-abbs#695]
see http://superpi.ilbello.com/

**Comment by StephDC** [comment]
Reject for permission issue:

> super_pi     : Shell script for running super_pi program under the 
>                terminal mode of Mac OS/X.
> pi           : Execution module called by the super_pi.
> Readme.txt   : Explanation text file for the super_pi.
> 
> Attention : All of the above mentioned files are not permitted for the
>             re-distribution.

So we could not re-distribute those files.

**Comment by MingcongBai** [comment]
Closing, redistribution not allowed.
