### ISSUE TITLE
Use GNU which instead of debianutils which

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#7]
DEBIANUTILS WHICH DOES! NOT! SUPPORT! `-i`! What the f…

**Comment by MingcongBai** [comment]
@Arthur2e5 Calm down, this will be fixed before midnight today...

**Comment by Arthur2e5** [comment]
Fixed?

**Comment by MingcongBai** [comment]
@Arthur2e5 please allow sometime, also looking for a more reliable version inequality parsing support.

**Comment by MingcongBai** [comment]
Time is allowed till tonight.
