### ISSUE TITLE
firefox: using system png likely kills APNG support

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#707]
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=486827. We can also go a bit further and package a "libpng-moz".

**Comment by MingcongBai** [comment]
Though I should point out that...

1. Our "system" LibPNG does have APNG patches applied.
2. The loading spinner, which is an APNG, does work properly for our builds.

Am I missing anything here?

**Comment by Artoria2e5** [comment]
hmm, we good then.
