### ISSUE TITLE
git: security update to 2.13.6 or 2.14.2

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#709]
See http://www.openwall.com/lists/oss-security/2017/09/26/9.

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/77f570a1c97184009f962389f1557c2ff100c181.

**Comment by l2dy** [comment]
Use AOSA-2017-0087.
