### ISSUE TITLE
firefox: security update to 56.0 and 52.4.0esr

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#737]
https://www.mozilla.org/en-US/security/advisories/mfsa2017-21/
https://www.mozilla.org/en-US/security/advisories/mfsa2017-22/

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/f9fb7ede3b5446c51a4073a6fb25e67a9dbda890. Closing.

**Comment by l2dy** [comment]
Use AOSA-2017-0131.
