### ISSUE TITLE
postgresql: security update to >9.6.3

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#751]
https://www.postgresql.org/docs/9.6/static/release-9-6-4.html

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/9daab34d445b5c3d8907c81d84d9775126634364. Closing.

**Comment by l2dy** [comment]
Use AOSA-2017-0109.
