### ISSUE TITLE
wavpack: security update to 5.1.0

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#754]
http://www.openwall.com/lists/oss-security/2017/01/23/4
http://www.openwall.com/lists/oss-security/2017/01/28/9

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/f2c57d9a2d1037cf98c4f182029405180f9d7f03. Closing.

**Comment by l2dy** [comment]
Use AOSA-2017-0112.
