### ISSUE TITLE
openjdk: security update to 8u144 or 9

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#756]
http://www.oracle.com/technetwork/security-advisory/cpuapr2017-3236618.html#AppendixJAVA
http://www.oracle.com/technetwork/security-advisory/cpujul2017-3236622.html#AppendixJAVA

**Comment by MingcongBai** [comment]
@liushuyu However that would be a staging change, I will try and make a u144 update tonight.

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/fff93f789976e113dd7618be948760edca666f3a. Closing.

**Comment by l2dy** [comment]
Use AOSA-2017-0116.
