### ISSUE TITLE
gnupg missing dependency

### ISSUE THREAD

**Issue by ekd123** [AOSC-Dev/aosc-os-abbs#77]
npth is missing in the default install of gnupg, which leads to the following failure.

gpg-agent: error while loading shared libraries: libnpth.so.0: cannot open shared object file: No such file or directory

gpg: can't connect to the agent: IPC connect call failed

**Comment by Arthur2e5** [comment]
PR it.

**Comment by MingcongBai** [comment]
#81 Fixes the issue, closing.
