### ISSUE TITLE
libevent: security update to 2.1.8

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#780]
https://www.debian.org/security/2017/dsa-3789
https://security.gentoo.org/glsa/201705-01

Or backport...

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/1d5ca7a18b5a1a15124d9a66b05aaca3e2240182. Closing.

**Comment by l2dy** [comment]
Use AOSA-2017-0135.
