### ISSUE TITLE
Issues with both Generation 1 and Generation 2 Hyper-V Guests

### ISSUE THREAD

**Issue by lunzima** [AOSC-Dev/aosc-os-abbs#7832]
### Bug description

Xorg refuses to start on Generation 1 and Generation 2 Hyper-V guests and 6.10.x kernels.
On Generation 2 guests, blacklisting hyperv_fb resolves the issue.
On Generation 1 guests, blacklisting hyperv_drm resolves the issue. Downgrading the Linux kernel is required if the hyperv_fb kernel module is not included in the kernel.
In some cases, framebuffer corruption of the virtual machine can be observed using the combination of Generation 1 guests + hyperv_drm.

### Steps to reproduce

Install AOSC OS with Hyper-V then wait for OS starting up for the first time after installation is complete.
My Windows Host is running Windows 11 version 23H2. @KexyBiscuit 

### Update channel(s)

stable

### Package and version

```bash
linux-kernel-6.10.x
```

**Comment by KexyBiscuit** [comment]
For generation 2 virtual machines in Hyper-V, the problem has been existed not later than `linux-kernel-5.11.1`.

Another workaround for generation 2 virtual machines in Hyper-V is to disable the splash screen of Plymouth.

**Comment by KexyBiscuit** [comment]
The problem of generation 2 virtual machines in Hyper-V is actually caused by #6126. After reverting #6126, the splash screen still doesn't appear, but the login screen works well.

**Comment by KexyBiscuit** [comment]
Part of the problem of generation 1 virtual machines in Hyper-V is also caused by https://github.com/AOSC-Dev/aosc-os-abbs/pull/6126. After reverting https://github.com/AOSC-Dev/aosc-os-abbs/pull/6126, the splash screen still doesn't appear, but the login screen works well.

**Comment by KexyBiscuit** [comment]
Confirmed that [Red Hat Bugzilla – Bug 2000921](https://bugzilla.redhat.com/show_bug.cgi?id=2000921) contains the fix for `hyperv_drm` driver plus `xorg-server` on generation 1 virtual machines in Hyper-V.

I prefer to remove `hyperv_fb` driver to mitigate the Plymouth splash screen issue, since that's also what Microsoft recommends.

Ref: https://access.redhat.com/downloads/content/xorg-x11-server-Xorg/1.20.11-10.el9/x86_64/fd431d51/package

**Comment by lunzima** [comment]
With the RHEL patch for Xorg, hyperv_drm now works for Gen1 guests.
![D4B2FF8106986F38B094D82771EF4811](https://github.com/user-attachments/assets/635c5d81-e6db-4135-8687-628c7b9807e7)
Plymouth works too with enabled downgrade topic.

Please retire hyperv_fb for kernel config so hyperv_drm will work out-of-box.

**Comment by lunzima** [comment]
![cef5deb07632fd3319dacd35698adb12](https://github.com/user-attachments/assets/68b53403-0334-4812-8906-6f897e8833e7)
With topic xorg-server-21.1.13-hyperv-drm-fix the issue mentioned above is fixed too.

**Comment by MingcongBai** [comment]
Very well.
