### ISSUE TITLE
forgejo: update to 8.0.2

### ISSUE THREAD

**Issue by xtexx** [AOSC-Dev/aosc-os-abbs#7836]
### Affected package (and version)

`forgejo` (8.0.1)

### CVE ID(s)

N/A

### Severity

Low

### Other security advisory ID(s）

- Bug report: [forgejo/forgejo#5149](https://codeberg.org/forgejo/forgejo/pulls/5149)

### Description/References

- Bug report: [forgejo/forgejo#5128](https://codeberg.org/forgejo/forgejo/issues/5128)
- Upstream fix: [forgejo/forgejo#5149](https://codeberg.org/forgejo/forgejo/pulls/5149)
- Severity is low because this is a bug of failing to enforce token scope, not a bug of scope escalation.

### Patch(es)/Solution(s)

Update to 8.0.2

**Comment by stdmnpkg** [comment]
see #7855

**Comment by MingcongBai** [comment]
Addressed in #7855 (merged). Closing.
