### ISSUE TITLE
amule missing dependency

### ISSUE THREAD

**Issue by ekd123** [AOSC-Dev/aosc-os-abbs#79]
It seems that the library is not in the repository this time.

amule: error while loading shared libraries: libbfd-2.25.so: cannot open shared object file: No such file or directory

ldd says:
	libbfd-2.25.so => not found

**Comment by Arthur2e5** [comment]
PR PR PR PR
ask apt search

**Comment by MingcongBai** [comment]
@Arthur2e5 This is a rebuild, because `binutils` updated to 2.25.1.

```
aosc [ ~ ] $ dpkg -S libbfd-2.25
binutils: /usr/lib/libbfd-2.25.1.so
```

A rebuild will be needed. But just a simple bump.

**Comment by Icenowy** [comment]
Maybe the hole of binutils

---- Mike Manilone编写 ----

It seems that the library is not in the repository this time.

amule: error while loading shared libraries: libbfd-2.25.so: cannot open shared object file: No such file or directory

ldd says:
        libbfd-2.25.so => not found

---
Reply to this email directly or view it on GitHub:
https://github.com/AOSC-Dev/aosc-os-abbs/issues/79

**Comment by Icenowy** [comment]
WTF. I think symlinks needed

- from Xperia Z3

---- Jeff Bai编写 ----

@Arthur2e5 This is a rebuild, because `binutils` updated to 2.25.1.

```
aosc [ ~ ] $ dpkg -S libbfd-2.25
binutils: /usr/lib/libbfd-2.25.1.so
```

A rebuild will be needed. But just a simple bump.

---

**Comment by MingcongBai** [comment]
@Icenowy It is, and it's weird that amule will just link to that library...

**Comment by MingcongBai** [comment]
> WTF. I think symlinks needed

@Icenowy needs change in `aosc-os-core` though, I guess a rebuild will be sufficient?

**Comment by Arthur2e5** [comment]
WTF, I think libtool soname boom

**Comment by biergaizi** [comment]
Don't blame soname, libtool or binutils. It just a feature of aMule for implementing some debugging features for many years.
