### ISSUE TITLE
shadowsocks, shadowsocks-libev: multiple vulnerabilities

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#809]
https://www.x41-dsec.de/lab/advisories/x41-2017-008-shadowsocks/
https://www.x41-dsec.de/lab/advisories/x41-2017-010-shadowsocks-libev/

**Comment by MingcongBai** [comment]
Seems like there's no fix yet? Or did I miss anything...

**Comment by MingcongBai** [comment]
@l2dy Said there's no fix yet (on IRC).

**Comment by l2dy** [comment]
Fix was committed in shadowsocks-libev after I created the issue.

https://github.com/shadowsocks/shadowsocks-libev/commit/c67d275803dc6ea22c558d06b1f7ba9f94cd8de3

**Comment by MingcongBai** [comment]
Please assign an AOSA for https://github.com/AOSC-Dev/aosc-os-abbs/commit/8cb112d79ad72a0e83e0c23e717f599fffaf0022.

**Comment by l2dy** [comment]
Use AOSA-2017-0164 for shadowsocks-libev.

**Comment by MingcongBai** [comment]
@liushuyu This issue is not fully fixed yet, do not put `Ready` marker on this.

**Comment by l2dy** [comment]
Upstream is inactive. https://github.com/shadowsocks/shadowsocks/commits/master

**Comment by l2dy** [comment]
https://github.com/shadowsocks/shadowsocks/commit/e332ec93e9c90f1cbee676b022bf2c5d5b7b1239

**Comment by liushuyu** [comment]
Fixed issues in `shadowsocks-libev`:
- [X]  local command execution

Fixed issues in `shadowsocks`:
- [ ] Log Manipulation
- [X] LCE
- [ ] Incorrect documentation led to unexpected behavior of `autoban.py`
- [ ] Weak key deviation

**Comment by MingcongBai** [comment]
@liushuyu Any updates?

**Comment by MingcongBai** [comment]
@liushuyu Please advise with the newest updates.

**Comment by liushuyu** [comment]
I have just checked, the newer commits did nothing to mitigate any of the vulnerabilities described above.
