### ISSUE TITLE
pgadmin: rename to pgadmin4

### ISSUE THREAD

**Issue by gumblex** [AOSC-Dev/aosc-os-abbs#820]
The name is ambiguous since there are pgAdmin 3 and pgAdmin 4. They are completely different software while their functions are similar.

[1] https://www.pgadmin.org/download/
[2] https://repology.org/metapackage/pgadmin4/versions

**Comment by KexyBiscuit** [comment]
It's actually installed in `/usr/lib/pgadmin4`.

**Comment by MingcongBai** [comment]
Yeah I think @gumblex has a point here... Since pgAdmin 4 is now at v5.0+.

**Comment by MingcongBai** [comment]
Proposing a drop in a new pull request.
