### ISSUE TITLE
postfix: security update to >=3.2.2

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#821]
http://www.postfix.org/announcements/postfix-3.2.2.html

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/85bb52045df2d7ad4f432aea4af99388fcd6c705. Closing.

**Comment by l2dy** [comment]
Use AOSA-2017-0174.
