### ISSUE TITLE
kodi: security update to >=17.3

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#823]
https://kodi.tv/article/kodi-v173-minor-bug-fix-and-security-release

**Comment by MingcongBai** [comment]
Marking `to-staging`, for lack of CVE information and risk definition.

**Comment by MingcongBai** [comment]
Staging fix. Please do not assign AOSA yet.

**Comment by l2dy** [comment]
Use AOSA-2017-0188.
