### ISSUE TITLE
Add Inziu(-iosevka) & Iosevka font family in favour of tsentsiu-sans

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#84]
Inziu is the Chinese part for the font.
[Iosevka](https://github.com/be5invis/Iosevka) is a western font family, generated by nodejs. It features 10-degree italics, which is slighter than common system default (15 deg) and thus fits monospace environments better.

Their combination is Inziu Iosevka. The family Iosevka itself without Inziu should be packaged, too, although we should write fc entrys to let Inziu Iosevka append Iosevka and write `Provides` for Inziu Iosevka.

For the in favour of, don't write `Replaces` stuffs. Just make a test in the `tsentsiu-sans` fc entry, and don't prepend when the list already `contains` inziu stuffs.

http://www.zhihu.com/question/24732078
http://yun.baidu.com/s/1sjp2GO1#path=%252F%25E5%25AD%2597%25E4%25BD%2593%252FInziu
https://be5invis.github.io/Iosevka/

Proposed pkgnames:
* `inziu`: `inziu`, "Hinted SHS for low resolutions", May provide Kaigen (tc tweaks needed, decrease in font weights!).
* `inziu-iosevka`: `inziu-iosevka`, "Hinted SHS plus Iosevka for coding with low resolutions", Provides Iosevka (tc tweaks needed).
* `iosevka` (GitHub): `iosevka`, "Half-width western coding typeface inspired by Pragmata Pro, M+ and PF DIN Mono. Comes with huge charset support and hinting. Generated by nodejs.".

And a metapackage:
* `tsentsiu-alt`: Depends on `inziu` and `inziu-iosevka`, Provides `tsentsiu-sans`, Contains tc naming tweaks.

**Comment by Arthur2e5** [comment]
inziu-20150905.7z is inziu-only, i.e. propotional font. This should be a seperate package.
I will be attaching a pkgname mapping.

**Comment by Arthur2e5** [comment]
`Inziu *m *` families are half-width, but I don't know what those are. SHS HW?

**Comment by MingcongBai** [comment]
Added with 8b903ab68561ba822f21e6491c740e0d13562b86, 0a711f59cee0fe4ddf116a7fa76159cc67f3ce16, ae44f1a48e70094da15217fa453f2f898ad2111b.
