### ISSUE TITLE
rpm: security update to 4.12.0.2

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#841]
http://rpm.org/wiki/Releases/4.12.0.2.html

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/7298dad5b7d1569e76268548a72d2d9b4b1cdbcb. Closing.

**Comment by l2dy** [comment]
Use AOSA-2017-0197.
