### ISSUE TITLE
请求打包deskflow

### ISSUE THREAD

**Issue by Asuku-Cao** [AOSC-Dev/aosc-os-abbs#8596]
https://github.com/deskflow/deskflow

安装deb包时返回依赖缺失

          deskflow : Depends: libei1 (>= 1.0.0) but it is not installable
                     Depends: libglib2.0-0t64 (>= 2.28.0) but it is not installable
                     Depends: libportal1 (>= 0.8.0) but it is not installable
                     Depends: libpugixml1v5 (>= 1.4) but it is not installable
                     Depends: libtomlplusplus3t64 (>= 3.2.0) but it is not installable

**Comment by stdmnpkg** [comment]
required new packages:
- [libei](https://gitlab.freedesktop.org/libinput/libei)
- [libtoml++](https://github.com/marzer/tomlplusplus)
