### ISSUE TITLE
Package Request: noi-guide+32 1.0.2

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#86]
http://download.noi.cn/T/noi/GUIDE-1.0.2-ubuntu.tar
http://bbs.archlinuxcn.org/viewtopic.php?id=2775
http://www.noi.cn/guide-10"

This is an old, proprietary software; It ran on Archlinux, and should run on our system. If it doesn't, we have problem(s).

**Comment by bobcao3** [comment]
I tested and found It could ran on our system. Although it's Qt version is too old. And didn't it have a lisence issue?

**Comment by Arthur2e5** [comment]
Ah, let's make it AUR. (大雾 (AOSC User Repo (逃

**Comment by MingcongBai** [comment]
Probably not in the main tree. But glad to find it working, closing for future reference.

**Comment by Icenowy** [comment]
You'd implement it

**Comment by Icenowy** [comment]
You'd implement it

**Comment by Arthur2e5** [comment]
Fuck you.
