### ISSUE TITLE
kernel: sshd os hint patch?

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#860]
https://lwn.net/Articles/618489/

Basically telling the sshd whether things should be kept in the quick solid part.

**Comment by MingcongBai** [comment]
Very interesting! I might try and integrate that with our 4.14 update.

**Comment by Artoria2e5** [comment]
list archive: https://marc.info/?t=141460793800002

**Comment by MingcongBai** [comment]
Thanks!

**Comment by MingcongBai** [comment]
Stalled (feature/design change) issue, closing. Please open a new issue if this thought arises again. 

@Artoria2e5 Sigh... This seemed to be stalled upstream as well - correct me if I'm wrong (and reopen).
