### ISSUE TITLE
repo: use apt-ftparchive, and re-arrangement of repository structure

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#87]
This issue is currently a stub, information will be appended in lower comments.

**Comment by Arthur2e5** [comment]
Requesting status update.

**Comment by MingcongBai** [comment]
> Requesting status update.

Not yet executed due to busy work in school.

**Comment by Arthur2e5** [comment]
> Not yet executed due to busy work in school.

But you said `apt-ftparchive` found some broken packages (and you deleted them) weeks ago..

**Comment by MingcongBai** [comment]
Still lagging on progress. A report only.

**Comment by MingcongBai** [comment]
Yet again this same magical program fixed our `apt` issue. I will modify our `mirrorupdater` script later today (morning, yawn).

**Comment by liushuyu** [comment]
Re-arrangement has completed.

@MingcongBai Marking as resolved?

**Comment by MingcongBai** [comment]
@liushuyu Please go ahead.

**Comment by liushuyu** [comment]
Marking as resolved
