### ISSUE TITLE
samba: possible data corruption issue

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#870]
https://www.samba.org/samba/history/samba-4.7.2.html
https://bugzilla.samba.org/show_bug.cgi?id=13130
>Yes, I'm afraid I concur with Volker. This can cause file corruption, and the *single* thing file servers must do is not corrupt files. So this is more important than a security release IMHO. Sorry :-(.

**Comment by MingcongBai** [comment]
This should have already been applied, no?

**Comment by MingcongBai** [comment]
I can confirm that the patch has been applied as a part of `4.7.0-1` in `bugfix`.

**Comment by l2dy** [comment]
My bad...
