### ISSUE TITLE
love07: why is this name?

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#876]
LOVE, LÖVE and love2d are reasonable, but why we call it love07?

https://love2d.org/
https://bitbucket.org/rude/love/downloads/?tab=tags
https://packages.aosc.io/packages/love07

BTW, it is 0.10.2 now. (0.7.2 in our repository)

**Comment by Icenowy** [comment]
2017年11月28日 19:13于 Lion Yang <notifications@github.com>写道：
>
> LOVE, LÖVE and love2d are reasonable, but why we call it love07?
>
> https://love2d.org/
> https://bitbucket.org/rude/love/downloads/?tab=tags
> https://packages.aosc.io/packages/love07
>
> BTW, it is 0.10.2 now. (0.7.2 in our repository)

0.7 is not compatible with newer versions.

**Comment by LionNatsu** [comment]
Emmm...indeed. So, what will happen about that version suffix in the future?

Should I request love010 and love011 then ..?
I dimly recalled the pattern `linux-kernel-4.99.99` etc, will it be a better way?

**Comment by MingcongBai** [comment]
`love11` was introduced earlier.
