### ISSUE TITLE
Package Request: python-translate

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/aosc-os-abbs#88]
https://github.com/translate/translate is a set of tools to process XLIFF/PO files.

Other PKGNAME candidates:
* translate-toolkit: offical name.

python-translate is the `setup.py` *programmers'* name.

**Comment by MingcongBai** [comment]
`translate` is a fine name for this package. Considering a Python 3 only build.

**Comment by Arthur2e5** [comment]
@MingcongBai Well, you know, Ubuntu name packages like `python-what`.

**Comment by MingcongBai** [comment]
Yep, but that's not how we did it...

**Comment by MingcongBai** [comment]
Added as `translate-toolkit`, https://github.com/AOSC-Dev/aosc-os-abbs/commit/7c09bfef93ab9c0a116b21a517ebc181cab963f5. Closing.
