### ISSUE TITLE
Should all kinds of `ex` serve as `ed` alternatives?

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#91]

**Comment by MingcongBai** [comment]
Clearer instruction requested.

**Comment by Arthur2e5** [comment]
We know that all `vi` can serve as `ex`, and the original `ex` was a super-`ed`, and they provide a nice one-way compatibility. So `ex` from `neovim`, `vim`, `vi` should also provide alternatives for `ed`.

**Comment by MingcongBai** [comment]
This issue is now self-explanatory in current tree.
