### ISSUE TITLE
raptor2: security vulnerability

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#923]
http://openwall.com/lists/oss-security/2017/06/07/1

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/c878d90c7b80ee0f0248d9270f788b47c463cda2. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0013.
