### ISSUE TITLE
pypy(3): remaining profile code

### ISSUE THREAD

**Issue by gumblex** [AOSC-Dev/aosc-os-abbs#935]
The binaries compiled with `--profopt` still contains profiling code, which writes to the following files:
```
/tmp/usession-release-pypy2.7-v5.9.0-0/testing_1/main.gcda
/tmp/usession-release-pypy3.5-v5.9.0-0/testing_1/main.gcda
```
Before the [issue](https://bitbucket.org/pypy/pypy/issues/2727/pgo-build-remains-profile-code) is resolved, we should just do --lto without --profopt.

**Comment by MingcongBai** [comment]
Wouldn't removing these files resolve this issue?

**Comment by gumblex** [comment]
pypy generates the gcda every time when exits.

**Comment by MingcongBai** [comment]
Oh... Okay, will keep this open as a tracker then.

**Comment by MingcongBai** [comment]
No longer reproducible. Closing.
