### ISSUE TITLE
Source Han Mega OTC

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#942]
Source & Noto CJK in one file. https://github.com/adobe-fonts/source-han-super-otc, those `SourceHanNotoCJK.ttc.z*` files.

**Comment by MingcongBai** [comment]
It could potentially replace the default package. However, we should be mindful of compatibility issues (also, potentially). Marking as `question` and `enhancement` instead.

**Comment by MingcongBai** [comment]
Stalled (feature/design change) issue, closing. Please open a new issue if this thought arises again.
