### ISSUE TITLE
icoutils: multiple CVEs

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#947]
https://access.redhat.com/errata/RHSA-2017:0837

**Comment by l2dy** [comment]
Update to 0.32.2

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/e751013e5e6e881c10343171ef8eea45ffb36a3d. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0028.
