### ISSUE TITLE
transmission: security vulnerability

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#949]
http://openwall.com/lists/oss-security/2018/01/11/1

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/36da87e786e58fa09ddc0a47695c7598f9ed6559. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0030.
