### ISSUE TITLE
squid: SQUID-2018:1 SQUID-2018:2

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#960]
http://www.squid-cache.org/Advisories/SQUID-2018_1.txt
http://www.squid-cache.org/Advisories/SQUID-2018_2.txt

**Comment by MingcongBai** [comment]
This is awkward... 4.0 branch is still marked beta, and no fix available for the stable 3.5 branch.

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/45e92e6c3a3326f95819a7f21be779eba6e9c8b7. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0037.
