### ISSUE TITLE
nodejs: security update to >=9.2.1

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#965]
https://nodejs.org/en/blog/vulnerability/december-2017-security-releases/
https://nodejs.org/en/blog/release/v9.2.1/

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/3878dc3ad495982534d85b8953968bb3e1194b12. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0054.
