### ISSUE TITLE
webkit2gtk: update to 2.18.6

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#966]
https://webkitgtk.org/security/WSA-2018-0002.html

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/1c5d84ec397be006621b543f5f667e76227ed716. Closing.

**Comment by l2dy** [comment]
Use AOSA-2018-0044.
