### ISSUE TITLE
simpy: wrong PKGNAME

### ISSUE THREAD

**Issue by gumblex** [AOSC-Dev/aosc-os-abbs#969]
https://github.com/AOSC-Dev/aosc-os-abbs/blob/d5d632b5e0b1cc7064dba11954e91104aa45c7d5/extra-python/simpy/autobuild/defines#L1

https://packages.aosc.io/packages/pypng

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/38499ab5e7fab681d54ca37a2d4e513f8e7f562b. Closing.
