### ISSUE TITLE
chntpw: switch to a fork, or a fork thereof

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#980]
The old chntpw is pretty much dead and useless, so people have been forking it to add features. [rescatux's version](https://github.com/rescatux/chntpw) adds helpful support for groups, and some more features are added by [others forking their project](https://github.com/rescatux/chntpw/network). I guess we should switch to one of those offshoots for our package.

As a side note it would be great if AOSC could take over some of chntpw's development too. When I accidentally unlocked an admin account on a machine with Deep Freeze today, I was initially left with no means of re-locking the account as `chntpw` only flips the "DISABLED" bit off and no modifications in Windows would persist. I had to hack the source code to reverse its function. Perhaps we should just give users a way to set the entire bitfield to whatever they want.

https://github.com/AOSC-Dev/chntpw/releases/tag/v1.1

**Comment by Artoria2e5** [comment]
I'll start with https://github.com/Googulator/chntpw, fork it over under AOSC-Dev (transfer it to my acct if you don't want it), and merge in some modifications from the original branch. Some `libsam` functions still need I/O pure cleanup.

**Comment by Artoria2e5** [comment]
Ugh, let's not mix the `debian` patches in. They just replicate all changes since `14xxxx`.

**Comment by Artoria2e5** [comment]
So the AOSC branch is pretty much ready now. Should I make a version tag for it?

**Comment by MingcongBai** [comment]
Sure, however... Are we sure that it's appropriate to basically set ourselves as a new upstream now? Or is there anyone we could contribute back to?

**Comment by Artoria2e5** [comment]
Yeah, I guess so. Let me do some Makefile work before tagging though.

**Comment by Artoria2e5** [comment]
Ah Bai, do you think I should make `ntreg` part of `libsam` or make them two different `.so`'s? `libsam` depends on `ntreg`, but not the other way around.

**Comment by MingcongBai** [comment]
I mean if it's not breaking anything let's leave it...

**Comment by Artoria2e5** [comment]
It's abso-fucking-lutely good to go now. I even fixed the make directives for that deprecated crypto part for setting passwords.

**Comment by Artoria2e5** [comment]
Ugh. Upstreaming a fuckton of Debian patches.

**Comment by Artoria2e5** [comment]
https://github.com/AOSC-Dev/chntpw/releases/tag/v1.1
