### ISSUE TITLE
mysql-workbench: Can't get 'MysqlSqlFacade' module when it connect to host

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#990]
Debug Logs
==========

Module `MysqlSqlFacade` is at `/usr/lib/mysql-workbench/modules/db.mysql.sqlparser.grt.so`

Run with `mysql-workbench --log-level=info --log-to-stderr`:
`
[WRN][            grt]: Could not load db.mysql.sqlparser.grt.so: Could not open module /usr/lib/mysql-workbench/modules/db.mysql.sqlparser.grt.so (/usr/lib/mysql-workbench/modules/db.mysql.sqlparser.grt.so: undefined symbol: _ZN12mysql_parser7my_statEPKcP4stati)
`

Unmangle the name, `_ZN12mysql_parser7my_statEPKcP4stati => mysql_parser::my_stat(char const*, stat*, int)`.

The missing symbol is declared at `$SRCDIR/library/sql.parser/source/my_dir.h` and implemented at `/usr/lib/mysql-workbench/libsqlparser.so`

`modules/db.mysql.sqlparser.grt.so ` do have not marked `libsqlparser.so` as NEEDED. That is the problem.

Workaround
==========
Use
```
LD_PRELOAD=/usr/lib/mysql-workbench/libsqlparser.so mysql-workbench
```
instead of
```
mysql-workbench
```

**Comment by MingcongBai** [comment]
Package dropped as orphan (804082070c03229de97b8dec6fabdb9be7dec8cb). Closing.
