### ISSUE TITLE
samba: broken symbol links in /usr/lib

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#991]
Check it out:
```
$ dpkg -S $(sudo ldconfig -v 2>&1 >/dev/null | grep -oP '/usr.*(?=: No such)')
dpkg-query: no path found matching pattern /usr/libx32
samba: /usr/lib/libsmbldap.so
samba: /usr/lib/libregistry.so
samba: /usr/lib/libgensec.so
samba: /usr/lib/libsmbclient-raw.so
samba: /usr/lib/libtorture.so
samba: /usr/lib/libdcerpc-atsvc.so
```
For example: `/usr/lib/libgensec.so` is linking to `libgensec.so.0`, which does not exist.

**Comment by LionNatsu** [comment]
Confirmed on another AOSC OS instance (I mean, dear @StephDC 's).

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/1cad53ebfc39843a676282eeb9ab08fff0765288. Closing. Thanks for the report.
