### ISSUE TITLE
mysql-workbench: bundled shared libraries hijack other programs

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#992]
Currently, the package installs an `/etc/ld.so.conf.d/mysql-workbench.conf`:

    /usr/lib/mysql-workbench
to let mysql-workbench stuff loads these old-bundled-private-shared objects (libraries).

Such order could be a trouble when some libraries do not compose its soname in semantic version, and/or some programs do not use the compatible form of soname (which is a common case). See https://github.com/AOSC-Dev/aosc-os-abbs/issues/863#issuecomment-363074875 .

**Comment by MingcongBai** [comment]
Package dropped as orphan (804082070c03229de97b8dec6fabdb9be7dec8cb). Closing.
