### ISSUE TITLE
brave-browser: security update to >=0.19.147

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#996]
https://github.com/brave/browser-laptop/releases/tag/v0.19.147dev
>Upgraded to Chromium 64.0.3282.119.

**Comment by MingcongBai** [comment]
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/662abf9d3fd141036101fcfeb472c4bc5ab93a64. Closing.
